### ISSUE TITLE
Xamarin.Forms 1.2.3.0 required

### ISSUE THREAD

**Issue by MitchMilam** [jamesmontemagno/Xamarin.Plugins#10]
James,

It would appear that there is a hard dependency on Xamarin.Forms 1.2.3.0.  

I created a 1.3.0 project and after installing ImageCircle and adding the ImageCircleRenderer.Init(); to the AppDelegate on iOS, I get this:

The type 'Xamarin.Forms.Platform.iOS.ImageRenderer' is defined in an assembly that is not referenced. You must add a reference to assembly 'Xamarin.Forms.Platform.iOS, Version=1.2.3.0, Culture=neutral, PublicKeyToken=null'

Thanks, Mitch

**Comment by jamesmontemagno** [comment]
I will take a look today mitch thanks.

**Comment by jamesmontemagno** [comment]
Pushed update for 1.3.0

I will have a pre-release for 1.3.1 in the near future with unified. I am not 100% sure why it locked into that, maybe they changed something under the hood.

Thanks.

**Comment by MitchMilam** [comment]
Thanks. I am not sure what happened.  I tried several variations of installation including installing ImageCircle first and it automatically installed 1.2.3.

**Comment by jamesmontemagno** [comment]
It used to rely on 1.2.3, but I just need to rebuild against 1.3.0. I guess
this is just how the renderers will work, so I need to keep on top of it.

On Thu, Jan 1, 2015 at 12:27 PM, Mitch Milam <notifications@github.com>
wrote:

> Thanks. I am not sure what happened. I tried several variations of
> installation including installing ImageCircle first and it automatically
> installed 1.2.3.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jamesmontemagno/Xamarin.Plugins/issues/10#issuecomment-68492332>
> .
>



-- 
James Montemagno
http://www.montemagno.com
@jamesmontemagno <http://www.twitter.com/jamesmontemagno>
