### ISSUE TITLE
[Bug]Media Plugin crashing on Android Lolipop 5.0

### ISSUE THREAD

**Issue by Jazzeroki** [jamesmontemagno/Xamarin.Plugins#103]
TakePhotoAsync works fine on my Galaxy Tab 10 running Kitkat.  My Samsung Galaxy 5 running Lolipop however routinely crashes.  Sometimes if I set a break point at that function, or if I wait a few minutes before taking a picture then the function might not crash.  However the image I could never get to load into the image view on the S5.  It did load on my tablet.  

This was tested using the latest media plugin on nuget.  Version 1.0.2 and xamarin forms 1.4.4.6392

The code was a copy and paste from the example except I had to change 1 line because an extension appears to have been changed from the example code

**Comment by jamesmontemagno** [comment]
Do you have a stack trace that I could look at?

**Comment by jamesmontemagno** [comment]
Closing no update.
