### ISSUE TITLE
Connectivity Plugin not Updating when connection is restored

### ISSUE THREAD

**Issue by OnTheFenceDevelopment** [jamesmontemagno/Xamarin.Plugins#104]
I've used the plugin in an Android application and it works fine but I'm currently working on an iOS app and am having some odd behaviour.

If I run the application with the device in Flight Mode or with the Wifi turned off (there is no SIM card in this device) then the calls to `IsConnected` correctly return false.
If, with the application still running, I disable Flight Mode or turn Wifi back on and wait for a connection to be restored the calls to `IsConnected` still returns false.

In both of the above scenarios the call to `IsRemoteReachable` also return false.

The method I have is below, this is held in a `static` class:

```csharp
public async static Task<bool> CanConnectToTarget (string targetUrl)
{
	var connected = false;
	var reachable = false;

	connected = Connectivity.Plugin.CrossConnectivity.Current.IsConnected;
	reachable = await Connectivity.Plugin.CrossConnectivity.Current.IsRemoteReachable (new Uri(targetUrl).Authority);

	return connected && reachable;
}
```

It's called from a ViewController as below;

```csharp
var canConnect = await DocumentCache.CanConnectToTarget(_documentUri);
if (canConnect == false) {
   // Code in here to display UIAlertView
}
```

I'm running the latest version of the plugin (1.0.4) and everything else is fully up to date at the time of writing.

**Comment by jamesmontemagno** [comment]
I have tested this on my iOS 9 iPhone 6 with no sim, on wifi and have not seen this issue. Are you still reproducing? It can take a few seconds for it to switch back over.

**Comment by OnTheFenceDevelopment** [comment]
The app will be heading off to the App Store next week so I will be revisiting this issue in the next few days (I'd parked it while I finished off other elements of the app). There have been a few updates to the plugin since I raised the issue so I'll get back to you shortly.

**Comment by OnTheFenceDevelopment** [comment]
Hi James - oddly I cannot replicate this issue any more, maybe I was not waiting long enough before.

I am however still having issues with the plugin - I am using an iPhone 5s, now with a SIM installed and WiFi available. Note that while the phone connects to a 3G network, the SIM has no data access (this is just a pay-as-you-go sim with no credit) - if I attempt to access the internet with Wifi turned off then Safari displays a 'could not connect' message.

Test Scenarios below:
**Scenario 1:**
**Cellular Data Off / WiFi On & Connected**
* Start Application
* Attempt to access web resource - Success

* Disable Wifi (on device)
* Attempt to access web resource - Fails (correct behaviour)

* Enable Wifi (on device)
* Attempt to access web resource - Success

* Disable Wifi (on device)
* Attempt to access web resource - Fails (correct behaviour)

* Enable Wifi (on device)
* Attempt to access web resource - Success

**Scenario 2:**
**Cellular Data On / WiFi On & Connected**
* Start Application
* Attempt to access web resource - Success

* Disable Wifi (on device)
* Attempt to access web resource - Plugin Returns True but request fails (Safari fails to load resource)

* Enable Wifi (on device)
* Attempt to access web resource - Success

It seems that the Cellular data connection is causing some issues. While it is connected it should not be able to reach the specified resource (Safari can't).

**Comment by jamesmontemagno** [comment]
So this seems correct as IsConnected is just alerting you if you are connected to a data source, not that you actually have a data connection. That is what the IsReachable can be used for to a ping to see if you can hit a website. However, that can take some time so should only be used sparingly.

**Comment by OnTheFenceDevelopment** [comment]
I was using IsRemoteReachable as I'm attempting to access a Web Resource - I've updated my code to handle the download failure differently now.

**Comment by jamesmontemagno** [comment]
This is the code that is called: https://github.com/jamesmontemagno/Xamarin.Plugins/blob/master/Connectivity/Connectivity/Connectivity.Plugin.iOS/ConnectivityImplementation.cs#L85-L130

Do you have a different example that is working in your application? 

Perhaps you could run your test by calling into this code: https://github.com/jamesmontemagno/Xamarin.Plugins/blob/master/Connectivity/Connectivity/Connectivity.Plugin.iOS/Reachability.cs#L110-L126

I would rather have it fixed 100% for everyone if there is in fact an issue here.

**Comment by OnTheFenceDevelopment** [comment]
I'll plug that it later this evening and let you know how I get on

Thanks

===============================
David Carson

Contracted / Freelance Software Developer
On The Fence Development (UK)
http://www.onthefencedevelopment.com
===============================

**Comment by OnTheFenceDevelopment** [comment]
Updating my 'reachability' call to 

```csharp
    reachable = Connectivity.Plugin.Reachability.IsHostReachable(targetUrl);
```

Does now fix the issue I was having, with the Cellular Data enable and the Wifi off my method will now return false. However, turning the Wifi back on does not result in reachable returning true - despite being able to access the resource in Safari.

**Comment by OnTheFenceDevelopment** [comment]
Scratch that - I was using `targetUrl` above instead of just pulling the actual domain.

I've just gone through the same test procedure as above with the same results.

I configured two reachable variables so that I could write out to the console and they were consistent with each other during the tests.

**Comment by jamesmontemagno** [comment]
What is your targeturl? There may be something specific with the http or the / at the end that could be causing conflicting results if the test url was working.

**Comment by OnTheFenceDevelopment** [comment]
The target URL was a standard https link to a .pdf file - it returned false
no matter what state the device was in. Pulling out the domain (
www.mydomain.com) means that it now works under 'normal' states (I don't
suppose too many people turn their data connection off - I was just trying
to provoke some connection issues)

===============================
David Carson

Contracted / Freelance Software Developer
On The Fence Development (UK)
http://www.onthefencedevelopment.com
===============================

**Comment by ash032** [comment]
I seem to be having this issue.  
I have an old Samsung Android phone for testing, I have it connected to WiFi and I can browse the internet.  The phone does not have a SIM.

I have the correct permissions set,
`	android:name="android.permission.INTERNET"
	android:name="android.permission.ACCESS_WIFI_STATE"
	android:name="android.permission.ACCESS_NETWORK_STATE"`

 and Isconnected returns true.  

`CrossConnectivity.Current.ConnectionTypes` returns WiFi but when I call 
`CrossConnectivity.Current.IsRemoteReachable("www.apple.com").Result`

the App hangs.  No errors or anything.

**Comment by ash032** [comment]
Hmmm, seems that the  Task.Run was never returning.

Copied the code locally from GitHub  when debugging got to the return statement but then didn't do anything.  Added 
`ConfigureAwait(false)` 

to the task.run and it now seems ok, this was only happening on Android - IOS handled it fine (Xamarin Forms Project)

Ash..
