### ISSUE TITLE
please make "libs-only" version for VS2015

### ISSUE THREAD

**Issue by nohorse** [jamesmontemagno/Xamarin.Plugins#105]
I'm having a hard time installing the nuget package for Xam.plugins.settings and I think it's because of the content delivery.  You are adding some helpers example source files and I think that feature was deprecated in the latest nuget release for VS2015.  I'm trying to work around that now by just adding the libraries, but it would be nice to be able to install this via nuget.

please note that this error only shows up for PCLs and it looks like the following:

Severity	Code	Description	Project	File	Line
Error		Could not find a part of the path 'C:\Users\Mark\.nuget\packages\Xam.Plugins.Settings\1.5.2\content\portable-net45%2Bwp8%2Bwpa81%2Bwin8%2BMonoAndroid10%2BMonoTouch10%2BXamarin.iOS10\Helpers\Settings.cs.pp'.			0

**Comment by jamesmontemagno** [comment]
Take a look here for work around: https://github.com/jamesmontemagno/Xamarin.Plugins/issues/86
