### ISSUE TITLE
[Feature Request] Settings plugin - Secure storage for sensitive data (passwords, etc)

### ISSUE THREAD

**Issue by daniel-luberda** [jamesmontemagno/Xamarin.Plugins#106]
It would be very nice to have **secure settings storing** functionality for things like passwords, session tokens, etc implemented with platform specific API's ensuring security. It could be done just the same as Xamarin.Auth plugin account storing (**backed by the Keychain on iOS and a KeyStore on Android**). What do You think about it?

**Comment by jamesmontemagno** [comment]
Would it just be strings?

**Comment by daniel-luberda** [comment]
Actually, it could be possible to store serialized objects but I don't know really know if it's really needed. The limits for text size for iOS Keychain and Android Keystore are quite large (eg. see: http://stackoverflow.com/questions/13488793/is-there-any-length-limit-of-string-stored-in-keychain). 

On Windows there's PasswordVault for passwords and Data Protection API (DPAPI) for larger files 
https://msdn.microsoft.com/en-us/library/windows/apps/windows.security.credentials.passwordvault.aspx and https://msdn.microsoft.com/en-us/library/windows/apps/hh464970.aspx

for Xamarin iOS example: https://github.com/xamarin/Xamarin.Auth/blob/master/src/Xamarin.Auth.iOS/KeyChainAccountStore.cs

for Xamarin Android example: 
https://github.com/xamarin/Xamarin.Auth/blob/master/src/Xamarin.Auth.Android/AndroidAccountStore.cs

**Comment by alexrainman** [comment]
This plugin do something like that. I haven't tested. Don't know if works from PCL https://github.com/has-taiar/KeyChain.Net

**Comment by sameerkapps** [comment]
Just published this one for securely storing strings. Please check it out.
http://www.nuget.org/packages/sameerIOTApps.Plugin.SecureStorage/

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/SettingsPlugin#9
