### ISSUE TITLE
Could not add Xam.Plugin.Geolocation in Xamarin Studio

### ISSUE THREAD

**Issue by georgeedwards** [jamesmontemagno/Xamarin.Plugins#108]
I just tried to install the plugin into a PCL project (based on [this](https://github.com/conceptdev/xamarin-forms-samples/tree/master/BluetoothHeartRateMonitor) example). I am using Xamarin Studio 5.9.5 (build10) on OSX Yosemite 10.10.5. When I add the Nuget, the dialogue at the top says "Could not add xam.plugin.geolocator" and the log generated is copied below. Although I did remove some of the files added, as the log was pretty hard to read and I didn't think them relevant. 
>>Adding Xam.Plugin.Geolocator...
>>Installing 'Xam.Plugin.Geolocator 1.0.4'.
>>Added file 'Geolocator.Plugin.dll' to folder 'Xam.Plugin.Geolocator.1.0.4/lib/portable-net45+wp8+wpa81+win8+MonoAndroid10+MonoTouch10+Xamarin.iOS10'.
>>// added more files
>>Added file 'GeolocatorReadme.txt.pp' to folder 'Xam.Plugin.Geolocator.1.0.4/content/Xamarin.iOS10/PluginsHelp'.
>>Added file 'Xam.Plugin.Geolocator.1.0.4.nupkg' to folder 'Xam.Plugin.Geolocator.1.0.4'.
>>Successfully installed 'Xam.Plugin.Geolocator 1.0.4'.
>>Adding 'Xam.Plugin.Geolocator 1.0.4' to HeartRateMonitor.
>>For adding package 'Xam.Plugin.Geolocator 1.0.4' to project 'HeartRateMonitor' that targets 'portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarinios10',
>> Assembly references are being added from 'lib/portable-net45+wp8+wpa81+win8+MonoAndroid10+MonoTouch10+Xamarin.iOS10'
>> Content files are being added from 'content/portable-net45+wp8+wpa81+win8+MonoAndroid10+MonoTouch10+Xamarin.iOS10/PluginsHelp'
Added file 'GeolocatorReadme.txt' to folder 'PluginsHelp'.
Added file 'packages.config'.
Added file 'packages.config' to project 'HeartRateMonitor'.
An exception was thrown while dispatching a method call in the UI thread.`

**Comment by jamesmontemagno** [comment]
I would need more info on this as I don't see the exception. Maybe just create a gist of it for me.

**Comment by georgeedwards** [comment]
here is the full log from the .ios project
https://gist.github.com/georgeedwards/80ffe8dfb9b912508262

**Comment by mrward** [comment]
@georgeedwards - The IDE log is what is needed. In Xamarin Studio open the Help menu and select Open Log Directory. The full exception callstack should be shown in the IDE log.

**Comment by georgeedwards** [comment]
Apologies, how about this?
https://gist.github.com/georgeedwards/ad805894e93a35ab233c

**Comment by mrward** [comment]
@georgeedwards - That log file looks old. It has entries from four days ago. I cannot see any exceptions from NuGet in it. I would reproduce the error and get the latest log file that has been created.

**Comment by georgeedwards** [comment]
It seems to be working now?
