### ISSUE TITLE
Unable to get background location updates iOS 9

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/Xamarin.Plugins#109]
Via this discussion:
https://twitter.com/zezioen/status/646651277456330752

https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocationManager_Class/#//apple_ref/occ/instp/CLLocationManager/allowsBackgroundLocationUpdates

Proposal:

Add a new boolean on IGeolocator called AllowsBackgroundUpdates. If this is set for iOS 9 I will trigger the AllowsBackgroundLocationUpdates to this value. However, you must update the info.plist with the correct information.

**Comment by jamesmontemagno** [comment]
Please see new beta package: https://www.nuget.org/packages/Xam.Plugin.Geolocator/1.1.0-beta1

**Comment by zezioen** [comment]
Tested the beta and the plugin works again. Thanks for the quick response!
