### ISSUE TITLE
Doubts in settings plugin

### ISSUE THREAD

**Issue by saramgsilva** [jamesmontemagno/Xamarin.Plugins#11]
In the plugin Settings you have

![](http://content.screencast.com/users/JamesMontemagno/folders/Jing/media/7466bca6-a916-4fd9-9301-3c3403d3a6ad/00000097.png)

but in Visual Studio 2013 using Xamarin Plugin I have

![xamarin-issue1](https://cloud.githubusercontent.com/assets/2135829/5683009/40aac370-981c-11e4-9fd6-cf1062b4fdf3.png)

Can you clarify it, please? I am trying to use it in a demo about Notification Hubs.

**Comment by jamesmontemagno** [comment]
This is a good question, I have never had an issue in VS. It should be fine, but I am asking the team why that box is never enabled.
