### ISSUE TITLE
IOS Geo Locator

### ISSUE THREAD

**Issue by javierantonioizquierdo** [jamesmontemagno/Xamarin.Plugins#110]
Hi

I discovered a small problem with GeoLocator. After 15 minutes stop updating if I don't moving to another location. I found the problem. Testing using CLLocationManager and set PausesLocationUpdatesAutomatically = false. Doing that the GeoLocator doesn't stop. I thing you need to add that setting like you did with AllowsBackgroundLocationUpdates for IOS 9.

I will very happy if you can fix that. You tools are very good.

Thanks

**Comment by martijn00** [comment]
Yes, it would be good if you can make a pull request to fix that!

**Comment by jamesmontemagno** [comment]
Adding in 1.1.1
