### ISSUE TITLE
[Settings] Could not find a part of the path

### ISSUE THREAD

**Issue by tblion** [jamesmontemagno/Xamarin.Plugins#112]
Hello,

I can't install this Nuget Package.

I have this error : 
Could not find a part of the path 'C:\Users\Thomas\ .nuget\packages\Xam.Plugins.Settings\1.5.2\content\portable-net45%2Bwp8%2Bwpa81%2Bwin8%2BMonoAndroid10%2BMonoTouch10%2BXamarin.iOS10\Helpers\Settings.cs.pp'.	

But the file is in the folder !

Vibration plugin is working so my installation is good.

Any idea ?

**Comment by jamesmontemagno** [comment]
Please see: https://github.com/jamesmontemagno/Xamarin.Plugins/issues/86
