### ISSUE TITLE
CameraDevice.Front doesn't seem to work on Android

### ISSUE THREAD

**Issue by heiser** [jamesmontemagno/Xamarin.Plugins#113]
I have specified CameraDevice.Front in the options, which works in iOS. However, it seems that it is not acknowledged in Android. Am I missing a step, or is this functionality not yet implemented on Android?

**Comment by jamesmontemagno** [comment]
I have attempted to get this working, but each camera and phone is different when launching an external app to take a photo: http://stackoverflow.com/questions/19667094/intent-does-not-set-the-camera-parameters/19670928#19670928

However, you can now attempt to use the parameter.
