### ISSUE TITLE
iOS9 location only returned on timeout.

### ISSUE THREAD

**Issue by kolchy** [jamesmontemagno/Xamarin.Plugins#115]
If I await for 10s for my location, I get the users location after 10s:

    await locator.GetPositionAsync(10000);

If I set the timeout to be 1s, I get the position after 1s:

    await locator.GetPositionAsync(1000);

It seems the location is only be returned when the async call times out?

**Comment by jamesmontemagno** [comment]
Are you running this on a device or an emulator? There is a new compass thing that has to be calobrated on the device/simulator. I have run my sample on a device and haven't had any issues.

**Comment by Vandersteen** [comment]
I tested this on several different devices running IOS9 and 9.1 and I have the same issue.

Putting the timeout on 10 000 makes the app wait 10 sec before a response comes out.

Idem for 1000

**Comment by jamesmontemagno** [comment]
Make sure you have a location set on your simulator.

I am adding some more error handing in here too.

**Comment by kolchy** [comment]
This was on device...

**Comment by jamesmontemagno** [comment]
Interesting, I have had absolutely no issues here, just tested it. With my new check it may timeout faster though.  Pushing 1.1.1 soon, so give that a test.

**Comment by kolchy** [comment]
Will do

**Comment by jamesmontemagno** [comment]
This is my sample: http://screencast.com/t/M052pgTeRcx  

If there is some timeout and it couldn't get the location it will wait fully if an exception hasn't been thrown. 

I added a sample app to the repo too. You could see what happens here: https://github.com/jamesmontemagno/Xamarin.Plugins/blob/master/Geolocator/Geolocator/Geolocator.Plugin.iOS/GeolocationSingleUpdateDelegate.cs#L80
