### ISSUE TITLE
Connectivity plugin in windows desktop application

### ISSUE THREAD

**Issue by galex66** [jamesmontemagno/Xamarin.Plugins#116]
I'm using the plugin Connectivity in a Xamarin Forms App, I need to use in a Windows desktop application, honestly I did not understand why it should not be compatible, because it is compatible with windows store. 
I can use it and how do

Can you help me ?

**Comment by jamesmontemagno** [comment]
I haven't provided an implementation yet for anything windows desktop at this point. Are you building a WPF app? would need to call into the actual APIs for Windows to handle this.

**Comment by galex66** [comment]
No, it isn't a WPF app, but only a library.
I have done a own plugin for some function

**Comment by jamesmontemagno** [comment]
Feel free to contribute and add in another platform if you would like :)
