### ISSUE TITLE
Settings - Possibility of extending the plugin in WPF Platform

### ISSUE THREAD

**Issue by gtas-verisk** [jamesmontemagno/Xamarin.Plugins#118]
Is it possible to extend and create an ISettings class to use the plugin in my WPF platform project?

I see that you are using internally a Lazy object that returns a new Refractored.Xam.Settings,Settings() class. Since this class is missing after I tried adding the Nuget package in the WPF project and throws a NotImplementedException, looking for a way to add my own implementation.

Any ideas of achieving this?

**Comment by jamesmontemagno** [comment]
I don't have it implemented currently at all, but would be a simple extension. I just don't have the bandwidth currently. However there is an older pull request that has an example.
