### ISSUE TITLE
Geolocator: Crash on iOS 8.4 on simulator when Location is set to None

### ISSUE THREAD

**Issue by gnola14** [jamesmontemagno/Xamarin.Plugins#119]
If I make the following call 

```await CrossGeolocator.Current.GetPositionAsync(10000).ConfigureAwait(false);```

while running it on the simulator, setting the Location to None on iOS 8.4 makes it crash with a

```-[CLLocationManager allowsBackgroundLocationUpdates]: unrecognized selector sent to instance <some hex number>```

I haven't been able to create a minimal test case, but it does happen consistently on my app. However, the error seems to be gone if I modify ```Failed``` method of ```GeolocationSingleUpdateDelegate```

```
public override void Failed(CLLocationManager manager, NSError error)
{
	switch((CLError)(int)error.Code)
	{
	case CLError.Network:
		StopListening();
		this.tcs.TrySetException(new GeolocationException(GeolocationError.PositionUnavailable));
		break;
	case CLError.LocationUnknown:
		StopListening();
		this.tcs.TrySetException(new GeolocationException(GeolocationError.PositionUnavailable));
		break;
	}
}
```

**Comment by jamesmontemagno** [comment]
I can add that case in there, but there is no possible way that allowsBackgroundLocationUpdates could be called on iOS 9, I am doing a system number check when setting it and it would only be enabled if you set it to true too.

**Comment by gnola14** [comment]
I know, that was the first thing I checked, both the source code (to see if
system number check was there) and also on my Info.plist if I had
inadvertently added that property. That's why I was puzzled with the
exception.

2015-10-25 5:26 GMT-02:00 James Montemagno <notifications@github.com>:

**Comment by jamesmontemagno** [comment]
Committing and pushing today

**Comment by gnola14** [comment]
Awesome, thanks James!
