### ISSUE TITLE
Circle Image control - For linking.... means?

### ISSUE THREAD

**Issue by jsinh** [jamesmontemagno/Xamarin.Plugins#120]
Hello James,

I am bit new to the XAMARIN / XF world so need to ask it right away.

On the readme file for Circle Image Control - I see you mentioned following:

>Final Builds For linking you may need to add:
>Android:
>`ImageCircle.Forms.Plugin.Abstractions;ImageCircle.Forms.Plugin.Android;`
>iOS:
>`--linkskip=ImageCircle.Forms.Plugin.iOS --linkskip=ImageCircle.Forms.Plugin.Abstractions`

I am not sure what linking means. But if I use this library to show circled images in an app, this would also get released to stores (Android & Apple) and will be distributed for testing to HockeyApp and TestFlight. Does your above state apply to my current situation or should I just ignore it.

If you can explain what does linking mean for this library and how exactly can I do it if needed?

**Comment by jamesmontemagno** [comment]
Be sure to read through: https://developer.xamarin.com/guides/android/advanced_topics/linking/ and https://developer.xamarin.com/guides/ios/advanced_topics/linker/

What you are doing it just telling the compiler to ignore the the assemblies. These are in the project build settings.

**Comment by jsinh** [comment]
That makes sense, thanks a lot for the reference!
