### ISSUE TITLE
Geolocator return always false on android M

### ISSUE THREAD

**Issue by stepkillah** [jamesmontemagno/Xamarin.Plugins#122]
After update android m, cross geolocator fail to get location

**Comment by jamesmontemagno** [comment]
You will have to ask for Fine&Course Location permissions via the new runtime permissions.
https://blog.xamarin.com/requesting-runtime-permissions-in-android-marshmallow/

See this example: https://github.com/jamesmontemagno/MarshmallowSamples/blob/master/RuntimePermissions/MarshmallowPermission/MainActivity.cs

Or you can set your target to 22 in the project settings.

The Geoloator does not handle this on Android as it is part of the Activity to request permissions.
