### ISSUE TITLE
Android 6 Marshmallow doesn't open camera activity

### ISSUE THREAD

**Issue by mstryb** [jamesmontemagno/Xamarin.Plugins#123]
Hi there.
I have this code, and after upgrading to Android 6.0 it stoppped working. Doesnt even throw any error. Just nothing happens, while on any other Android it works like a charm.

                    StoreCameraMediaOptions options = new StoreCameraMediaOptions();
                    options.Name = Configuration.config_UserPhoto_TempName;
                    options.Directory = Configuration.path_App_Storage_Path;
                    var intent = picker.GetTakePhotoUI(options);
                    StartActivityForResult(intent, IntentRequestCode.CapturePhoto);

**Comment by mstryb** [comment]
What's strange, is that I can do this and it works.

                                    var intent = picker.GetPickPhotoUI();
                                    StartActivityForResult(intent, IntentRequestCode.CapturePhoto);
                                    alertDialog.Dismiss();

**Comment by LostBalloon1** [comment]
I can confirm. I have the same issue on my nexus 5 running marshmallow, picking a photo works, trying to capture (picture or video) does not even pop the camera up. Doesn't crash, just instantly returns null. I haven't had the chance to run it using the source code (and probably won't anytime soon). I suspect the library's code throws an exception that is internally handled to return null.

**Comment by jamesmontemagno** [comment]
Interesting, you should be to pull down the source code and run the sample app in the Media solution. 

I don't have any Marshmallow devices with me this week, but can look into it soon when I get back to Seattle on Sunday. I am sure we can figure this out though.

**Comment by jamesmontemagno** [comment]
Also, what are your settings for the project so I can repo? Are you compiling with 6.0, also what is min an target APIs for project?

**Comment by mstryb** [comment]
Hey!
Min api level is 2.3, max is 6.0, compiling with 6.0.
This code works fine on any other android version, just not on 6.0

**Comment by jamesmontemagno** [comment]
So, the camera plugin requires: WRITE_EXTERNAL_STORAGE for taking photos. Can you request the Read/Write external storage permissions (Storage). https://blog.xamarin.com/requesting-runtime-permissions-in-android-marshmallow/  If you have AppCompat.v4 installed you can use the ContextCompat. 

I will update my sample in the future to test this out.

**Comment by mstryb** [comment]
Yes. This solved everything :) Thanks a lot!

**Comment by ahmadalibaloch** [comment]
Not solved for me. I have this permission to WRITE_EXTERNAL_STORAGE and also CAMERA but still it returns null for camera.open() and camera.open(0) too. Nexus 5 with Android 6.0.1.
