### ISSUE TITLE
Media plugin not working in Window Phone 8.1 RT

### ISSUE THREAD

**Issue by ibrahimAJ** [jamesmontemagno/Xamarin.Plugins#125]
var file = await CrossMedia.Current.TakePhotoAsync(new Media.Plugin.Abstractions.StoreCameraMediaOptions
								{

									Directory = "Photo",
									Name = "Photo.jpg"
								});
when try to run this in emulator it throw Xml Parse error in my PCL, and in device no response it hanged.

even after add this 

        protected override void OnActivated(IActivatedEventArgs args)
        {
             MediaImplementation.OnFilesPicked(args);
       
             base.OnActivated(args);
        }

in App.xaml.cs file in window project

**Comment by jamesmontemagno** [comment]
Checkout the latest 2.0.0: https://www.nuget.org/packages/Xam.Plugin.Media/2.0.0-alpha2

Releasing to stable tomorrow and has been working well for me.

**Comment by ibrahimAJ** [comment]
how to implement in PCL? ... it work well with shared project(previously also). when i trying to used in PCL, it show the same error again.

**Comment by jamesmontemagno** [comment]
Fixed officially in 2.5.1-beta33! Tested and shipped!
