### ISSUE TITLE
Error while trying to set up the project for Xamarin.Forms Control Plugin

### ISSUE THREAD

**Issue by tkowalczyk** [jamesmontemagno/Xamarin.Plugins#13]
I am trying to use this VS extension from you: 
https://visualstudiogallery.msdn.microsoft.com/afead421-3fbf-489a-a4e8-4a244ecdbb1e
but after selecting Plugin Control for Xamarin.Forms I am getting this error:
![2015-01-15 12_42_06-ij gestureframe - microsoft visual studio](https://cloud.githubusercontent.com/assets/1682564/5756779/99614836-9cb3-11e4-9c26-2d7437b164cc.png)

**Comment by jamesmontemagno** [comment]
Please ensure that you have the latest version of nuget package manager: http://kb.xamarin.com/customer/portal/articles/1772629-you-are-trying-to-install-this-package-into-a-project-that-targets-xamarin-ios10

**Comment by tkowalczyk** [comment]
Yes that was it!
THX
