### ISSUE TITLE
Media picker is not working in Galaxy Note2 and Note3.

### ISSUE THREAD

**Issue by TunTunAg** [jamesmontemagno/Xamarin.Plugins#130]
I used media picker (from the Xlabs) in my Xamarin app. Its working in Xiomi note, Nexus 6,LG and Mi3 W.
But when I test with Note2 and Note3. Its crash when tacking photo or select the photo from gallery.
I try to use the CrossMedia plugin. Still crash.
Pls, help me. Is there any other idea?

I added the permission on manifest as follow:

android.permission.CAMERA And android.permission.WRITE_EXTERNAL_STORAGE

**Comment by cbartonnh** [comment]
I think you might need android.permission.READ_EXTERNAL_STORAGE as well.

**Comment by jamesmontemagno** [comment]
Merging this with #128

**Comment by TunTunAg** [comment]
hi @cbartonnh I added as your advice but still the same issue.
