### ISSUE TITLE
CrossDeviceInfo.Current.Id returns "unknown" in Xamarin Android Player

### ISSUE THREAD

**Issue by mrbelk** [jamesmontemagno/Xamarin.Plugins#132]
I'm trying to use the CrossDeviceInfo.Current.Id property in my software's device licensing scheme.  When I'm testing in the xamarin android player, it just returns "unknown."  I assume that's because the player itself doesn't implement that completely (I haven't run on an actual device yet), but I would think that for consistency this call should return _something_ since it makes testing this sort of feature pretty difficult.

**Comment by jamesmontemagno** [comment]
There really isn't much I can do here as I am calling Build.Serial: http://developer.android.com/reference/android/os/Build.html#SERIAL 

It does have the ability to not be set. I haven't seen any issues on device, but you may want to google around. You could check against "unknown" and then generate a unique guid and save into settings with the settings plugin.

**Comment by mrbelk** [comment]
Understood.  Anyway you could put in a good word to the folks building the player images to include an implementation for Build.Serial in the player, so that this can more closely reflect how "real" devices work?
