### ISSUE TITLE
[Feature Request]Expose a getpath method

### ISSUE THREAD

**Issue by bebo109** [jamesmontemagno/Xamarin.Plugins#133]
```
file = await CrossMedia.Current.TakePhotoAsync (new Media.Plugin.Abstractions.StoreCameraMediaOptions {
					Directory = "directory",
					Name = "name'
				});
```
There is currently no way to know where the file will be stored, until after it is captured.
Can you expose a getpath method?

**Comment by jamesmontemagno** [comment]
Is there a reason for this? It is calculated right before you take the photos based on the MediaOptions.
