### ISSUE TITLE
Lenovo a6000 plus return contacts null

### ISSUE THREAD

**Issue by jaganjan** [jamesmontemagno/Xamarin.Plugins#136]
contact plugin works expected in some of devices but i was tested in lenovo device[mention device detail in bug title]its failed to get the contact details.

Here is my code

public override async void OnActivityResult(int requestCode, int resultCode, Intent data)
        {
            if (requestCode != PICK_CONTACT_REQUEST) return;
            // Make sure the request was successful
            if (resultCode != (int)Result.Ok) return;
            if (data?.Data == null) return;
            var addressBook = new Xamarin.Contacts.AddressBook(Activity) { PreferContactAggregation = false };
            //iam geting null  for this line
            var contact = addressBook.Load(data.Data.LastPathSegment);
            //but actual is contact=null
            // expected result is contact

            var phoneNo = contact?.Phones?.ToList();
            if (phoneNo == null) return;
            var mobileNo =
                phoneNo.Where(p => p.Type == Xamarin.Contacts.PhoneType.Mobile)
                    .Select(p => p.Number)
                    .FirstOrDefault();

        }

**Comment by jamesmontemagno** [comment]
I can not solve device specific issues that you are having. You need to ensure that permissions are set. If you are on Android 6.0 you need to request proper permissions.

**Comment by jaganjan** [comment]
i already set Read_contacts permission .ok  i will looking the plugin code ,i will fix the bug asap..

**Comment by jamesmontemagno** [comment]
If you find it please feel free to send a pull request.
