### ISSUE TITLE
ConnectivityPlugin.ConnectivityChanged not working on iOS for an XForms App

### ISSUE THREAD

**Issue by aunanue** [jamesmontemagno/Xamarin.Plugins#137]
I'm using the ConnectivityPlugin for detecting changes in the connections for a XF App.

Connectivity.Plugin.CrossConnectivity.Current.ConnectivityChanged += (sender, e) => { ....; };

The event is triggered on Android, that works excellent but on iOS it is never triggered.

I tried with iPhone using iOS 9 and also on Tablets with iOS 7/8 and the event is never triggered on iOS.

According to the readme for iOS there's nothing special to configure on the App to make it work. 
Is this a known issue? Do I need to assign any background Modes to the iOS App?

Plugin Version: 1.0.4
Xamarin.Forms Version: 1.5.0.6447

Cheers
Ariel

**Comment by jamesmontemagno** [comment]
Are you putting them into Airplane mode? This has been working fine for me since I originally launched the plugin.

**Comment by aunanue** [comment]
No, no airplane mode.
I have the Connectivity.Plugin.CrossConnectivity.Current.ConnectivityChanged += (sender, e) => { ....; }; on a ViewModel that is created when the MainPage is created. Again on Android works excellent. 

I placed a Debug.Writeln("ConnectivityChanged"); in the event to make sure it is not a problem with the breakpoint or on my business code so I have only one line with "Debug.Writeln("ConnectivityChanged");" as the event implementation.

I do as follows: 
with the App running, I tap the home button of the iPhone, move to settings. Here I changed from one Wi-Fi network to another. That didn't triggered the event. I also tried to turn off the Wi-Fi settings so no connection will be in place and that does not work either.
I just tried this on a iPhone 5 with iOS 9 running the App in Debug mode.

**Comment by avorobjovs** [comment]
Hi,

One of our client has a problem with connectivity detection when he switch into into Airplane mode. He has an Apple iPad Air. Our app using Xamarin.Forms and the Connectivity.Plugin for it.

Is there a solution for this problem?

Best Regards,
Aleksandrs

**Comment by jamesmontemagno** [comment]
I can not reproduce this at all on iOS 9 on a physical device. I have tried over and over again and no issues at all as it triggers the change each and every time.  You may receive multiple events when coming to and from the application though. If you swipe up from the bottom of the screen you can toggle to airplane mode and see it working. I have tried 2 apps with the nuget and with the dlls directly.

I am using Reachability from here: https://developer.xamarin.com/recipes/ios/network/reachability/detect_if_network_is_available/

**Comment by aunanue** [comment]
Ok, no worries. I'll reinstall the plugin again to see if it helps.
 Thanks for the support

**Comment by Plofstoffel** [comment]
I had the same issue,

It was due to "fault" of my own. I Added and removed the event on sleep and resume.
`protected override void OnResume()
{
CrossConnectivity.Current.ConnectivityChanged += ConnectivityChanged;
}`
`protected override void OnSleep()
{
CrossConnectivity.Current.ConnectivityChanged -= ConnectivityChanged;
}`

On iOS the OnSleep gets called when you swipe from the bottom or press the home button. Thus the event will never fire.

Hope this helps someone ;)
