### ISSUE TITLE
Settings Plugin - Android - Loses decimal part when storing/reading doubles

### ISSUE THREAD

**Issue by rdelrosario** [jamesmontemagno/Xamarin.Plugins#14]
Checking the code this is because doubles read/store as long. On Android Library : Xamarin.Plugins/Settings/Refractored.Xam.Settings.Android/Settings.cs
///////////////////////////////////// --- On Read

       case TypeCode.Double:
            value = (double)SharedPreferences.GetLong(key, (long)Convert.ToDouble(defaultValue, System.Globalization.CultureInfo.InvariantCulture));
            break;

////////////////////////////////////// ---- On Store

        case TypeCode.Double:
            SharedPreferencesEditor.PutLong(key, (long)Convert.ToDouble(value, System.Globalization.CultureInfo.InvariantCulture));
            break;

**Comment by jamesmontemagno** [comment]
Intriguing, yes this is a bug, let me see how best to fix.

**Comment by jamesmontemagno** [comment]
I believe the same would be true for decimal.

**Comment by jamesmontemagno** [comment]
I will most likely have to save out to a string and convert back as there is no double/decimal in shared preferences. I will have a fix in my next release 1.5.0 when I implement a remove method. 

I may have to put some error correct in there as since I will be changing the stored type into shared preferences if you stored it previously and it is a long it will throw an exception. There are 2 options:

1.) Automatically remove the key and reset it
2.) Release note that you will have to remove or change key

Thoughts?

**Comment by rdelrosario** [comment]
Hi James

Yes that's the workaround i did after finding out the bug. I save it and
get it as a string then parse it to double. Same applies for decimals.

I think the best option is number 2. Because we don't know the current
state of the apps using the plugin, so might be the safest track.

**Comment by jamesmontemagno** [comment]
I have released this as alpha today: https://www.nuget.org/packages/Xam.Plugins.Settings/2.0.0-alpha

Please test and let me know

**Comment by rdelrosario** [comment]
Tested. Is fixed.

Thanks.

**Comment by jamesmontemagno** [comment]
Good to know ;) I made this a 2.0.0 release since there is a breaking
change.

Thanks for reporting this.

**Comment by jamesmontemagno** [comment]
@rdelrosario 

So it seems like I could also do this:

```
 //Android doesn't have decimal in shared prefs so get string and convert
            var savedDecimal = string.Empty;
            try
            {
              savedDecimal = SharedPreferences.GetString(key, string.Empty);
            }
            catch(Java.Lang.ClassCastException cce)
            {
              try
              {
                var temp = (decimal)SharedPreferences.GetLong(key, (long)Convert.ToDecimal(defaultValue, System.Globalization.CultureInfo.InvariantCulture));
                savedDecimal = temp.ToString();
              }
              catch (Java.Lang.ClassCastException cce2)
              {
              }
              Remove(key);
              Console.WriteLine("Settings 2.0 breaking change, have to remove key.");
            }
```

I attempt to get our new string out.. which it will be most of the time and for anyone new. Else I can get the long out of there, remove the key and re-insert it...

**Comment by jamesmontemagno** [comment]
Check out these changes: https://github.com/jamesmontemagno/Xamarin.Plugins/commit/27f663c927de4e51f7e490f6d0342b290301ff59

I now do a smooth upgrade transition :)

**Comment by rdelrosario** [comment]
Oh good approach!
On Jan 23, 2015 5:55 PM, "James Montemagno" <notifications@github.com>
wrote:

Check out these changes: 27f663c
<https://github.com/jamesmontemagno/Xamarin.Plugins/commit/27f663c927de4e51f7e490f6d0342b290301ff59>

I now do a smooth upgrade transition :)

—
Reply to this email directly or view it on GitHub
<https://github.com/jamesmontemagno/Xamarin.Plugins/issues/14#issuecomment-71273123>
.

**Comment by jamesmontemagno** [comment]
1.5.0 has been released now
