### ISSUE TITLE
Assemblies in nuget package not signed

### ISSUE THREAD

**Issue by netsrotr** [jamesmontemagno/Xamarin.Plugins#141]
I like to use them in our projects, but the requirement here is to strongly sign all our assemblies. So referencing and use these Settings result now in this build failures:

Assembly generation failed -- Referenced assembly 'Refractored.Xam.Settings' does not have a strong name
Assembly generation failed -- Referenced assembly 'Refractored.Xam.Settings.Abstractions' does not have a strong name	

Is there a chance to get a signed version without "take over" the project from github and recompile to string named assemblies?

**Comment by jamesmontemagno** [comment]
I have no plans on strong naming as that is a bad idea in mobile apps.

You can use StrongNamer though: https://github.com/dsplaisted/strongnamer
