### ISSUE TITLE
Connectivity Plugin doesn't work on all WinPhone devices in Silverlight mode

### ISSUE THREAD

**Issue by avorobjovs** [jamesmontemagno/Xamarin.Plugins#142]
Hi,

We have an Xamarin.Forms application and use Connectivity Plugin.
One of our target platform is WinPhone. We use Silverlight 8.0 app on WinPhone for some reasons.

But now we have an issue that Connectivity Plugin doesn't work on all WinPhone devices.
For example, it works successfully on Lumia 920 device, but doesn't work on Lumia 830 device.

On Lumia 830 device it doesn't show current connectivity state at all.
- The Connectivity.Plugin.CrossConnectivity.Current.IsConnected == TRUE all time. 
- And the Connectivity.Plugin.CrossConnectivity.Current.ConnectivityChanged event is not triggered at all.
- But in the Connectivity.Plugin.CrossConnectivity.Current.ConnectionTypes list there are two "Other" connection all time additionally to the real connection. Even if all real connections are disabled.

We use Xamarin.Forms 1.5.0.6447 and Connectivity.Plugin 1.0.4

Is there some fixes or workarounds?

Best Regards,
Aleksandrs

**Comment by jamesmontemagno** [comment]
I can not detect device specific issue, I would recommend cloning the repository and creating a test project with the actual code to debug though. WP Silverlight is known for not being consistent in the changes even in the Microsoft documentation. If it is working on one phone that means it is implemented correctly.

**Comment by jamesmontemagno** [comment]
I updated the code here to match RT in the 2.0.0-alpha 2. Test that out and let me know your results.

**Comment by avorobjovs** [comment]
I have tested the 2.0.0-alpha2 version. It works almost good. Now events are sent to the portable class CrossConnectivity.

But I have some comments.

1) Since NetworkAvailabilityChanged and NetworkAddressChanged events are triggered several times on each network change you use the special check:

```
private void UpdateStatus()
{
    bool previous = isConnected;
    if (previous != IsConnected)
    {
        Deployment.Current.Dispatcher.BeginInvoke(() =>
        {
            OnConnectivityChanged(new ConnectivityChangedEventArgs { IsConnected = IsConnected });
        });
    }
}
```

But you forget that the "IsConnected" property is not set the "isConnected" filed now. So, please remove this check at all, or add an assignment of the "isConnected" filed in the "IsConnected" property.

In other case you have no valid value in the "isConnected" filed during this check. And therefore you don't send the TRUE or FALSE OnConnectivityChanged event depending on the initial "isConnected" filed value;


2) There are several additional strange network interfaces with NetworkInterfaceSubType = Unknown and InterfaceName like "{22C7611B-530E-11DB-BA31-806E6F6E6963}_13359" when you use the
var interfaceName = networkInterfaceInfo.InterfaceName;
expression to get the ConnectionTypes.

You can use the 
var networkInterfaceList = NetworkInformation.GetConnectionProfiles();
expression instead, the same as for WinRT projects. It works better.

**Comment by avorobjovs** [comment]
Hi James,

Have you did any new updates?

Best Regards,
Aleksandrs

**Comment by jamesmontemagno** [comment]
It's the holidays here in the states so I won't be around a computer until
Monday. Best, James

**Comment by avorobjovs** [comment]
Oh, I'm sorry.
Wish you a nice weekend!

**Comment by jamesmontemagno** [comment]
Alright, so had to take a longer look at this. I have updated both WinRT & WP8.0SL to save out the isConnected and compare before pushing up a change event properly.

For your other change to use: var networkInterfaceList = NetworkInformation.GetConnectionProfiles();

This API actually wasn't available in WP 8.0SL, which is why I used the other method. However, it was available in WP 8.1SL. I have no added a new DLL to target WP 8.1SL, which uses the same implementation as WP/Store 8.1 RT and UWP, which is nice. Checkout alpha3, available now.

**Comment by avorobjovs** [comment]
Thank you!
I'll check it tomorrow. Because I have a night already. :)

**Comment by avorobjovs** [comment]
Unfortunatelly, I have no any devices with WP 8.0. All my test devices already have 8.1. But my Silverlight project is 8.0.

And anyway the expression
var networkInterfaceList = NetworkInformation.GetConnectionProfiles();
works successfully. 

As well as 
NetworkInformation.GetInternetConnectionProfile()
instead of
DeviceNetworkInformation.IsNetworkAvailable

Maybe it depends on device Windows version. Can it be that?

**Comment by jamesmontemagno** [comment]
It depends on what version of Windows Phone silverlight your actual application is targeting. 

If you read the documentation it is very clear it is 8.1 only: https://msdn.microsoft.com/en-us/library/windows.networking.connectivity.networkinformation.getconnectionprofiles.aspx


NetworkInformation.GetInternetConnectionProfile() is in Windows Phone 8.0 and I upgraded the project to use this in alpha 3:
https://github.com/jamesmontemagno/Xamarin.Plugins/blob/namespace-changes/Connectivity/Connectivity/Connectivity.Plugin.WindowsPhone8/ConnectivityImplementation.cs#L62-L63


If your app is targeting WP Silverlight 8.1 then you will get the new DLL that uses GetConnectionProfiles()

**Comment by avorobjovs** [comment]
Thank you, James! Now it works fine.
And as I can see you already updated the master branch to the version 2.0. It's good!

**Comment by jamesmontemagno** [comment]
Glad we got it all figured out :)
