### ISSUE TITLE
Connectivity Plugin doesn't work on Windows 8.1 StoreApp

### ISSUE THREAD

**Issue by avorobjovs** [jamesmontemagno/Xamarin.Plugins#143]
Hi,

We have an Xamarin.Forms application and use Connectivity Plugin. And one of our target platform is Windows. We use Windows 8.1 StoreApp.

- The Connectivity.Plugin.CrossConnectivity.Current.ConnectivityChanged event is triggered when I enable and disable different internet connections.
- The Connectivity.Plugin.CrossConnectivity.Current.ConnectionTypes list also contains real enabled connections.
- But the Connectivity.Plugin.CrossConnectivity.Current.IsConnected is not changed and equal TRUE all time.

We use Xamarin.Forms 1.5.0.6447 and Connectivity.Plugin 1.0.4
The app is running on Windows 10 64-bit Version 1511 (OS Build 10586.3)

Best Regards,
Aleksandrs

**Comment by jamesmontemagno** [comment]
Interesting perhaps they changed something in Windows 10 as this used to work.

Currently I do:

NetworkInterface.GetIsNetworkAvailable();

Going to change to:
ConnectionProfile connections = NetworkInformation.GetInternetConnectionProfile();
    bool internet = connections != null && connections.GetNetworkConnectivityLevel() == NetworkConnectivityLevel.InternetAccess;
    return internet;

**Comment by avorobjovs** [comment]
I have found a reason for this issue.
The virtual "vEthernet (Internal Ethernet Port Windows Phone Emulator Internal Switch)" network adapter starts when all other real connections are disabled.

And regardless of the fact that the Connectivity.Plugin.CrossConnectivity.Current.IsConnected is not changed and equal TRUE, the count of ConnectionProfile in NetworkInformation.GetConnectionProfiles() is 0.

**Comment by jamesmontemagno** [comment]
Fixed and tested in 2.0.0-alpha2 please grab this pre-release. Note that there is a new namespace: Plugin.Connectivity.

Thanks,
James

**Comment by avorobjovs** [comment]
Thank you. I have tested the 2.0.0-alpha2 version. It works succesfully.
