### ISSUE TITLE
CircleImage backgrounds render differently on iOS and Android

### ISSUE THREAD

**Issue by dvdsgl** [jamesmontemagno/Xamarin.Plugins#145]
Setting the BackgroundColor of a CircleImage, but not setting its image, renders differently, and I'd argue incorrectly, on Android compared to iOS.

On iOS I get a colored circle, on Android I get a colored square. My user interface relies on the CircleImage drawing as a circle even if the image is not yet set.

**Comment by jamesmontemagno** [comment]
Fixed in 1.3.0, now available. You must use "FillColor" for the fill of the circle. "BackgroundColor" should never be set as that would be the entire square that the circle is cut out of.
