### ISSUE TITLE
Geolocator plugin KeyNotFoundException 

### ISSUE THREAD

**Issue by JonathanYates** [jamesmontemagno/Xamarin.Plugins#151]
After updating to v2.0 of Geolocator plugin I get the following Fault exception reported from the task returned from GetPositionAsync. (I do a ContinueWith to check for any faults).

{System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary. …} System.Collections.Generic.KeyNotFoundException

Reverted to 1.1.1 which works fine.

**Comment by jamesmontemagno** [comment]
Haven't seen this at all in anything... any reason to not use await on it?
