### ISSUE TITLE
Xam.Plugins.Settings Remove method not working properly on WP 8.0 Silverlight

### ISSUE THREAD

**Issue by pawlowskim** [jamesmontemagno/Xamarin.Plugins#152]
Hello,

I'm using Settings plugin (v. 1.5.2.0) in my XF apps. It works great on iOS unified and Android, but doesn't work on WP 8.0. It removes key temporary, while app is running I can debug and it shows that value from given key is removed. After relaunching the app the value from given key is still there.

I'm using AppSettings.Remove(mykey) to clear key data.

**Comment by jamesmontemagno** [comment]
I am simply calling the remove method:

https://github.com/jamesmontemagno/Xamarin.Plugins/blob/master/Settings/Refractored.Xam.Settings.WindowsPhone/Settings.cs#L105-L108

As documented here:
https://msdn.microsoft.com/en-us/library/windows/apps/system.io.isolatedstorage.isolatedstoragesettings.remove(v=vs.105).aspx

So it is removed according to documentation. If anywhere in your code you are calling and resetting or getting it, it may look like it exists.

**Comment by pawlowskim** [comment]
I have read the documentation and it looks good in your implementation.

**Comment by jamesmontemagno** [comment]
Yeah, the only thing I can think of is that you need to call .Save(), but NONE of their samples have it. I will try to test it out when I have some spare time just to be sure.
