### ISSUE TITLE
Misleading Readme for PLugin Media

### ISSUE THREAD

**Issue by Blackbilbao** [jamesmontemagno/Xamarin.Plugins#153]
Hi guys, 

I tried yesterday to use the media plugin for the first time and i saw a small error in the readme for media..

with 2.0.0 and 2.0.1 you have to use
Plugin.Media.Abstractions.StoreCameraMediaOptions 

in the old version (1.0.1) you have to use 

Media.Plugin.Abstractions.StoreCameraMediaOptions

i'm new to coding in c# and xamarin so for me this was a bit of a problem till i saw what is the problem...

Maybe you could fix that in the readme for follow newcommers to the plugin.

**Comment by jamesmontemagno** [comment]
Fixed
