### ISSUE TITLE
Media plugin to retrive MediaFiles from Storage (feature request)

### ISSUE THREAD

**Issue by Blackbilbao** [jamesmontemagno/Xamarin.Plugins#154]
When using Plugin Media you can save them via CrossMedia instance. i ran into the problem that system specfic folders are created when saving Pictures and Videos 

on Android for example if you specify the Directory "Sample" it is internally saved to [yourAppID]/Pictures/Sample
(although "Pictures" was not available before)
on Ios it is in the 
[AppleAppID]/Documents/Sample

it would be nice if the service could retrive the mediafiles correctly for crossplatform applications, because in the current setup i can't really modify where the Media is saved (without renaming and relocating the files my self)
Therefore i would have to write diffrent implementations for each device which we all know can be a pain in the...
I think many people would benefit from this feature.

**Comment by jamesmontemagno** [comment]
You can use the PCL Storage Plugin: https://github.com/dsplaisted/PCLStorage

You just have to specify where you want to get the files from.
