### ISSUE TITLE
[Feature Request] Abstract Image Metadata & Return in MediaFile

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/Xamarin.Plugins#155]
Originally from #76, what is requested is a way to abstract the metadata form the files into a common class that is returned with the file location in the Media File.

Things such as:
* Size
* Dimensions
* Date
* Exposure
* Camera Make
* Camera Model
* Etc..

For discussion on missing metadata please see #156

**Comment by lodev09** [comment]
This has been implemented in Xlabs media that stores metadata to a common class ([see my comment](https://github.com/jamesmontemagno/Xamarin.Plugins/issues/82#issuecomment-162055685)). It needs some tweak though since in iOS, when the source is from camera, GPS info is not included (not sure about this) so you have to create your own and include it in the `JpegInfo` property.

It would be awesome if you can implement it to this plugin :)

**Comment by Jazzeroki** [comment]
personally I would think reading exif data should be in it's own seperate plugin.  There is a plugin out there that supports reading exif data, and can get things like dimensions, exposure, camera and the like.  My problem with it was it would never return gps data.  There's also inconsistencies about being able to get such data.  iOS is really good about having GPS unless it's cast as a UImage.  Android in my experience doesn't like to add gps.  Have tried winphone yet.  I'd like to make this into a plugin but here's some ways I read exif data for GPS in iOS and Android.

public class GeoCoordinatesAndroid : IGeoCoordinates
	{
		public string GetLatitude(string filepath)
		{
			var exif = new ExifInterface(filepath);
			string lat = ExifInterface.TagGpsLatitude;
			string lat_data = exif.GetAttribute(lat);
			return FormatAsCoordinate(lat_data);
		}

		public string GetLongitude(string filepath)
		{
			var exif = new ExifInterface(filepath);
			string lon = ExifInterface.TagGpsLongitude;
			string lon_data = exif.GetAttribute(lon);
			return FormatAsCoordinate(lon_data);
		}
		public string FormatAsCoordinate(string unformattedCoordinate)
		{
			if (string.IsNullOrEmpty(unformattedCoordinate))
				return "";
			else
			{
				char divider = '/';
				char divider2 = ',';
				var strings = unformattedCoordinate.Split(divider);
				var strings1 = strings[1].Split(divider2);
				var strings2 = strings[2].Split(divider2);
				var numSeconds = (Convert.ToDouble(strings1[1]) * 60 + Convert.ToDouble(strings2[1]));
				double seconds = 0;
				try
				{
					seconds = numSeconds / 3600;
					seconds = Math.Round(seconds, 6, MidpointRounding.AwayFromZero);
				}
				catch
				{
					seconds = 0;
				}
				var coordinate = (Convert.ToDouble(strings[0])) + seconds;
				return (coordinate -1).ToString();
            }

		}

for iOS

public GeoCoordinatesiOS()
		{
		}

		public string GetLatitude(string filepath)
		{
			var fetchResult = PHAsset.FetchAssets(new [] { NSUrl.FromString(filepath) }, null);
			if (fetchResult.Count == 1)
			{
				var result = (PHAsset)fetchResult[0];
				if (result.Location != null)
					return result.Location.Coordinate.Latitude.ToString();
			}
			return "0";
		}

		public string GetLongitude(string filepath)
		{
			var fetchResult = PHAsset.FetchAssets(new [] { NSUrl.FromString(filepath) }, null);
			if (fetchResult.Count == 1)
			{
				var result = (PHAsset)fetchResult[0];
				if (result.Location != null)
					return result.Location.Coordinate.Longitude.ToString();
			}
			return "0";
		}

**Comment by Axel3232** [comment]
See my PR : https://github.com/XLabs/Xamarin-Forms-Labs/pull/953

Get all Exif Tags on iOS and Android

**Comment by jamesmontemagno** [comment]
Based on some of this feedback, i wonder if it would be better if this was it's own plugin to be honest, why put it in this plugin and add more complexity to it? There should be a simple Exif plugin to handle this.

Then technically this plugin could rely on that plugin to return the meta data back if needed.

**Comment by Axel3232** [comment]
Yes it could, but the plugin has it is was when I did the PR did not fullfill the need since it did not retreive all the ExifTags, and introduce coupling : 

>The main problem regarding coupling is that the MediaInfo class has a JpegInfo prop wich is defined  >inside ExifLib and wrap some metadata but not all...so we are stuck with this external implementation...
>For me, that is bad coupling.
>
>That's why I decided to include the ExifLib implementation in the XLab code this way ExifBinary reader >only expose a generic method to get any Exif tags using an Enum Key.
>
>And it is the responsability to the platform project to wrap metadata in more "friendly shortcut object" >that implement the IJpegInfo interface

**Comment by Jazzeroki** [comment]
I've been thinking about writing an exif plugin especially since I'm already using the code above in a project.  James thanks for the AlbumPath extension when taking photo's.  Can you extend that to also work when picking photos?

**Comment by brandon21486** [comment]
> Based on some of this feedback, i wonder if it would be better if this was it's own plugin to be honest, why put it in this plugin and add more complexity to it? There should be a simple Exif plugin to handle this.

> Then technically this plugin could rely on that plugin to return the meta data back if needed.

Wouldn't you have to change the way you are handling the image anyway when choosing a gallery image? The way it is now the metadata gets stripped off when you copy it over to the App library. I used your code as a base and was able to grab the whole image with the metadata using the ALAssetLibrary and copying it to the path instead of the UIImage.

`                var imageURL = info[UIImagePickerController.ReferenceUrl];
                asset = SynchronousGetAsset(imageURL.ToString());

                long size = asset.DefaultRepresentation.Size;
                byte[] imgData = new byte[size];
                NSError nsError;

                IntPtr buffer = Marshal.AllocHGlobal(imgData.Length);
                asset.DefaultRepresentation.GetBytes(buffer, 0, (uint)size, out nsError);
                Marshal.Copy(buffer, imgData, 0, imgData.Length);
                NSData nsData = NSData.FromArray(imgData);
                using (FileStream fs = File.OpenWrite(path))
                using (Stream s = new NSDataStream(nsData))
                {
                    s.CopyTo(fs);
                    fs.Flush();
                }`
 I am still trying to figure out how to grab the location and add it to an image from the camera because for some reason it doesn't add it to the photo even when saving to the Gallery.

**Comment by AlmaJensen** [comment]
I've started an exiff reader plugin.  I could use some help getting the other platforms added and some testing.  [https://github.com/AlmaJensen/XamPlugin-Exiff-Reader](url)

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/MediaPlugin#29
