### ISSUE TITLE
[Bug] iOS Looses MetaData when Store in App Directory

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/Xamarin.Plugins#156]
Since it is cast to UIImage the image looses all exif meta data.

Android & Windows seem fine.

This if originally from #82

For Discussion on Abstracting the Metadata see: #155

**Comment by Jazzeroki** [comment]
An easier work around would be just to let Album Path always have the path back to the original file.  This is an iOS only issue as far as I can tell.  I really needed the exif data in iOS so after modifiying your source code that's the route I used to get past this issue.

**Comment by Jazzeroki** [comment]
If you want to take a different route though this code did a great job of grabbing exiff data for me.

public ImagePropertiesModel GetData(string filepath)
		{
			var imageData = new ImagePropertiesModel();

			var fetchResult = PHAsset.FetchAssets(new[] { NSUrl.FromString(filepath) }, null);
			if (fetchResult.Count == 1) //exception being thrown here
			{
				var result = (PHAsset)fetchResult[0];
				if (result.Location != null)
				{
					imageData.Latitude = result.Location.Coordinate.Latitude;
					imageData.Longitude = result.Location.Coordinate.Longitude;
					
				}
				imageData.Height = (int)result.PixelHeight;
				imageData.Width = (int)result.PixelWidth;
				
			}
			return imageData;
		}

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/MediaPlugin#28
