### ISSUE TITLE
SaveToAlbum Option

### ISSUE THREAD

**Issue by Blackbilbao** [jamesmontemagno/Xamarin.Plugins#157]
on the readme there is a point about enabling SaveToAlbum feature

but when i try 
new Plugin.Media.Abstractions.StoreCameraMediaOptions {
				SaveToAlbum = true,
				Directory = "Sample",
				Name = "Foto_" + (long)(DateTime.Now.Subtract (new DateTime ()).TotalSeconds)
			};

it says does not contain a definition for SaveToAlbum
also i'm wondering why the version 2.1.0 is mentioned but the latest version is 2.0.1

**Comment by cbartonnh** [comment]
2.1 is a pre-release version: https://www.nuget.org/packages/Xam.Plugin.Media/2.1.0-beta1 <https://www.nuget.org/packages/Xam.Plugin.Media/>

**Comment by jamesmontemagno** [comment]
Updated the readme to really spell it out.
