### ISSUE TITLE
ios 9 do I still need to call RequestWhenInUseAuthorization ?

### ISSUE THREAD

**Issue by egarim** [jamesmontemagno/Xamarin.Plugins#158]
Does this work on ios 9, do I still need to do RequestWhenInUseAuthorization or RequestAlwaysAuthorization?

**Comment by jamesmontemagno** [comment]
It does it for you automatically when you attempt to call the method. You still need to place the correct settings in your info.plist though. If you want more control you can install the Permissions plugin: https://github.com/jamesmontemagno/Xamarin.Plugins/tree/master/Permissions and request manually.
