### ISSUE TITLE
[Feature Request] (Media/Android) Add ability to push MediaIntent so that returning doesn't force application resume with Xamarin.Forms

### ISSUE THREAD

**Issue by pdblasi** [jamesmontemagno/Xamarin.Plugins#161]
Currently on Android, media is taken using an intent. The intent is always launched with the "NewTask" flag, which means that when the user is done getting/taking media, a Xamarin.Forms application will go through the OnResume method. Is it possible to keep the intent in the current application's Task to prevent the OnResume method from being called?

It would be convenient to be able to configure this, at app start or on a per call basis, so either behavior could be used.

(The reason I wish to avoid the OnResume method is because of a pin page being presented during OnResume. The pin page is required for security so I can't remove it. My plan for now is to add an extra flag to avoid the pin page if the developer says to skip it this time, but it's a hack.)

**Comment by jamesmontemagno** [comment]
OnResume will always get called after your current Activity launched the intent (doesn't matter if it is NewTask) or not: http://developer.android.com/reference/android/app/Activity.html#onPause() on Pause would get called and then OnResume would be called again.
