### ISSUE TITLE
Android Camera filename

### ISSUE THREAD

**Issue by ddeysel** [jamesmontemagno/Xamarin.Plugins#162]
Hi

I noticed that if I open the camera like so:

var options = new StoreCameraMediaOptions
                        {
                            Directory = "SomeDir",
                            Name = "test.jpg"
                        };
var mediaFile = await CrossMedia.Current.TakePhotoAsync(options);

and then cancel (by pressing Back button) or discard the photo taken, it still keeps a reference to that filename, because the next time the photo will be called something like "test_1.jpg" or "test_2.jpg".

Is there any easy way to reset the filename if photo was discarded?

Thanks

**Comment by jamesmontemagno** [comment]
The android system must be creating the file as I search for files in that directly as you can see here: https://github.com/jamesmontemagno/Xamarin.Plugins/blob/master/Media/Media/Media.Plugin.Android/MediaPickerActivity.cs#L377-L391 so it must not actually be discarded.
