### ISSUE TITLE
Xamarin Forms,  CrossCurrentActivity and Android

### ISSUE THREAD

**Issue by PureWeen** [jamesmontemagno/Xamarin.Plugins#165]
The MainApplication file created for Android breaks the Xam Forms Android project with "too many classes have [Application] attributes" ... 

Because Android Xam Forms all just works off of a single MainActivity and I'm assuming internally it has an Application class it doesn't want you inheriting from or messing with

Is it enough to just add something like this

```
CrossCurrentActivity.Current.Activity = this;
```

In the OnCreate method of the MainActivity used with Xam Forms? And call it good?

Or should MainActivity implement
```
Application.IActivityLifecycleCallbacks
```

and then replicate the stuff in the generated MainApplication.cs file?

**Comment by jamesmontemagno** [comment]
If you already have a class with an [Application] attribute just add the code to it so it looks like this: 
https://github.com/jamesmontemagno/Xamarin.Plugins/blob/master/TestProject/TestAppForms/TestAppForms/TestAppForms.Android/MainApplication.cs

It works perfect with Xamarin.Forms because that is where all of my test cases are att.

You can add CrossCurrentActivity.Current.Activity = this; however, it is recommended to add the MainActivity.

**Comment by PureWeen** [comment]
hmm alright upgrading the nuget package must generate something in the project that causes issues...
I did this on the test project
-downloaded latest bits of test project from github
-TestAppForms.Android compiles
-went to nuget and updated to all the latest Xam.Plugins in Nuget
-recompiled TestAppForms.Android Project and I get this error

```
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1604,3): error MSB4018: The "GenerateJavaStubs" task failed unexpectedly.
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1604,3): error MSB4018: System.InvalidOperationException: There can be only one type with an [Application] attribute; found: , 
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1604,3): error MSB4018:    at Xamarin.Android.Tasks.ManifestDocument.CreateApplicationElement(XElement manifest, List`1 subclasses, List`1 selectedWhitelistAssemblies)
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1604,3): error MSB4018:    at Xamarin.Android.Tasks.ManifestDocument.Merge(List`1 subclasses, List`1 selectedWhitelistAssemblies, Boolean embed, Boolean replaceSplashScreen, IDictionary`2 splashScreenClasses, String bundledWearApplicationName, IEnumerable`1 mergedManifestDocuments)
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1604,3): error MSB4018:    at Xamarin.Android.Tasks.GenerateJavaStubs.Run()
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1604,3): error MSB4018:    at Xamarin.Android.Tasks.GenerateJavaStubs.Execute()
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1604,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1604,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========
```

Looking over it to see what it's creating when updating those nugets that causes this

**Comment by PureWeen** [comment]
Looking at the newest version of PLugin.Permissions it looks like it includes MainApplication in the binary which is causing this exception

from this commit
https://github.com/jamesmontemagno/Xamarin.Plugins/commit/af9071eb2faa20369567875b3f6a0071fa4b3283

**Comment by jamesmontemagno** [comment]
Good catch, fixing. Thanks!

**Comment by jamesmontemagno** [comment]
I have de-listed these for a short while to fix.

**Comment by jamesmontemagno** [comment]
just pushed out 1.1.3 and will upgrade media/geolocation to this version next.

**Comment by PureWeen** [comment]
Awesome!!!! Thank you for pushing this through the pipeline so fast... Changes all worked great

**Comment by kentcb** [comment]
For future readers, another scenario in which this error can come up is if you've installed the plugin into an Android library project. That will have added the application class there too, so now you'll have the application class in your main UI project _and_ the application class in your library project. Obviously, delete the latter.

**Comment by jiletx** [comment]
Hey i just downloaded nuget package. When i added package to droid packages, i get the following error:
The " GenerateJavaStubs" task failed unexpectedly. 
What i am doing wrong here? Any guesses?

**Comment by faceoffers28** [comment]
I'm getting the same error as jiletx is reporting. I just installed Xam.Plugin.Media 2.3.0 into my Xamarin.Forms 2.2.0.31 project. Here is the full error.

Severity	Code	Description	Project	File	Line	Suppression State
Error		The "GenerateJavaStubs" task failed unexpectedly.
System.InvalidOperationException: Application cannot have both a type with an [Application] attribute and an [assembly:Application] attribute.
   at Xamarin.Android.Tasks.ManifestDocument.CreateApplicationElement(XElement manifest, List`1 subclasses, List`1 selectedWhitelistAssemblies)
   at Xamarin.Android.Tasks.ManifestDocument.Merge(List`1 subclasses, List`1 selectedWhitelistAssemblies, Boolean embed, String bundledWearApplicationName, IEnumerable`1 mergedManifestDocuments)
   at Xamarin.Android.Tasks.GenerateJavaStubs.Run()
   at Xamarin.Android.Tasks.GenerateJavaStubs.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	FaceOffers.Droid			

I'm trying to switch from the XLabs Camera over to this implementation. Thanks!

**Comment by jiletx** [comment]
This plugin adds mainactivity.cs on its own. So when you have 2 application classes in same project and in your manifest it causes this error.simply merge your's with the one that comes with this plugin and it will work

**Comment by jamesmontemagno** [comment]
^ That is correct. Please see: https://github.com/jamesmontemagno/CurrentActivityPlugin

**Comment by faceoffers28** [comment]
@jiletx and @jamesmontemagno I only see one MainActivity.cs file in my Android app, so there is nothing to merge. I'm not sure I understand your explanation as to what the problem is and I certainly don't know how to fix it. :) What lines of code or what specific file to I have to merge with my current MainActivity.cs file? Here is my file.

```
[Activity(Label = "FaceOffers Mobile", Icon = "@drawable/icon", ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]

    //public class MainActivity : FormsAppCompatActivity
	public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsApplicationActivity
	{
		protected override void OnCreate(Bundle bundle)
		{
			//FormsAppCompatActivity.ToolbarResource = Resource.Layout.toolbar;
			//FormsAppCompatActivity.TabLayoutResource = Resource.Layout.tabs;

			//Barcode scanner
			//global::ZXing.Net.Mobile.Forms.Android.Platform.Init ();

			#region Resolver Init
			SimpleContainer container = new SimpleContainer();
			container.Register<IDevice>(t => AndroidDevice.CurrentDevice);
			container.Register<IDisplay>(t => t.Resolve<IDevice>().Display);
			container.Register<INetwork>(t => t.Resolve<IDevice>().Network);
			
			Resolver.SetResolver(container.GetResolver());
			#endregion
			

			//Xamarin Insights init for Android
			Insights.Initialize("SOMEIDNUMBE", ApplicationContext);

			//Added for Secure Storage
			SecureStorageImplementation.StoragePassword = SOMEPASSWORD;

            // Xamarin Forms Toast init for Android
            DependencyService.Register<ToastNotificatorImplementation>();
            ToastNotificatorImplementation.Init(this);

			//Added for FFImageLoading
			CachedImageRenderer.Init ();

			//Added for HockeyApp
			// ... your own OnCreate implementation
			CrashManager.Register(this, "SOMEIDNUMBER");

			base.OnCreate(bundle);
			Forms.Init(this, bundle);
			LoadApplication(new App());
		}
``` 
Thanks in advance!

**Comment by jamesmontemagno** [comment]
Sorry, it is that it adds a new MainApplication class, not Main Activity, you would need to merge teh application classes together.

**Comment by faceoffers28** [comment]
I'm still not sure what to do. I have one MainApplication.cs file in my Android app. The file looks like both of these. https://github.com/jamesmontemagno/CurrentActivityPlugin/blob/master/tests/CurrentActivityTest.Droid/MainApplication.cs | https://github.com/jamesmontemagno/MediaPlugin/blob/master/src/Media.Plugin.Android/MainApplication.cs
What exactly do I need to merge? Perhaps my GenerateJavaStubs issue is a different problem.

**Comment by PureWeen** [comment]
It might be in a different file not necessarily with that name.. Or maybe you have a different class acting as the application root?

```
[Application]

    public class MainApplication  : Application
```

Do a solution search "CTRL SHIFT F"  for MainApplication

Or look for another class with the [application] attribute or implementing application...  It might not be in a file specifically called MainApplication.cs

**Comment by faceoffers28** [comment]
@PureWeen This really helped me understand what was happening. I the did a broader search and found a blog post indicating a possible issue in my AssemblyInfo.cs. It appears that this line of code was the culprit. If I completely comment it out, the app compiles. 

```
//Added to Release to Google Play Store
#if DEBUG
[assembly: Application(Debuggable=true)]
#else
[assembly: Application(Debuggable=false)]
#endif


```Is there a way to write this, so the app will compile whether I'm debugging or releasing it? My apologies to everyone for thinking this was a Media Plugin issue. Since that was the only thing I added, I started there and happened to find this issue.

**Comment by PureWeen** [comment]
the Xamarin project can only have one Application Attribute 

I'm guessing just keep the one that works for your application

My projects all just use the type that has the application attribute on the class and not in the AssemblyInfo.cs file

the MainApplication.cs  added by the plugin is really more of a guideline or demonstration of what makes the CurrentActivity plugin work

The plugin isn't able to just behind the scenes work without having to do anything... It has to be set as part of the Android Life cycle ... i.e.
```
 public void OnActivityResumed(Activity activity)

        {

            CrossCurrentActivity.Current.Activity = activity;

        }
```

And then a lot of the other plugins that depend on CrossCurrentActivity just assume that this has been setup correctly and then use it to do what they need to do... Android for a lot of its operation need the current activity in order to do stuff. So this plugin allows a common way for all the plugins built on top of it to function.  Somewhere in your Xamarin Forms Android project you have the hooks that are expressed in the MainApplication.cs file that you can setup in the same fashion.

so take the ideas expressed in the MainApplication.cs file and relate them to your project
Hopefully that makes sense

**Comment by jamesmontemagno** [comment]
@faceoffers28  simply find this that was added and adjust where necessary:

https://github.com/jamesmontemagno/CurrentActivityPlugin/blob/master/files/MainApplication.cs.pp#L11

**Comment by 15mgm15** [comment]
Great discussion.

**Comment by ceblanda** [comment]
@faceoffers28 You may have already solved it, but I had the same issue so I solved it my merging the two ...
MainApplication.cs:

namespace TestAppForms.Droid
{
    #if DEBUG
    [Application(Debuggable = true)]
    #else
    [Application(Debuggable=false)]
    #endif
    public class MainApplication : Application, Application.IActivityLifecycleCallbacks
    {

**Comment by user-mw** [comment]
If I have Application class that is not named like MainApplication will this package download its own MainApplication again if I reinistall package?

**Comment by user-mw** [comment]
If I have Application class that is not named like MainApplication will this package download its own MainApplication again if I reinistall package?

**Comment by jamesmontemagno** [comment]
just comment out the MainApplication.cs content and leave the file

**Comment by sunnysonic** [comment]
Anybody ever had this got going? I'm having a MainActivity.cs already and changed the class to:
 public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity, Android.App.Application.IActivityLifecycleCallbacks

Still don't have it working.

Also i can't use             RegisterActivityLifecycleCallbacks(this);
 It tells me it doesn't exist in current content

Anybody got this working with Xamarin Forms???
