### ISSUE TITLE
Plugin Media fails in WindowsPhone RT

### ISSUE THREAD

**Issue by nordicca** [jamesmontemagno/Xamarin.Plugins#167]
The recommended code

Plugin.Media.MediaImplementation.OnFilesPicked(args);

fails on launch application in WindowsPhone RT

Any solution ?

**Comment by jamesmontemagno** [comment]
This isn't very descriptive at all as to what "fails" mean and if you are getting a crash and if there is a stack trace at all. I have a WinPhone RT sample here: https://github.com/jamesmontemagno/Xamarin.Plugins/tree/master/Media/MediaTest

**Comment by nordicca** [comment]
Ok. Solved.

The complete code in App.cs in WindowsPhone RT project is:

 protected override void OnActivated(IActivatedEventArgs args)
        {
#if WINDOWS_PHONE_APP
            Plugin.Media.MediaImplementation.OnFilesPicked(args);
#endif
            base.OnActivated(args);
        }

Thanks James ;)

**Comment by tomcrusader** [comment]
Thanks for this clarification, @nordicca . The documentation was rather unclear about Win 8.1 VS Win Phone 8.1
