### ISSUE TITLE
[Bug] Location Permission requested on iOS with PermissionPlugin twice

### ISSUE THREAD

**Issue by anthonybattel** [jamesmontemagno/Xamarin.Plugins#169]
The first time I request a location permission on iOS(9.2) , it works good. I have a popup "allow" or "not allow". 
If I choose "not allow" and request it again, there is no popup asking me again and the app seems to be freezed. 
In debug mode, it appears that the execution is blocked at the line :
var results = await CrossPermissions.Current.RequestPermissionsAsync(Permission.Location);

Tested on PermissionTest.iOS sample

Thanks

**Comment by cbartonnh** [comment]
@anthonybattel You shouldn't get another request for permission if the user clicked Not Allow. I am not sure on the "freeze" you are reporting but here is how the permissions in general work for iOS.

Basically, Apple will not nag the user to allow it once they explicitly say no. The only option is for the user to go to iOS Settings app and change the setting to allow it. You can help the user get there by deep linking to your app-specific setting.

Here is how I have done it in the past for Contacts but the idea is the same:

`// Make sure we have permission to access contacts

            if (await CrossContacts.Current.RequestPermission())
            {
                // I have permission so do what I have to do
            }
            else
            {
                // I don't have permission. Present some UI to the user (you could use a message box)

                NoDataLabel.Text = "To help you keep in touch, YouCalled requires access to your contacts. You can grant permission in Settings.";
                NoDataButton.Text = "Go To Settings";

                NoDataStack.IsVisible = true;

                
            }
`
When they press the "Go To Settings" button, I did this:

`
UIApplication.SharedApplication.OpenUrl(new NSUrl("app-settings:"));
`

The Url takes them to the settings for your app and they can change the switch to allow permission.

I did this a while ago so there could be other ways to do it. Also, it is possible that this might only work back to iOS 8 but hopefully it gives you some ideas.

Hope this helps.

Carl

**Comment by jamesmontemagno** [comment]
So the simple work around is to check if the status is Denied and if it is Denied then don't re-request it. I am going to update the code. iOS does not re-prompt. I am fixing the freeze now, but Carl's recommendation above is pretty great. Also you could use the the Share Plugin to navigate to app-settings:

**Comment by jamesmontemagno** [comment]
Note, that this would also most likely happen for Contacts and Photos. This is due to iOS not giving a callback if request a known status.

**Comment by anthonybattel** [comment]
Thanks cbartonnh and James, you are very efficient.
I will test your recommandations.

**Comment by jamesmontemagno** [comment]
Also pushed 1.1.4 with a fix if you re-request too many times.
