### ISSUE TITLE
ImageCircle not working as expected on Android

### ISSUE THREAD

**Issue by kentarneb** [jamesmontemagno/Xamarin.Plugins#17]
Hello!

https://github.com/jamesmontemagno/Xamarin.Plugins/tree/master/ImageCircle, version 1.0.0.5

It works perfectly on iOS, but on Android the pixels outside the drawn circle isnt transparent. Images of how it looks on iOS and Android (S4, Android 4.4.2). Xamarin Forms version 1.3.1.6296:

![circleimage](https://cloud.githubusercontent.com/assets/2409479/5799658/3451e084-9fd5-11e4-8596-a534b83ef88c.jpg)

**Comment by jamesmontemagno** [comment]
I have tested this on my Moto G and haven't had issues. Are you able to test this an emulator or anything besides an S4? Might be a bug on that phone.

**Comment by kentarneb** [comment]
You're right. I tested it on a S2(4.1.3) and a Samsung Galaxy tab pro 10.1 (4.4.2) and there it worked. I dont got another S4 to test it, but do you think in that case its just the phone, or all S4's?

**Comment by jamesmontemagno** [comment]
It very well could be. The S4 has TONS of issues across the board in their firmware. I will see if anyone else is having this issue. I am curious if I change this if it will work. My assumption is that they did not implement hardware acceleration on something in their firmware.

 if ((int)Android.OS.Build.VERSION.SdkInt < 18)
          SetLayerType(LayerType.Software, null);

**Comment by jamesmontemagno** [comment]
So confirmed that this is the issue:

https://code.google.com/p/android/issues/detail?id=75011

I will put a work around in place, but I do not have a device to test this on unfortunately.

**Comment by kentarneb** [comment]
Ok, nice that you've the issue. Just give me a notice when the work around is implemented and ill update the nuget package and test it :)

**Comment by jamesmontemagno** [comment]
This might be the safest way to always do software :(

**Comment by jamesmontemagno** [comment]
I have pushed out 1.0.6 with this fix in it now. I do enable it for Lollipop devices though for now.
