### ISSUE TITLE
Leaked window exception

### ISSUE THREAD

**Issue by sergibarnyard** [jamesmontemagno/Xamarin.Plugins#171]
Hey, i have an issue:
when i call var file = await Plugin.Media.CrossMedia.Current.PickPhotoAsync();
from my forms pcl, i receive a file, but exception follows :

[WindowManager] android.view.WindowLeaked: Activity md5426df52c3692a7a242e80cbb3363c75d.MediaPickerActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{3c56975 V.E..... R.....ID 0,0-287,346} that was originally added here
[WindowManager] 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:363)
[WindowManager] 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:271)
[WindowManager] 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
[WindowManager] 	at android.app.Dialog.show(Dialog.java:298)
[WindowManager] 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.FormsApplicationActivity.n_onRestart(Native Method)
[WindowManager] 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.FormsApplicationActivity.onRestart(FormsApplicationActivity.java:79)
[WindowManager] 	at android.app.Instrumentation.callActivityOnRestart(Instrumentation.java:1246)
[WindowManager] 	at android.app.Activity.performRestart(Activity.java:6057)
[WindowManager] 	at android.app.Activity.performResume(Activity.java:6068)
[WindowManager] 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2975)
[WindowManager] 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3017)
[WindowManager] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
[WindowManager] 	at android.os.Handler.dispatchMessage(Handler.java:102)
[WindowManager] 	at android.os.Looper.loop(Looper.java:135)
[WindowManager] 	at android.app.ActivityThread.main(ActivityThread.java:5254)
[WindowManager] 	at java.lang.reflect.Method.invoke(Native Method)
[WindowManager] 	at java.lang.reflect.Method.invoke(Method.java:372)
[WindowManager] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
[WindowManager] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

Same code executed in activity, don't throw any exceptions. 
When i call it via dependency service, the exception is back.
Any hints on whats up? or how to fix it?
Thanks!

**Comment by jamesmontemagno** [comment]
I have not personally seen this at all, are you running on UI thread?

**Comment by xleon** [comment]
This is possibly caused by the custom Android Application class.
With that class, all rotations in applications will make the app crash.
I implemented the class so it doesn´t crash. Let me know if you need a sample

**Comment by jamesmontemagno** [comment]
Samples are always good, however I use this class and haven't had issues at all. If you can share that would be great as to what you have changed.

**Comment by xleon** [comment]
Well, I know this because my app was totally crashing because of this on every rotation until I changed that. The logcat logs are not very clear about what was failing (at least I didn´t understand it).
Basically you need to create a handler for IActivityLifecycleCallbacks instead of implementing that on the Application class

https://gist.github.com/xleon/46880f6189acc02df663

**Comment by jamesmontemagno** [comment]
Hmmmm, That is interesting and I will test this out.

However Application itself actually implements IComponentCallbacks2:

public class Application : ContextWrapper, IComponentCallbacks, IComponentCallbacks2, IJavaObject, IDisposable

So that is handled automatically and you aren't doing anything super special in those calls. 

What if you only created a custom handler and ONLY implemented IActivityLifecycleCallbacks does that make a difference?

**Comment by xleon** [comment]
Well, I think I need to implement IComponentCallbacks2 because of the OnTrimMemory that I must implement for the "IsInBackground" functionality. But I can try not implementing IComponentCallbacks2 to check if that makes something crash

**Comment by xleon** [comment]
Tested.
It doesn´t crash.
Now I think where all this is coming from. When I implemented IComponentCallbacks2 directly in the CustomApplication (without a handler), one of the methods of the interface is "public void OnConfigurationChanged(Configuration newConfig) {  }". Now I think that override could be the cause. And that´s why you are not getting errors (you are not overriding that method).
If all this is true, your custom application is not the problem but my custom implementation

**Comment by jamesmontemagno** [comment]
Oh yay! I didn't think it was, but yes it makes sense as overriding might do something different. I was worried for a minute, because I figured someone would have posted this already.

**Comment by xleon** [comment]
Just a clue. I was getting the same exception when doing this:

```
var result = await _mediaPicker.TakePhoto();
if (result == null) // user cancelled or any problem with the picture
	UserDialogs.Instance.ErrorToast("TakePicture.Error.Message".Translate());
```

Looks like you UserDialogs is messing with the window somehow (I´m completely lost here), and commenting the code did the trick. No idea what´s the actual reason though. Just saying that what you do after the await [...]TakePhoto matters.
