### ISSUE TITLE
How to get path of original video when PickVideoAsync() is called

### ISSUE THREAD

**Issue by RogerSchmidlin** [jamesmontemagno/Xamarin.Plugins#172]
I believe calling PickVideoAsync() returns a copy of a video file and puts it into a temp folder. Is there a way to get the original path of the video file without copying? I have a movie player that keeps a history of local video files that have been played.
Thanks

**Comment by jamesmontemagno** [comment]
I believe I save it on the "AlbumPath" property of the MediaFile.

**Comment by jamesmontemagno** [comment]
I may not though... as this is a feature request here: https://github.com/jamesmontemagno/Xamarin.Plugins/issues/164
