### ISSUE TITLE
Wrong photo selected with PickPhotoAsync

### ISSUE THREAD

**Issue by Guicc89** [jamesmontemagno/Xamarin.Plugins#173]
Hello,
There's an issue after selecting an image from the gallery on Android 5.1.1 (Genymotion), its seems to store the temp file with another image resource than the selected. This doesn't happen neither on ios nor in previous versions of Android

I'm using the 2.1.2 version of he plugin.media.

**Comment by jamesmontemagno** [comment]
where are you seeing the image temp file? I haven't had any issues from what I can see and the correct image is displayed for me.

**Comment by Guicc89** [comment]
Hello, 
When i select the image, it returns me the wrong filename (It has the filename of another image).
Note that this happens just in genymotion and could be an emulator issue.

**Comment by jamesmontemagno** [comment]
I would assume yes that it is a genymotion issue. Can you try on a real device or a different simulator?

Never trust an emulator :)

**Comment by Guicc89** [comment]
I couldn't reproduce this behaviour yet on a real device, however it happens very often on genymotion.
I will give you some feedback if this issue appears on another platform.
Let's assume that the issue it's due to genymotion.
Thank you for your response.

**Comment by jamesmontemagno** [comment]
Sounds good :) will close
