### ISSUE TITLE
Media plugin bug on Android when pressing home and reentering application which calls TakePhotoAsync() again

### ISSUE THREAD

**Issue by igorczapski** [jamesmontemagno/Xamarin.Plugins#174]
Steps to reproduce:
1. After Activity initialization call:
var photo = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions{
    Directory = SOME_DIRECTORY,
    Name = SOME_NAME
});

2. When you have photo app opened, press HOME button on device.
3. Reenter the app, go to your activity which calls method above.
4. InvalidOperationException -> Only one operation can be active at a time.

It doesn't matter if it's Xamarin.Forms or Xamarin.Android, obviously.

Workaround:
In Xamarin.Android just use the standard way with intents and OnActivityResult, or at least you can make some use of intent creation method, from this library.

var media = new MediaImplementation();
var intent = media.GetTakePhotoUI (new Abstractions.StoreCameraMediaOptions {
	Directory = DIRECTORY,
	Name = NAME
});
StartActivityForResult (intent, ...);

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/MediaPlugin#26
