### ISSUE TITLE
Multiple Image Select & Getting Them

### ISSUE THREAD

**Issue by doddamurali** [jamesmontemagno/Xamarin.Plugins#175]
Hi there , really thanx for developing the plugin.....
Well at present im able to select single image using your library.....
But i wanted to implement selection of multiple images from gallery & want to display them in UI
which i think is impossible right now , or jus guide me or give me an hint on how to Fetch Multiple Images From gallery using your Library ! 

#Thanx in #Advance :+1:

**Comment by jamesmontemagno** [comment]
It is not currently a feature of the Media library and I have no plans on implementing at this time.

**Comment by PerceptionToshiba** [comment]
Hi James,

Thank you for the control.  It was easy to set up and get working.  We are currently evaluating Xamarin as a solution and our current App allows multiple image selection from the Photo Libary.  I saw that this feature was requested previously and resolved as Won't Fix. Is it possible to reaconsider?  Looks like you have added many different plugins, so I'm not sure what your time commitment is to this particular plugin.

Thanks again for your time implementing this plugin.
