### ISSUE TITLE
DeviceInfo - Feature Request

### ISSUE THREAD

**Issue by Sparksteam** [jamesmontemagno/Xamarin.Plugins#176]
Hey James - can you enhance this plugin to detect and return OSX as a platform? Also, another good piece of device information would be the processor architecture, i.e. X86, x64, Ia64, ARM, etc. Thanks.

**Comment by jamesmontemagno** [comment]
I currently have no plans on support Mac as it isn't really easy to publish, but can look into processor architecture.

**Comment by Sparksteam** [comment]
Another good piece of Device Information would be to know if it's a phone. Do you have a chance to look into that as well?

Thanks,

**Comment by jamesmontemagno** [comment]
Moved to: https://github.com/jamesmontemagno/DeviceInfoPlugin/issues/1
