### ISSUE TITLE
SupportsHeading on Android Always False

### ISSUE THREAD

**Issue by ianvink** [jamesmontemagno/Xamarin.Plugins#177]
Xamarin.Forms

Works amazing in iOS, but in Android SupportsHeading == false even on devices where other Compass apps work.

I have set Permissions:
	uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" 
	uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" 
	uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" 
	uses-permission android:name="android.permission.ACCESS_WIFI_STATE" 

And I get back Lat/Lng in Android. Just not Heading

Am I missing something that needs to be enabled in Android?

**Comment by jamesmontemagno** [comment]
It actually will return it automatically, but it is extremely inaccurate
even Google doesn't recommend using it. I would suggest using the Compass
plugin if you need extremely accurate heading.

There is a closed issue in here somewhere where I link to articles.

James

**Comment by jamesmontemagno** [comment]
Here you go: https://github.com/jamesmontemagno/Xamarin.Plugins/issues/140

**Comment by ianvink** [comment]
It worked, thanks!!
