### ISSUE TITLE
[Media][Question] App seems to close after pick/take photo

### ISSUE THREAD

**Issue by lima66** [jamesmontemagno/Xamarin.Plugins#182]
for test = Motorola XT1032
xamarin forms version =  2.0.0.6490

Issue in Android when i call PickPhotoAsync() and i search the photo or i wait few seconds the app close unexpectedly.
The same is when i call TakePhotoAsync() and i wait few second or after i take a photo the app 
close unexpectedly.

No warnings, No Errors, No Exceptions

**Comment by jamesmontemagno** [comment]
Did you add additional flags to your MainActivity? 

You should setup the Android Device Monitor to see the log cat to see if something is going on. I have had no issues on these. You can test the app: https://play.google.com/store/apps/details?id=com.refractored.testappforms

**Comment by lima66** [comment]
I don't  add a additional flags to MainActivity.

I have tried your app and the second/third time I try to pick a photo the app crash and returns to the home page.

Do you have a sample project to see the correct implementation?

**Comment by jamesmontemagno** [comment]
The sample app is here: https://github.com/jamesmontemagno/Xamarin.Plugins/tree/master/TestProject/TestAppForms

**Comment by lima66** [comment]
Thank, but i don't understand where is the error.
I also set the Java Max Heap Size to 1G but the application continues to close



[logCat.txt](https://github.com/jamesmontemagno/Xamarin.Plugins/files/96060/logCat.txt)

**Comment by lima66** [comment]
Log when i try to take a photo


-19 16:25:32.388 D/Mono    (24726): Assembly Ref addref AppGloboXamarin[0x654bf280] -> Plugin.Media.Abstractions[0x654dbef8]: 2
01-19 16:25:32.388 D/Mono    (24726): Assembly Ref addref AppGloboXamarin[0x654bf280] -> System.IO[0x65a5aec0]: 3
01-19 16:25:32.393 D/Mono    (24726): Assembly Ref addref AppGloboXamarin[0x654bf280] -> Plugin.Media[0x654dfee0]: 2
01-19 16:25:32.394 D/Mono    (24726): Assembly Ref addref Plugin.Media[0x654dfee0] -> Plugin.Media.Abstractions[0x654dbef8]: 3
01-19 16:25:32.398 D/Mono    (24726): Assembly Ref addref Plugin.Media.Abstractions[0x654dbef8] -> System.Threading.Tasks[0x65abbe90]: 4
01-19 16:25:32.400 D/Mono    (24726): Assembly Ref addref Plugin.Media.Abstractions[0x654dbef8] -> System.IO[0x65a5aec0]: 4
01-19 16:25:32.403 D/Mono    (24726): Assembly Ref addref AppGloboXamarin[0x654bf280] -> Xamarin.Insights[0x659ad2c8]: 3
01-19 16:25:32.423 D/Mono    (24726): Assembly Loader probing location: '/storage/emulated/0/Android/data/it.globo.app/files/.__override__/Plugin.Permissions.Abstractions.dll'.
01-19 16:25:32.424 D/Mono    (24726): AOT module '/storage/emulated/0/Android/data/it.globo.app/files/.__override__/Plugin.Permissions.Abstractions.dll.so' not found: dlopen failed: library "/data/app-lib/it.globo.app-1/libaot-Plugin.Permissions.Abstractions.dll.so" not found
01-19 16:25:32.426 D/Mono    (24726): AOT module '/Users/builder/data/lanes/2512/d3008455/source/monodroid/builds/install/mono-armv7/lib/mono/aot-cache/arm/Plugin.Permissions.Abstractions.dll.so' not found: dlopen failed: library "/data/app-lib/it.globo.app-1/libaot-Plugin.Permissions.Abstractions.dll.so" not found
01-19 16:25:32.426 D/Mono    (24726): Assembly Ref addref Plugin.Media[0x654dfee0] -> Plugin.Permissions.Abstractions[0x654e9f48]: 2
01-19 16:25:32.430 D/Mono    (24726): Assembly Loader probing location: '/storage/emulated/0/Android/data/it.globo.app/files/.__override__/Plugin.Permissions.dll'.
01-19 16:25:32.432 D/Mono    (24726): AOT module '/storage/emulated/0/Android/data/it.globo.app/files/.__override__/Plugin.Permissions.dll.so' not found: dlopen failed: library "/data/app-lib/it.globo.app-1/libaot-Plugin.Permissions.dll.so" not found
01-19 16:25:32.433 D/Mono    (24726): AOT module '/Users/builder/data/lanes/2512/d3008455/source/monodroid/builds/install/mono-armv7/lib/mono/aot-cache/arm/Plugin.Permissions.dll.so' not found: dlopen failed: library "/data/app-lib/it.globo.app-1/libaot-Plugin.Permissions.dll.so" not found
01-19 16:25:32.433 D/Mono    (24726): Assembly Ref addref Plugin.Media[0x654dfee0] -> Plugin.Permissions[0x654eef60]: 2
01-19 16:25:32.434 D/Mono    (24726): Assembly Ref addref Plugin.Permissions[0x654eef60] -> Plugin.Permissions.Abstractions[0x654e9f48]: 3
01-19 16:25:32.435 D/Mono    (24726): Assembly Ref addref Plugin.Permissions.Abstractions[0x654e9f48] -> System.Threading.Tasks[0x65abbe90]: 5
01-19 16:25:32.437 D/Mono    (24726): Assembly Ref addref Plugin.Permissions.Abstractions[0x654e9f48] -> System.Collections[0x65a3d818]: 5
01-19 16:25:32.442 D/Mono    (24726): Assembly Ref addref Plugin.Permissions[0x654eef60] -> Mono.Android[0x65b1c7b8]: 19
01-19 16:25:32.443 D/Mono    (24726): Assembly Ref addref Plugin.Permissions[0x654eef60] -> Plugin.CurrentActivity[0x654d8f78]: 3
01-19 16:25:32.444 D/Mono    (24726): Assembly Ref addref Plugin.Permissions[0x654eef60] -> Xamarin.Android.Support.v4[0x6555ea78]: 3
01-19 16:25:32.449 D/Mono    (24726): Assembly Ref addref Plugin.Permissions[0x654eef60] -> System.Core[0x6632c480]: 10
01-19 16:25:32.501 I/ActivityManager( 1024): START u0 {flg=0x10000000 cmp=it.globo.app/md5426df52c3692a7a242e80cbb3363c75d.MediaPickerActivity (has extras)} from pid 24726
01-19 16:25:32.504 W/ContextImpl( 1298): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1252 android.content.ContextWrapper.sendBroadcast:365 com.motorola.motocare.util.TriggerHelper$TriggerBuilder.send:76 com.motorola.motocare.internal.frameworkevents.PauseResumeTrigger.handleFrameworkEvent:53 com.motorola.motocare.internal.frameworkevents.FwEventMonitor$FrameworkListener.processFrameworkEvent:114 
01-19 16:25:32.527 W/ContextImpl( 1298): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1252 android.content.ContextWrapper.sendBroadcast:365 com.motorola.motocare.util.TriggerHelper$TriggerBuilder.send:76 com.motorola.motocare.internal.frameworkevents.PauseResumeTrigger.handleFrameworkEvent:53 com.motorola.motocare.internal.frameworkevents.FwEventMonitor$FrameworkListener.processFrameworkEvent:114 
01-19 16:25:32.583 D/WifiStateMachine( 1024): handleMessage: E msg.what=151572
01-19 16:25:32.584 D/WifiStateMachine( 1024): processMsg: ConnectedState
01-19 16:25:32.584 D/WifiStateMachine( 1024): processMsg: L2ConnectedState
01-19 16:25:32.609 D/WifiStateMachine( 1024): handleMessage: X
01-19 16:25:32.623 D/Mono    (24726): Assembly Ref addref Plugin.Media[0x654dfee0] -> System[0x66569f88]: 14
01-19 16:25:32.634 I/ActivityManager( 1024): START u0 {act=android.media.action.IMAGE_CAPTURE cmp=com.motorola.camera/.Camera (has extras)} from pid 24726
01-19 16:25:32.635 W/ContextImpl( 1298): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1252 android.content.ContextWrapper.sendBroadcast:365 com.motorola.motocare.util.TriggerHelper$TriggerBuilder.send:76 com.motorola.motocare.internal.frameworkevents.PauseResumeTrigger.handleFrameworkEvent:53 com.motorola.motocare.internal.frameworkevents.FwEventMonitor$FrameworkListener.processFrameworkEvent:114 
01-19 16:25:32.655 I/ActivityManager( 1024): Start proc com.motorola.camera for activity com.motorola.camera/.Camera: pid=24837 uid=10012 gids={50012, 1028, 1015}
01-19 16:25:32.675 W/ContextImpl( 1298): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1252 android.content.ContextWrapper.sendBroadcast:365 com.motorola.motocare.util.TriggerHelper$TriggerBuilder.send:76 com.motorola.motocare.internal.frameworkevents.PauseResumeTrigger.handleFrameworkEvent:53 com.motorola.motocare.internal.frameworkevents.FwEventMonitor$FrameworkListener.processFrameworkEvent:114 
01-19 16:25:32.727 W/AppOps  ( 1024): Bad call: specified package qcamera under uid 1013 but it is really -1
01-19 16:25:32.768 W/AppOps  ( 1024): Bad call: specified package qcamera under uid 1013 but it is really -1
01-19 16:25:32.770 W/AppOps  ( 1024): Bad call: specified package qcamera under uid 1013 but it is really -1
01-19 16:25:32.811 W/AppOps  ( 1024): Bad call: specified package qcamera under uid 1013 but it is really -1
01-19 16:25:32.874 W/CameraBgProcess(24837): BGPROC Not Supported
01-19 16:25:32.900 W/AppOps  ( 1024): Bad call: specified package qcamera under uid 1013 but it is really -1
01-19 16:25:32.941 W/AppOps  ( 1024): Bad call: specified package qcamera under uid 1013 but it is really -1
01-19 16:25:32.943 W/AppOps  ( 1024): Bad call: specified package qcamera under uid 1013 but it is really -1
01-19 16:25:32.984 W/AppOps  ( 1024): Bad call: specified package qcamera under uid 1013 but it is really -1
01-19 16:25:33.076 W/LayoutParamsReflection(24837): unable to initialize class
01-19 16:25:33.091 D/Sensors ( 1024): AccelerationSensor: set delay 200
01-19 16:25:33.126 I/dalvikvm(24837): Could not find method android.content.pm.PackageManager.getPackageInstaller, referenced from method com.google.android.gms.common.GooglePlayServicesUtil.zzh
01-19 16:25:33.127 W/dalvikvm(24837): VFY: unable to resolve virtual method 470: Landroid/content/pm/PackageManager;.getPackageInstaller ()Landroid/content/pm/PackageInstaller;
01-19 16:25:33.127 D/dalvikvm(24837): VFY: replacing opcode 0x6e at 0x000b
01-19 16:25:33.129 W/AppOps  ( 1024): Bad call: specified package qcamera under uid 1013 but it is really -1
01-19 16:25:33.137 D/WearableService(31742): callingUid 10003, callindPid: 31742

**Comment by jamesmontemagno** [comment]
Posting a full log doesn't help me and just clutters a GitHub issue. Please do not do this in the future and post to Gist.

**Comment by jamesmontemagno** [comment]
Have you added the plugin NuGets to all of your projects? What device are you using? Is this Debug or Release? Are you AOTing the app in the setting. You need to provide me with more information or give me a small sample that you can repo. If the app is in Debug you would get Application output that would help to see what is actually crashing as there is nothing really here in the logs.

**Comment by lima66** [comment]
Device = Motorola XT1032

And the sample app is here:
[GitHub](https://github.com/lima66/SampleAppXamarin) 

thank you very much for helping

**Comment by jamesmontemagno** [comment]
Just ran it on my Nexus 6P and have absolutely no issue at all. Images are showing in the UI for taking and picking a picture.

**Comment by lima66** [comment]
I think it's a problem with the device, because I tested the application on Tablet galaxy tab 2 and nexus 5 and it works well
