### ISSUE TITLE
[Question] does the Geolocator plugin supports location changes when the App is closed (not running)

### ISSUE THREAD

**Issue by aunanue** [jamesmontemagno/Xamarin.Plugins#183]
[Question] does the Geolocator plugin supports location changes when the App is closed (not running)?
Is there any way to start the App as a service in order to receive the changes in the CrossGeolocator.Current.PositionChanged event?

**Comment by jamesmontemagno** [comment]
You would need to put it in a background service on Android or on iOS enable the background location changes.
