### ISSUE TITLE
Settings: Unable to use in Xamarin Unified iOS Project?

### ISSUE THREAD

**Issue by roXDesign** [jamesmontemagno/Xamarin.Plugins#19]
I am trying to use the CrossSettings Library in a PCL with this line:

public static object getSetting(string key)
{ 
   return CrossSettings.Current.GetValueOrDefault(key,string.Empty);
}

And all I get is a "System.IO.FileNotFoundException" - Could not load file or assembly 'monotouch, Version 0.0.0.0'...

I am running version 1.4.0.1 which should be unified api compatible ?
just tried.. this also happens with 2.0.0-alpha

Thanks for your help.

**Comment by jamesmontemagno** [comment]
If you have migrated your project you should remove all of your NuGets and re-add them so they are re-started as the latest version does support unified.

**Comment by roXDesign** [comment]
Hello James, thanks for your reply!

I actually did that already.. still does not work :( Not sure whats happening there. I'll have a look in the xamarin.ios10 folder asap.

**Comment by jamesmontemagno** [comment]
Also, make sure you have the latest version of NuGet package manager installed in Visual Studio. You can ensure that this is updated if you go to Tools->Extensions and Updates and look under updates.

**Comment by jjbrunton** [comment]
I am currently having this issue, have tried readding all of the packages and updating nuget but still getting an exception referencing monotouch.

**Comment by gerryhigh** [comment]
Running into the same thing with a project that was converted to Unified (I've not run into this on new Unified projects using the PCL).

Unhandled managed exception: Could not load file or assembly 'monotouch, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' or one of its dependencies. (System.IO.FileNotFoundException)
  
Dies on this line: Refractored.Xam.Settings.CrossSettings.Current.GetValueOrDefault<string>(...)

In my .csproj I have:
    <Reference Include="Refractored.Xam.Settings">
      <HintPath>packages\Xam.Plugins.Settings.1.5.0\lib\Xamarin.iOS10\Refractored.Xam.Settings.dll</HintPath>
    </Reference>
    <Reference Include="Refractored.Xam.Settings.Abstractions">
      <HintPath>packages\Xam.Plugins.Settings.1.5.0\lib\Xamarin.iOS10\Refractored.Xam.Settings.Abstractions.dll</HintPath>
    </Reference>

Thoughts?

**Comment by jamesmontemagno** [comment]
See: https://github.com/jamesmontemagno/Xamarin.Plugins/issues/30#issuecomment-75313889

**Comment by gerryhigh** [comment]
That's a nice "feature"! :)

Fixed it for me.  I see now you have a few people having to do the same thing.
