### ISSUE TITLE
Does not have storage or camera permissions granted, requesting.

### ISSUE THREAD

**Issue by piandcache** [jamesmontemagno/Xamarin.Plugins#190]
FrameWork                   = Use latest installed platform (6.0)
Target Android Version = Automatic (API 23)
Min version                    = 4.0.3

Manifest has all three required permissions. read, write and camera.

Works fine on 21, 17 but seems to throw error on 4.0.3 Samsung GT-P7510 (API 15)

[Mono] Assembly Ref addref Plugin.Media[0x21f15d0] -> Mono.Android[0x222d530]: 25
[Mono] Assembly Ref addref Plugin.Media.Abstractions[0x21f2640] -> System.Resources.ResourceManager[0x2217240]: 7
[Mono] Assembly Loader probing location: '/mnt/sdcard/Android/data/com.company/files/.__override__/Plugin.Permissions.Abstractions.dll'.
[Mono] AOT module '/mnt/sdcard/Android/data/com.company/files/.__override__/Plugin.Permissions.Abstractions.dll.so' not found: Cannot load library: load_library[1092]: Library '/data/data/com.company/lib/libaot-Plugin.Permissions.Abstractions.dll.so' not found
[Mono] AOT module '/Users/builder/data/lanes/2098/3efa14c4/source/monodroid/builds/install/mono-armv7/lib/mono/aot-cache/arm/Plugin.Permissions.Abstractions.dll.so' not found: Cannot load library: load_library[1092]: Library '/data/data/com.company/lib/libaot-Plugin.Permissions.Abstractions.dll.so' not found
[Mono] Assembly Ref addref Plugin.Media[0x21f15d0] -> Plugin.Permissions.Abstractions[0x21f05b8]: 2
[Mono] Assembly Ref addref Plugin.Permissions.Abstractions[0x21f05b8] -> System.Runtime[0x221eae8]: 24
[Mono] Assembly Loader probing location: '/mnt/sdcard/Android/data/com.company/files/.__override__/Plugin.Permissions.dll'.
[Mono] AOT module '/mnt/sdcard/Android/data/com.company/files/.__override__/Plugin.Permissions.dll.so' not found: Cannot load library: load_library[1092]: Library '/data/data/com.company/lib/libaot-Plugin.Permissions.dll.so' not found
[Mono] AOT module '/Users/builder/data/lanes/2098/3efa14c4/source/monodroid/builds/install/mono-armv7/lib/mono/aot-cache/arm/Plugin.Permissions.dll.so' not found: Cannot load library: load_library[1092]: Library '/data/data/com.company/lib/libaot-Plugin.Permissions.dll.so' not found
[Mono] Assembly Ref addref Plugin.Media[0x21f15d0] -> Plugin.Permissions[0x21ef540]: 2
[Mono] Assembly Ref addref Plugin.Permissions[0x21ef540] -> mscorlib[0x2091c50]: 49
[Mono] Assembly Ref addref Plugin.Permissions[0x21ef540] -> Plugin.Permissions.Abstractions[0x21f05b8]: 3
[Mono] Assembly Ref addref Plugin.Permissions.Abstractions[0x21f05b8] -> System.Threading.Tasks[0x2226768]: 12
[Mono] Assembly Ref addref Plugin.Permissions.Abstractions[0x21f05b8] -> System.Collections[0x22008c8]: 16
[Mono] Assembly Ref addref Plugin.Permissions[0x21ef540] -> Mono.Android[0x222d530]: 26
[Mono] Assembly Ref addref Plugin.Permissions[0x21ef540] -> Plugin.CurrentActivity[0x21ee560]: 3
[Mono] Assembly Ref addref Plugin.Permissions[0x21ef540] -> Xamarin.Android.Support.v4[0x21e6a28]: 4
[Mono] Assembly Ref addref Plugin.Permissions[0x21ef540] -> System.Core[0x231bbe8]: 15
Does not have storage or camera permissions granted, requesting.

**Comment by jamesmontemagno** [comment]
Set your Target explicitly to 23, that is best practice. 

This didn't really help as you did not mention the code you are calling, how you are calling, list of all permissions in the manifest. And you should never post a full stack trace in here, please post it all on a gist: gist.github.com then I can help

**Comment by jamesmontemagno** [comment]
I cleaned this code up a bit in latest package 2.2.x.
