### ISSUE TITLE
Xamarin.Forms.Maps.Geocoder not working with Geolocator plugin in Android

### ISSUE THREAD

**Issue by jovymathew** [jamesmontemagno/Xamarin.Plugins#191]
When using the GeoLocator plugin in a Xamarin Forms app which also is using the Xamarin.Forms.Maps.Geocoder, the Geocoder stops functioning and the execution is stuck on the geocoder's  GetAddressesForPositionAsync call.

var locator = CrossGeolocator.Current;
locator.DesiredAccuracy = 50;

var position = await locator.GetPositionAsync(timeoutMilliseconds: 10000); 
if (position != null) {
				Geocoder geoCoder = new Geocoder();
				IEnumerable<string>  addressList = geoCoder.GetAddressesForPositionAsync(new Position(position.Latitude, position.Longitude)).Result;
}

**Comment by jamesmontemagno** [comment]
You should never call .Result like that as it will lock the thread:
```
var addressList = await geoCoder.GetAddressesForPositionAsync(new Position(position.Latitude, position.Longitude));
```
