### ISSUE TITLE
[Feature Request] [Text to Speech] Allow custom TTS Engine on Android

### ISSUE THREAD

**Issue by lovittmccormick** [jamesmontemagno/Xamarin.Plugins#194]
Android allows a TTS Engine (string) to be passed in to the TextToSpeech constructor, it would be nice to have an additional flag for Android to set the package name that is part of the constructor:

See documentation: [Docs](http://developer.android.com/reference/android/speech/tts/TextToSpeech.html#TextToSpeech(android.content.Context, android.speech.tts.TextToSpeech.OnInitListener, java.lang.String))

Modification to allow a TTS engine selection. For Android, generally done through the constructor.

----------
        public void Init()
        {
            Console.WriteLine("Current version: " + (int)global::Android.OS.Build.VERSION.SdkInt);
            Android.Util.Log.Info("CrossTTS", "Current version: " + (int)global::Android.OS.Build.VERSION.SdkInt);

            textToSpeech = new Android.Speech.Tts.TextToSpeech(Application.Context, this,<<TTS ENGINE>>);
        }

Idea would just to have a string on the Android implementation that can be set and modified.

**Comment by jamesmontemagno** [comment]
Are you suggesting a feature or have you implemented this and looking to do a pull request? Please go ahead and submit a pull request if you desire. Else open a new issue as a feature request as to what it is, why, and if you have an idea for implementation.

**Comment by lovittmccormick** [comment]
Yep Sorry... Is a feature request (Which i saw no way to flag as in
GitHub). New to that process...


----------------------------------------------
*Mark McCormick*
*Director of Research*
Votuit Inc

**Comment by jamesmontemagno** [comment]
So, I have modified your title and your request. Take a look at how I did it. The more details and more specific you can be the better so I can tag it correctly.

**Comment by lovittmccormick** [comment]
No Worries... Nicely done.

**Comment by jamesmontemagno** [comment]
Moved to: https://github.com/jamesmontemagno/TextToSpeechPlugin/issues/4
