### ISSUE TITLE
[Feature] Android Permission - Use Blank Activity

### ISSUE THREAD

**Issue by aritchie** [jamesmontemagno/Xamarin.Plugins#197]
Hey James

I would love to use the permissions plugin, but the hack of dropping in the same block of code per activity just doesn't sit with me.  Something I was considering doing was a transparent activity that can request the permission and dialogs while staying under the control of the plugin.  You also wouldn't need your top activity plugin any longer to accomplish this.  You could do Application.Context.StartActivity(typeof(TransparentPermissionPluginActivity));

I'll do a PR if you're interested.

**Comment by jamesmontemagno** [comment]
My recommendation is that you simply have a base activity with your call in
it. It has to pass up the arguments, and it would only need to be on an
activity that needs to request the permission. This same code would have to
be written if you were implementing permissions. The idea of a transparent
activity is interesting. However I am not sure if adding and launching
adding activities are a great solution and could have odd side effects that
the developer is no longer in control of. Adding 2 lines of code to a base
activity is pretty good personally. However I am open to ideas.

**Comment by aritchie** [comment]
I have had several projects pop up lately that have a ton of activities without any sort of base activity.  Fixing this is in the long term goals, but in the meantime, I have to get runtime permissions working.

The idea of the transparent activity shouldn't cause any side effects other than pushing/popping an activity like normal.  The difference is that the plugin now has the control it needs to display and request things without popping in any code.  This will remove the need for all of the top activity stuff as well.

I'll fork and test in any case.

**Comment by jamesmontemagno** [comment]
Hmmm yeah, I would be interested in testing this out. The more I think about it I don't mind it at all. Would  probably just get around any common errors when installing NuGets if people don't read docs.

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/PermissionsPlugin#1
