### ISSUE TITLE
Media Plugin (WP8.1 SL) : How to avoid picture to be saved in "Camera Roll" album ?

### ISSUE THREAD

**Issue by An0d** [jamesmontemagno/Xamarin.Plugins#198]
Hi,

Thanks to the Media Plugin, it's really easy to take picture within Xamarin Forms Apps.

However, I'm facing a small issue on Windows Phone Silverlight 8.1.
When taking a photo, it's properly saved to the local application storage but I noticed that the picture is always saved to the "Camera Roll" album... Under a different name.

I would like to know whether it is possible or not to prevent saving in the "Camera Roll" album ? And thus save the picture only in the local application storage ?

Thank you and thank you for your work !

EDIT : Before you ask, [SaveToAlbum] is not set and I also tried with [SaveToAlbum = false] ;-)

**Comment by jamesmontemagno** [comment]
Unfortunately this is a limitation in Windows Phone 8 SL: https://msdn.microsoft.com/library/windows/apps/hh394006(v=vs.105).aspx

On Windows Phone 8, if the user accepts a photo taken with the camera capture task, the photo is automatically saved to the phone’s camera roll. 

I will document this.

**Comment by An0d** [comment]
Okay thank you :-)


Thanks for your time & your work !
