### ISSUE TITLE
[Connectivity] Handling connected but offline state improvement in Android

### ISSUE THREAD

**Issue by rihadavid** [jamesmontemagno/Xamarin.Plugins#199]
In some situation there is few-minutes deadlock in Android
`await CrossConnectivity.Current.IsRemoteReachable(host);`

This is happening to me if I am calling this in situation where I am on wifi but something is wrong with the wifi and internet is not reachable.

More about this issue and how I solved it can be found [here](https://forums.xamarin.com/discussion/36993/connectivity-plugin/p2?)

Please consider implementing this workaround to production version of the plugin.

**Comment by jamesmontemagno** [comment]
David, thanks for the info, I do accept pull requests and would love that.

Can you describe your repo steps and the code you used to call it.

Thanks.

**Comment by rihadavid** [comment]
Ok, i've just made the pull request. I hope that what i wrote in description is helpful.
Thanks

**Comment by jamesmontemagno** [comment]
Will be available in next NuGet :) thanks
