### ISSUE TITLE
Android App restarts after taking photo

### ISSUE THREAD

**Issue by kryz** [jamesmontemagno/Xamarin.Plugins#201]
In rare cases it happens, that after taking a photo, the android app restarts. Therefore  "await CrossMedia.Current.TakePhotoAsync(options)" never returns, so i won't get the path to the taken picture.

Trying to find the problem, I saw that ActivityFlags.NewTask is set on the Intent. The android documentation says "This flag can not be used when the caller is requesting a result from the activity being launched. " (http://developer.android.com/reference/android/content/Intent.html#FLAG_ACTIVITY_NEW_TASK). So I wonder whether this could be a problem. I guess you need to get the filepath back from the camera activity?

**Comment by jamesmontemagno** [comment]
What device are you testing on? I haven't had any issue here on Nexus6, Nexus 6p, motox, moto e, or moto g.

**Comment by kryz** [comment]
I have a Galaxy S3 with Android 4.3 installed.

**Comment by kryz** [comment]
Hey James

I was working on a low budget project. So we had to decide to accept this behaviour. Therefore I won't have any more time to investigate.

My feeling tells me, that this behaviour only occured after taking more than one picture. After taking a picture I rotate and scale it. But I make shure to recycle and dispose all the bitmaps. So I don't see a memoryleak. Never the less I try to prevent this behaviour by explicitly calling the Garbage Collector.

As I can't investigate any further, it would be ok for me to close this report.

Btw.: Thanks for your work. You have some nice libraries here on github :+1:
