### ISSUE TITLE
[Feature request] Remove all method

### ISSUE THREAD

**Issue by oansquer** [jamesmontemagno/Xamarin.Plugins#204]
Hello,

Can you add a method to remove all settings ?
In my app, I have a reset command and I want to be sure to remove all settings values.
On Android, I do it with;

ISharedPreferencesEditor edit = Preferences.Edit();
edit.Clear();
edit.Commit();

On UWP:

ApplicationDataContainer settings = ApplicationData.Current.LocalSettings;
foreach (string key in settings.Values.Select((p) => p.Key).ToList())
{
   settings.Values.Remove(key);
}

Thanks,

Olivier

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/SettingsPlugin#7
