### ISSUE TITLE
when orientation changes after calling CrossMedia.Current.Take..Async, MediaFile is empty.

### ISSUE THREAD

**Issue by volkan-akkus** [jamesmontemagno/Xamarin.Plugins#206]
Hi, thank you for ready-to-use plugins. I am using them and really appreciate it.

I have tried on Samsung Note 2 API 19 lots of times with all updated nugets and xamarin.

If I change the orientation after calling CrossMedia.Current.Take*Async, returning MediaFile is null.

thanks for your efforts, again.

**Comment by jamesmontemagno** [comment]
Will be fixed in 2.4.0-beta1 today
