### ISSUE TITLE
Media Plugin for UWP

### ISSUE THREAD

**Issue by Sudhacc** [jamesmontemagno/Xamarin.Plugins#207]
Hi, Thank you so much for the plugins. its really helpful. i want to implement Taking Video and Picture functionalists in Windows(UWP) . i have checked the plugin but there is no Media implementation code for UWP. Can i expect the support any time soon?

**Comment by jamesmontemagno** [comment]
Interesting... the nuget is out of date.... oddd fixing this up.

**Comment by jamesmontemagno** [comment]
In 2.3.0: https://www.nuget.org/packages/Xam.Plugin.Media/2.3.0

**Comment by Sudhacc** [comment]
Great. Thank you!!
