### ISSUE TITLE
'Black Screen' / Unable to take picture on Ipad mini 2, IOS 9.2

### ISSUE THREAD

**Issue by NVentimiglia** [jamesmontemagno/Xamarin.Plugins#208]
Gallery works fine. When I press the TakePicture button the camera shows but the screen is black. I tried switching cameras, would not help. I did notice some yellow outlines as if the image recognition and identification system was running. When I tried to take a picture nothing happened.

IPad Mini 2, running on IOS 9.2

**Comment by 100s** [comment]
I have the same.

**Comment by xleon** [comment]
Same here on iphone5

**Comment by xleon** [comment]
Well, investigating a bit more, I think this can happen when the user does not have permissions to access the camera. Some times I get the permission request. Some times I don´t (even reinstalling the app). Not sure why

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/MediaPlugin#25
