### ISSUE TITLE
Geolocator - Detect GPS signal lost?

### ISSUE THREAD

**Issue by mhirons** [jamesmontemagno/Xamarin.Plugins#209]
With the Geolocator plugin, is there a way to detect that the GPS signal has been lost/gained?

**Comment by jamesmontemagno** [comment]
You would probably receive an error back via 
```
event EventHandler<PositionErrorEventArgs> PositionError;
```

**Comment by mhirons** [comment]
That was my initial thought, as well.  However, it doesn't appear to be raising the PositionError event.  If I turn off location services, I get an error, but not if the GPS just loses position due to being in a building, etc.  Not a big deal, I was more curious than actually needing this functionality.
