### ISSUE TITLE
UnifiedAPI DeviceInfo isn't on nuget

### ISSUE THREAD

**Issue by shanempope** [jamesmontemagno/Xamarin.Plugins#21]
Hey James, sorry to bother. I'm getting IOException monotouch not found exception in the UnifiedAPI using Xam.Plugins.DeviceInfo (the 1.0.0.2 one on nuget). It works fine if I just build the DLLs, so that works for now. I was wondering when you plan on updating the nuget to have the unified iOS version. Thanks, Shane

**Comment by jamesmontemagno** [comment]
It is there, please ensure that you have your NuGet package manager up to date in VS

https://github.com/jamesmontemagno/Xamarin.Plugins/blob/master/DeviceInfo/DeviceInfo.Plugin.nuspec#L76-L81

James
