### ISSUE TITLE
[feature request] Media Picker Option to set image size

### ISSUE THREAD

**Issue by rd09** [jamesmontemagno/Xamarin.Plugins#210]
It would be very helpful to have the option in StoreCameraMediaOtions of setting an image size.

**Comment by jamesmontemagno** [comment]
Can you try out https://www.nuget.org/packages/Xam.Plugin.Media/2.4.0-beta2

I added a "PhotoSize" for small, medium, and large for scaling 25, 50, and 75% for iOS and Android;

**Comment by rd09** [comment]
Thanks, that is awesome!

**Comment by LogicMate** [comment]
Also would we be able to force the orientation of the camera?

**Comment by jamesmontemagno** [comment]
I have thought about doing a custom ratio and may change it in the future, but wanted to get some feedback. Just need to add a lot of logic. A scale was easier to implement that would cover most use cases.

**Comment by marcojak** [comment]
When I set PhotoSize = Plugin.Media.Abstractions.PhotoSize.Small, the image become a square. If I don't set the PhotoSize property, the image is fine.
This happens on iOS. I tested it on an iPad mini but a colleague with an iphone 5 told me the same.

**Comment by AvBrenk** [comment]
@jamesmontemagno First of all, I have been using your Media plugin for a while now. It works great, thanks for making this available for us.

Is there any news on this feature? I have been following it, and I see there is a beta version available. Is that version "safe" to use in a production app? I would like to use the plugin for another app, but I need the resizing and auto-rotate functionality for that one. Any idea on when this will be in a production version?

Thanks in advance.

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/MediaPlugin#24

**Comment by fabriciomoreirao** [comment]
very good

**Comment by fabriciomoreirao** [comment]
var mediaFile = await this._mediaPicker.TakePhotoAsync(new StoreCameraMediaOptions
                {
                    DefaultCamera = CameraDevice.Front,
                    PhotoSize =  PhotoSize.Medium 
    
                });

**Comment by fabriciomoreirao** [comment]
var pick = new PickMediaOptions();
                pick.PhotoSize = PhotoSize.Medium;
                
                var mediaFile = await this._mediaPicker.PickPhotoAsync(pick);

**Comment by okerider** [comment]
Any updates on the MediaPicker yet?
