### ISSUE TITLE
Get Exception in Mvx.GetSingleton<ISettings>()) 

### ISSUE THREAD

**Issue by derhexer13** [jamesmontemagno/Xamarin.Plugins#211]
If i attempt to access your Helpers.Setting like following code

        Settings.Subscriptions = "Test";

i got an exception.

The exception came up in Mvx.GetSingleton<ISettings>()

        private static ISettings _mSettings;
		private static ISettings AppSettings => _mSettings ?? (_mSettings = Mvx.GetSingleton<ISettings>());

Here is my code:

    public static class Settings
    {
        /// <summary>
        /// Simply setup your settings once when it is initialized.
        /// </summary>
        private static ISettings _mSettings;
		private static ISettings AppSettings => _mSettings ?? (_mSettings = Mvx.GetSingleton<ISettings>());

		#region Subscriptions Constants
		private const string SubscriptionsKey = "subscriptions";
		private static readonly string SubscriptionsDefault = string.Empty;
		#endregion

		public static string Subscriptions
		{
			get
			{
				return AppSettings.GetValueOrDefault(SubscriptionsKey, SubscriptionsDefault);
			}
			set
			{
				AppSettings.AddOrUpdateValue(SubscriptionsKey, value);
			}
		}
	}

The exception contains following error
ex = {System.NullReferenceException: Object reference not set to an instance of an object
  at Cirrious.CrossCore.Mvx.GetSingleton[T] () [0x00006] in <filename unknown>:0 
  at TestApp.Helpers.Settings.set_Subscriptions (System.String value) [0x00001] in C...

I'm developing a pcl app and just testing with the iphone simulator.

**Comment by derhexer13** [comment]
After changing to Xam.Plugins.Settings the Helper.Settings example changes to

    private static ISettings AppSettings
    {
      get
      {
        return CrossSettings.Current;
      }
    }

and now all works fine.
I think there had something to be initalized it didn't do...

**Comment by jamesmontemagno** [comment]
Nope :) I put down a code file for you too :) Enjoy
