### ISSUE TITLE
"Task was cancelled" exception thrown in some android device while calling "GetPositionAsync"

### ISSUE THREAD

**Issue by tselvan2311** [jamesmontemagno/Xamarin.Plugins#212]
"Task was cancelled" exception thrown in some android device while calling "GetPositionAsync".

**Comment by 100s** [comment]
I have the same problem, Samsung Galaxy S 4

**Comment by jamesmontemagno** [comment]
That means it timed out. You can increase the timeout by passing in a larger number. Every device is different based on network

**Comment by kolchy** [comment]
Timeout is set for 10 seconds, but I get this error almost instantly:

loc = await locator.GetPositionAsync (timeoutMilliseconds: 10000);

**Comment by Sivamuralidhar** [comment]
yea even I am getting same issue. please post solution if anyone have
