### ISSUE TITLE
Media plugin EXC_BAD_ACCESS (SIGABRT)

### ISSUE THREAD

**Issue by DVrsajko** [jamesmontemagno/Xamarin.Plugins#213]
Hi,

I am having issues when taking pictures on any iOS device I'vre tried (iPad mini 2, iPad 3, iPhone 5s).

Exception Subtype:  KERN_INVALID_ADDRESS at 0x00.

I am investigating this for the last 4 days, and got to the point that can't go further without some help.
I caught a zombie during device debug with instruments and saved it to a trace file.

Snapshot result:
An Objective-C message was sent to a deallocated 'PLImagePickerCameraView' object (zombie) at address: 0x13...
Event Type/Responsible library/Caller: 
malloc/PhotoLibrary/-[PLUICameraViewController loadView]
Zombie/Foundation/__NSFireDelayedPerform

This happens when an image is taken and "Use picture" is tapped. I process the image and navigate to next page after saving the image to SQLite as byte[]. The image saves, the whole new page is constructed but never reaches OnAppearing. The problem is that this happens only sometimes. 
I couldn't figure out the pattern for replicating it. The only thing that somehow is consistent is the use of zoom option. When using zoom it happens more frequently.

This all could very much be in the way the page is built. I am building it dynamically with for loop, because the user has Occurrence that needs to match the number of photos he can take per page. This could be a problem, but I created class references to all items in the loop and it is still happening.

If needed I can post some code of the way I am using your plugin, but it is set up exactly how you recommended. The funny thing is that it worked perfectly before. So i updated to the last version but it did not help.

Cant find a way to pinpoint the source code responsible for this.

Can you help please?

Kind regards,
Dalibor Vrsajko

**Comment by DVrsajko** [comment]
It looks like that your plugin is not doing this, as I figured my code is the culprit. It seems that my ImageSource.FromStream is doing this.

I am obviously not handling something the way I should.

**Comment by DVrsajko** [comment]
Hi James,

After a lot more hassle I managed to reproduce the issue that was causing the SIGABRT on iOS 9.2.
Access to an already released object.

The problem is in the Media plugin, and I hope that this will help others so they wont have to spend days on this like I did.

Steps to reproduce:
1. Open Camera view
2. Portrait orientation
3. Take image
4. Click use image and quickly change the orientation of the device to landscape (may need a few attempts because it is all about timing)

As far as I see it, the problem was that the plugin did not stop listening for orientation notifications on time, so the user could trigger the notification to be sent to the view, but in the time it came dispose already took place, and then it of course crashed.

It took me a while to get all this sorted because no Insights error caught this, and with Instruments I got nowhere. Only to catch zombies with no code.

I have applied your code directly in my solution and changed a few lines of code in MediaPickerDelegate.cs. After that everything works fine. I just cant reproduce ti anymore.

1. In Dismiss method I commented:
      NSNotificationCenter.DefaultCenter.RemoveObserver(observer);
      UIDevice.CurrentDevice.EndGeneratingDeviceOrientationNotifications();
2. In Canceled and FinishedPickingMedia I inserted at the top:
        public override async void FinishedPickingMedia(UIImagePickerController picker, NSDictionary info)
        {
            UIDevice.CurrentDevice.EndGeneratingDeviceOrientationNotifications();
            NSNotificationCenter.DefaultCenter.RemoveObserver(observer);
            ...

Any confirmation on this would be appreciated.

Thank you.

Kind regards,
Dalibor Vrsajko

**Comment by jamesmontemagno** [comment]
If you have a fix for this can you send down a pull request please?

**Comment by DVrsajko** [comment]
NP. 
Done.

I stated in the pull request that I have not changed the Android or WPhone code. There is no way i can test it, and have no idea if there is an issue on those platforms.

Kind regards,
Dalibor Vrsajko

**Comment by ssultan** [comment]
I am facing the same issue in Objective-C code. 
But I am not sure which 'Observer' you mentioned in your code @DVrsajko 
NSNotificationCenter.DefaultCenter.RemoveObserver(observer);

How can I get this notification 'observer'? Can you please help me. I saw in my zombie profile that, orientation might be the issue. Then in didFinishPickingMediaWithInfo method, I added only this 'EndGeneratingDeviecOrientationNotifications' line and still I am facing same zombie crash issue.
UIDevice.CurrentDevice.EndGeneratingDeviceOrientationNotifications();

If you can tell me how to get this 'observer' object, then hopefully i would be able to fix the issue.

**Comment by DVrsajko** [comment]
Hi @ssultan,

Unfortunately I am not working in Objective-C code (hence the need for this plugin).
Your problem can be caused by loads of things.

Try asking for help on the Apple Objective-C support site with your code example for starters.

Good luck,
Dalibor
