### ISSUE TITLE
Connectivity Throwing an error

### ISSUE THREAD

**Issue by ibrahimAJ** [jamesmontemagno/Xamarin.Plugins#214]
connectivity plugin is throwing error like Unable to resolve host.no address is associated with host.internet,network state,wifi state permissions also given in androidmanifest.xml,but that dns in the hostname is not accepting.why.what is the reason behind that

**Comment by jamesmontemagno** [comment]
What URL are you passing it?

**Comment by ibrahimAJ** [comment]
www.tranzportal.ie it is ping in commandprompt but in app its not reaching

**Comment by jamesmontemagno** [comment]
Specifically the documentation reads:
/// <summary>
/// Tests if a remote host name is reachable (no http:// or www.)
/// </summary>
/// <param name="host">Host name can be a remote IP or URL of website</param>
/// <param name="port">Port to attempt to check is reachable.</param>
/// <param name="msTimeout">Timeout in milliseconds.</param>
/// <returns></returns>
Task<bool> IsRemoteReachable(string host, int port = 80, int msTimeout = 5000);


Note: Tests if a remote host name is reachable (no http:// or www.)

**Comment by ibrahimAJ** [comment]
i tried using http:// or www but when i use this way it is throwing unresolve host but when we pass only ip address as url that is not reaching but in commanprompt it is pingable.what may be reason behind that?

**Comment by jamesmontemagno** [comment]
When you go to that URL it is a 500 error so I assume it can't reach it as
it is returning an error.

**Comment by ibrahimAJ** [comment]
yes i am getting that 500 error in broswer when i test with that url

**Comment by ibrahimAJ** [comment]
but how it  is ping in commandprompt

**Comment by jamesmontemagno** [comment]
Most likely different protocol that it is trying. Try google.com or any
other website that is running I am sure it will work just fine.

**Comment by ibrahimAJ** [comment]
using www.google.com as hostname to check whether the server is reachable or not is showing server not reachable only.

**Comment by jamesmontemagno** [comment]
What device and what OS are you using?

On Thu, Feb 11, 2016 at 1:48 AM, ibrahimAJ <notifications@github.com> wrote:

> using www.google.com as hostname to check whether the server is reachable
> or not is showing server not reachable only.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jamesmontemagno/Xamarin.Plugins/issues/214#issuecomment-182785446>
> .
>



-- 
James Montemagno
http://www.montemagno.com
@jamesmontemagno <http://www.twitter.com/jamesmontemagno>

**Comment by ibrahimAJ** [comment]
Nexus One(3.7",480x800;hdpi),android 5.0.1-API Level21

**Comment by jamesmontemagno** [comment]
Do you see anything in the log cat or can you try to run the actual code and see what the exception is. Running fine for me on my device (6P) and also emulators:
![image](https://cloud.githubusercontent.com/assets/1676321/13012744/c44e8a72-d169-11e5-9e8a-45a1924b1969.png)

I assume you have the internet permission checked in release mode
