### ISSUE TITLE
Permissions uses C# 6 features, unable to build in Xamarin Studio 

### ISSUE THREAD

**Issue by Eversor** [jamesmontemagno/Xamarin.Plugins#215]
Permissions uses C# 6 features, unable to build in Xamarin Studio.

**Comment by martijn00** [comment]
Update to the latest stable and you'll be able to build. The release notes for this are available here: https://releases.xamarin.com/stable-release-cycle-6-service-release-1/

**Comment by jamesmontemagno** [comment]
Yes, you must have VS 2015 or the latest Xamarin Studio sorry.
