### ISSUE TITLE
Could not load type 'Android.OS.BaseBundle' from assembly 'Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'.

### ISSUE THREAD

**Issue by andrewSvsg** [jamesmontemagno/Xamarin.Plugins#218]
I created new project and added Xam.Plugin.Media via nuget

 private async void RecordVideo(object sender, System.EventArgs e)
        {
            if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
            {
                System.Console.WriteLine("No Camera :( No camera available.", "OK");
                return;
            }

            var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
                {
                    Directory = "Sample",
                    Name = "test.jpg"
                });

            if (file == null)
                return;

            System.Console.WriteLine("File Location:"+file.Path);
        }

I got all time this exception when try to open 
Could not load type 'Android.OS.BaseBundle' from assembly 'Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'.

**Comment by jamesmontemagno** [comment]
Are you compiling against API 23?

**Comment by aconte80** [comment]
What about using it with API 19? For me it's mandatory to be compatible with that API level.
I set "General -> TargetFramework = Android 4.4 (KitKat)", Minimum Android version = 19 and Target Android Version = 23.. it compiles but at runtime it doesn't works.

**Comment by jamesmontemagno** [comment]
It should look something like:
![image](https://cloud.githubusercontent.com/assets/1676321/13535903/acc48fd0-e1f1-11e5-8fd5-7141b87a7c93.png)

**Comment by aconte80** [comment]
It works perfectly! 
I (wrongly) think that if I have a device with Android 4.4.2 I must select TargetFramework ("compile using Android version") = Android 4.4.. 
After choosing "Android 6.0" as target it works also on 4.4.2 device!
Thanks!
