### ISSUE TITLE
Connectivity Plugin - List of Available Wi-Fi Details

### ISSUE THREAD

**Issue by KathirveluM** [jamesmontemagno/Xamarin.Plugins#221]
Hi Team,

We are using the [Connectivity Plugin](https://github.com/jamesmontemagno/Xamarin.Plugins/tree/master/Connectivity) for finding the Network Connectivity of Mobile. 
In one of our scenario, we need to find the mobile is connected with our specified Wi-Fi.

**How to find the list of available Wi-Fi details like (Name , Mac Address and etc..,)?**

**Comment by jamesmontemagno** [comment]
This is not currently available, but a good feature request.

**Comment by jamesmontemagno** [comment]
Moved to: https://github.com/jamesmontemagno/ConnectivityPlugin/issues/9
