### ISSUE TITLE
Monitoring significant location changes in iOS

### ISSUE THREAD

**Issue by MatthewGerber** [jamesmontemagno/Xamarin.Plugins#222]
Great work on this plugin!

Any plans to incorporate monitoring of significant location changes for iOS? I didn't find a way to do this.

https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/LocationAwarenessPG/CoreLocation/CoreLocation.html

**Comment by cbartonnh** [comment]
This should do that for you:

Task<bool> StartListeningAsync (int minTime, double minDistance, bool includeHeading = false);

**Comment by MatthewGerber** [comment]
I believe that `StartListeningAsync` implements what the iOS docs call "Starting the Standard Location Service". This is a high-energy approach and works well for cases where accurate, high-resolution location tracking is needed.

However, there is a second approach to location monitoring described in the iOS docs:  "Starting the Significant-Change Location Service". This appears to consume less power and is perfect for my use case.

Third, the iOS docs describe "Deferring Location Updates While Your App Is in the Background".

Are these latter approaches (significant-change monitoring and update deferral) present in this plugin or on the roadmap? I haven't found an indication that they are, but they would be very useful.

**Comment by cbartonnh** [comment]
Sorry, I read too quickly. I though you were just looking for it to limit the number of updates based on the distance. 

I will have to defer to James on whether there are any plans to incorporate this feature.

**Comment by MatthewGerber** [comment]
@jamesmontemagno What do you think about this? From an energy conservation perspective it would probably be a compelling enhancement. Thoughts?

**Comment by jamesmontemagno** [comment]
Ideally, what we could do is add an enum that is passed in when you start listening if that lets you toggle which one you want. I have added it as a feature request, you are free to work on it and send a pull request.

**Comment by MatthewGerber** [comment]
Sure, I'll take a crack at it.

**Comment by jamesmontemagno** [comment]
Test this out: https://www.nuget.org/packages/Xam.Plugin.Geolocator/3.1.0-beta1 made some changes to the code, but just about the same

**Comment by MatthewGerber** [comment]
@jamesmontemagno Testing the beta now. Will post back.
