### ISSUE TITLE
Scrollview content exceed in xamarin form android

### ISSUE THREAD

**Issue by ibrahimAJ** [jamesmontemagno/Xamarin.Plugins#223]
The list in the scrollview is exceeding the stack layout .By using heightrequest exceed of data is solved but scrolling functionality not working.so how can i resolve this situation,actually i need to keep a list of buttons with scroll in a layout without exceeding the bounds of the layout.it is exceeding the whole page also while scrolling.

**Comment by jamesmontemagno** [comment]
I am not sure what you are asking, this is for help with Plugins that I work on. Please head over to http://forums.xamarin.com for community support.
