### ISSUE TITLE
Permission plugin always return status as Granted even the permission is explicitly turn off android 6.0

### ISSUE THREAD

**Issue by softsan** [jamesmontemagno/Xamarin.Plugins#224]
Hi James,

I am using Xamarin.Forms and try to use Permission plugin for asking user to provide access of various permission like Camera, Contacts, SMS etc. which are used by my application.

However, I always get CrossPermissions.Current.CheckPermissionStatusAsync as PermissionStatus.Granted. I explicitly revoke(turn off) the permission from App Permission on my marshmallow device, but still the CheckPermissionStatusAsync method returns granted.

Also,  specified all permission in android manifest file.

Is there anything i am missing?

Thanks.

**Comment by jamesmontemagno** [comment]
Are you targeting API 23 and compiling against API 23?

**Comment by softsan** [comment]
yes this is my android manifest settings:
<uses-sdk android:minSdkVersion="16" android:targetSdkVersion="23" />

**Comment by jamesmontemagno** [comment]
Do you have a sample you can share as I am using this currently and so are others just fine. What permissions are you setting in the manifest? Which device are you trying it on?

**Comment by softsan** [comment]
Following permissions are defined in my manifest file:
`<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.CAMERA" />
	<uses-permission android:name="android.permission.CAPTURE_AUDIO_OUTPUT" />
	<uses-permission android:name="android.permission.CAPTURE_VIDEO_OUTPUT" />
	<uses-permission android:name="android.permission.READ_CALENDAR" />
	<uses-permission android:name="android.permission.READ_CONTACTS" />
	<uses-permission android:name="android.permission.READ_OWNER_DATA" />
	<uses-permission android:name="android.permission.RECORD_AUDIO" />
	<uses-permission android:name="android.permission.WRITE_CALENDAR" />
	<uses-permission android:name="android.permission.WRITE_CONTACTS" />
	<uses-permission android:name="android.permission.WRITE_SETTINGS" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
	<uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
	<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
	<uses-permission android:name="android.permission.PERSISTENT_ACTIVITY" />
	<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
	<uses-permission android:name="android.permission.READ_SMS" />
	<uses-permission android:name="android.permission.RECEIVE_MMS" />
	<uses-permission android:name="android.permission.RECEIVE_SMS" />`

I can't share the sample as i am trying it with my actual project. But i can share the method.I have define a helper class called "PermissionHelper" and defined a method :
`
public  static async Task CheckMarshmallowPermission(Permission permissionType)
        {
            
            StringBuilder msg = new StringBuilder();
            msg.AppendLine("Permission denied for ");
            bool isDenied = false;

            var status = PermissionStatus.Unknown;
          
            var permissionStatus = PermissionStatus.Unknown;
            permissionStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(permissionType);
	    if (permissionStatus != PermissionStatus.Granted) //This always return Granted even if i explicitly revoke from device

            {
                var results = await CrossPermissions.Current.RequestPermissionsAsync(permissionType);
                status = results[permissionType]; 
                if (status != PermissionStatus.Granted)
                {
                    msg.AppendLine(permissionType.ToString());
                    isDenied = true;
                }
            }

            if (isDenied)
            {
                await App.Instance.MainPage.DisplayAlert("Permission Denied", msg.ToString(), "OK");
            }
        }
`

following is a call of above method which i used to check permission on Marshmallow.
`PermissionHelper.CheckMarshmallowPermission(Permission.Camera);`

Similarly i have different place in app from where i need to check/request permission for different action.
Also override following method in MainActivity.cs:

` public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
        {
            PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }`

I have a Motorola G3(3rd Generation) - Android 6.0 device.

Hope this helps.
Thanks.

**Comment by jamesmontemagno** [comment]
I just ran your code on my physical Nexus 6P and it worked like a charm and returned Denied and then prompted correctly.  Are you on an early dev build of 6.0?

here is my code
[PermissionSample.zip](https://github.com/jamesmontemagno/Xamarin.Plugins/files/136634/PermissionSample.zip)

**Comment by softsan** [comment]
Not sure, but I think i may have an early dev build of 6.0 so i have  upgrade to official 6.0 and its working fine now. 

Thanks a lot for your support. Your plugins are life saver!

Thanks.

**Comment by jamesmontemagno** [comment]
Absolutely! Yeah the early previews and some emulators it doesn't work on as it isn't fully implemented. cheers

**Comment by kentliaw** [comment]
Hi James,

Is the permission plugin only support android device with android 6.0 ? I tested on physical device (not 6.0 version) and i am facing this issue.

**Comment by jamesmontemagno** [comment]
@kentliaw Android permissions only prompt you on 6.0+ https://blog.xamarin.com/requesting-runtime-permissions-in-android-marshmallow/

**Comment by kentliaw** [comment]
Thanks @jamesmontemagno for the info. Will read it up =)

Keep up the good works.

**Comment by ilber** [comment]
Hi to all,
The main issue here is that if on XS you have the option "Target Android version" set to automatic (use target framework version (API 23) the Manifest file will not contain any reference about the target SDK. You should always explicitly set the target framework to 23. I see this as a bug on XS and not in the plugin.
Servus Xamarin aus München.

**Comment by snekbaev** [comment]
@ilber indeed. I was wondering why the following example didn't work as expected: https://blog.xamarin.com/requesting-runtime-permissions-in-android-marshmallow 
I have minimum API level 16 and "compile using" - the latest, yet Nexus 5 with Marshmallow doesn't ask for any permissions at all, even when I disable some permissions via Settings -> Apps ```ContextCompat.CheckSelfPermission``` is still returning granted. Moreover, following added to confusion - http://stackoverflow.com/questions/33407250/checkselfpermission-method-is-not-working-in-targetsdkversion-22

Eventually, explicitly setting the target Android version fixed the issue.

@jamesmontemagno maybe update the article to mention that? :)

Thank you!

**Comment by ilber** [comment]
@snekbaev Probably Xamarin is doing something wrong. It checks the target android version only and I don't know why.

**Comment by jamesmontemagno** [comment]
It says it specifically in the readme :)

**Comment by snekbaev** [comment]
@jamesmontemagno yeah, I meant the article. I was doing Xamarin Android and following those instructions :)

**Comment by jamesmontemagno** [comment]
:) yup updated the article you linked to
