### ISSUE TITLE
Device specific id is not static

### ISSUE THREAD

**Issue by Sudhacc** [jamesmontemagno/Xamarin.Plugins#225]
I am using Device info to get Unique device id for both android and iOS. When checking in iOS the unique id is keep on changing per installation. Am i missing something or this is how it will working in iOS? Please guid me.

**Comment by jamesmontemagno** [comment]
On iOS you can not get a unique device ID, only a unique app install ID for the app: https://github.com/jamesmontemagno/Xamarin.Plugins/issues/163
