### ISSUE TITLE
Remove permission

### ISSUE THREAD

**Issue by acaliaro** [jamesmontemagno/Xamarin.Plugins#227]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [ ] Bug
- [X] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [ ] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin: 1.1.7
Device Tested On:
Simulator Tested On: Android 5.1.51

I Would like to know if there is the possibility to "remove" a permission with code.
### Steps to reproduce the Behavior

**Comment by jamesmontemagno** [comment]
To revoke a permission that had already been granted by the user? I don't
think any of the operating systems support that.

**Comment by acaliaro** [comment]
Thanks James. Another question... I would like to test your plugin in a Android 6 simulator but seems that Xamarin android player does not have android 6. How can I do this test without a real device?

**Comment by cbartonnh** [comment]
You could use *gulp* the standard Android SDK simulators…

You could also try Genymotion. They have them as well and I bet they will run better than the stock ones.

**Comment by jamesmontemagno** [comment]
Yup, I would use the x86 Google emulators. However, permissions on
emulators aren't a one to one sometimes with the real device, so be sure to
test it on an official emulator.

**Comment by acaliaro** [comment]
@jamesmontemagno can you explain 'official emulator '?

**Comment by jamesmontemagno** [comment]
Official Google emulators.

**Comment by acaliaro** [comment]
Thanks @jamesmontemagno I have found an Android 6 device. Your plugin works, thanks
Alessandro
