### ISSUE TITLE
iOS: When Mobile Data enabled, check if app is set to allow data

### ISSUE THREAD

**Issue by johnhearfield** [jamesmontemagno/Xamarin.Plugins#229]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [x] Bug
- [x] Feature Request

Which plugin does this impact:
- [ ] Battery
- [x] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [ ] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin: 2.1.1
Device Tested On: iPhone 6S
Simulator Tested On: N/A

### Expected Behavior
The app should not allow data connections when Mobile Data is on (no WIFI) AND the app has data disabled
### Actual Behavior
The app still uses data even if the app has data disabled in the settings

### Steps to reproduce the Behavior
Do a http request with only 3G/4G enabled and the app is disabled in the settings. Watch the usage go up.

**Comment by jamesmontemagno** [comment]
Connectivity only checks connections. You can disable functionality in your
app to not make the request. I am confused by what the claimed issue or
request is.

**Comment by johnhearfield** [comment]
Ah okay.
I request that there is also a check for seeing if the app has actually been enabled to use mobile data on iOS

**Comment by jamesmontemagno** [comment]
Ahhh gotcha interesting. Let me think about it.

**Comment by johnhearfield** [comment]
Cheers mate :+1:

**Comment by jamesmontemagno** [comment]
I think this is out of the scope for the plugin.
