### ISSUE TITLE
Status bar text changes color on iOS when picking photo

### ISSUE THREAD

**Issue by steckums** [jamesmontemagno/Xamarin.Plugins#230]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [x] Bug
- [ ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [x] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin: 2.3.0
Device Tested On: iPad
Simulator Tested On: n/a

### Expected Behavior
Status bar text stays the same initially set by the app.

### Actual Behavior
Status bar changes to black text when picking a picture.

### Steps to reproduce the Behavior
Set the status bar text to white.
Have a buttons select a photo. 
Select "Camera Roll"
The status bar text is now black.

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/MediaPlugin#23
