### ISSUE TITLE
App shoots back when camera orientation is changed

### ISSUE THREAD

**Issue by MoffApps** [jamesmontemagno/Xamarin.Plugins#235]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [ x] Bug
- [ ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [ x] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin:Xam.Plugin.Media.2.3.0
Device Tested On:Oneplus x
Simulator Tested On:

### Expected Behavior
When in camera view and it is rotated everything works as normal
### Actual Behavior
Where camera is rotated and picture taken. App shoots back to start screen
### Steps to reproduce the Behavior
Launch camera in portrait, switch to landscape, take photo and ok it

**Comment by jamesmontemagno** [comment]
Can you try https://www.nuget.org/packages/Xam.Plugin.Media/2.4.0-beta3 I think it is fixed there.

**Comment by rjcollingham** [comment]
I get exactly the same behaviour with beta 3. It seems after taking a number of photos the app just isn't resumed after the camera activity and you get thrown back to the start screen.

I don't think it's anything to do with the rotation.

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/MediaPlugin#22
