### ISSUE TITLE
Multi-Language support

### ISSUE THREAD

**Issue by qjdev** [jamesmontemagno/Xamarin.Plugins#238]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [ ] Bug
- [x] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [x] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin:
Device Tested On:
Simulator Tested On:

### Expected Behavior
Can I change the language(or the text) in the take photo page?

### Steps to reproduce the Behavior

**Comment by jamesmontemagno** [comment]
Taking or picking photos simply launches the default camera application to take the picture so you do not have control over this.
