### ISSUE TITLE
Adding new key value works ONLY in AppDelegate.FinishedLaunching in MONOTOUCH

### ISSUE THREAD

**Issue by akrambek** [jamesmontemagno/Xamarin.Plugins#24]
I followed readme instruction and used _SettingsStarted.txt as an example. But it works only AppDelegate.FinishedLaunching when I call Settings.UserName = "demo".

For example, If I call Settings.UserName = "demo1" in any other view controller and then use it in some classes. I don't see that UserName value has changed.

Can you please help me with this.

**Comment by jamesmontemagno** [comment]
Settings work anywhere in any viewcontroller. Please try out this sample: https://github.com/jamesmontemagno/Xamarin.Plugins/tree/master/Settings/Component/SettingsPlugin/samples

**Comment by akrambek** [comment]
yeah it was my bad! Thanks
