### ISSUE TITLE
[Win 8.1] Geolocator and Permissions doesn't ask the user ==> can't get position

### ISSUE THREAD

**Issue by quentinR0bert** [jamesmontemagno/Xamarin.Plugins#241]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [x] Bug
- [ ] Feature Request

Which plugin does this impact:
- [x] Geolocator
- [x] Permissions

Version Number of Plugin: 3.0.4
Device Tested On: Surface
Simulator Tested On: PC on Win10

### Expected Behavior
For the plugin Geolocator get the position
For the plugin Permission ask for the permission for Location
### Actual Behavior
**Geolocator**: 

- On Surface (Windows 8.1) : the system return a System.InvalidOperationException when we ask for the location
Stack : 
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at SdkProtoXF.GeolocatorTool.<GetPosition>d__1.MoveNext()

- On PC (Windows 10) : the system return a Plugin.Geolocator.Abstractions.GeolocationException with the message "Unauthorized"
Same Stack

- The two : the attributes IsGeolocationAvailable and IsGeolocationEnabled return true even if the app doesn't have the permission or if it's disabled.

**Permission**:
On surface and PC the method CheckPermissionStatusAsync return "Granted" for Location even if the system never ask for or if it's disabled in the parameters.
And the method RequestPermissionsAsync(Permission.Location) does nothing.

**Finaly** i know all this troubles it's because the system have to ask for the permission the first time that a geolocator is called, but the Geolocator or Permission Plugin doesn't done it. The user have to manually set in the parameters. And we can't make the prompt for asking, it's a nativ one called by the system.

### Steps to reproduce the Behavior
Launch a app and called for GetPositionAsync or CheckPermissionStatusAsync or RequestPermissionsAsync

**Comment by jamesmontemagno** [comment]
What type of app are you creating? WinPhone 8.1 RT or Silverlight?


The permissions plugin currently have a blank implementation for all Windows Platforms and will always return Granted.

Did you specify: ID_CAP_LOCATION ?

I am using the code currently in Windows 10 and it prompts right away from the Geolocator code.

**Comment by quentinR0bert** [comment]
I'm on a Windows 8.1 (Moder UI style) project

okay i understand for the permissions plugin and will wait for it =).

Yes i haved specify  the Location capacity in the manifest

**Comment by jamesmontemagno** [comment]
Is it a RT or a Silverlight project?

**Comment by quentinR0bert** [comment]
It's a RT project
