### ISSUE TITLE
Geolocator 4.0 Changes

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/Xamarin.Plugins#243]
Breaking Changes:

- [ ] Adjust all times to TimeSpan
- [ ] Introduce better listening settings
- [ ] Change IsGeolcationAvailable and IsGeoloationEnabled to Task<bool>
- [ ] Add request permission Async
- [ ] Remove Desired Accuracy & bundle into PositionSettings for GetPositionAsync 
- [x] Add Activity Type

**Comment by MatthewGerber** [comment]
Also adds deferral of location update delivery.

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/GeolocatorPlugin#8
