### ISSUE TITLE
Connectivity plugin not working

### ISSUE THREAD

**Issue by ibrahimAJ** [jamesmontemagno/Xamarin.Plugins#247]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [] Bug
- [ ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [x] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [ ] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin:v4.0.30319
Device Tested On:
Simulator Tested On:Android 5.0.1(API 21)

### Steps to reproduce the Behavior

**Comment by jamesmontemagno** [comment]
Can not reproduce
