### ISSUE TITLE
'ConnectivityChanged' is not fired when wifi connects with active data - android only

### ISSUE THREAD

**Issue by rayhan990** [jamesmontemagno/Xamarin.Plugins#248]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [x ] Bug
- [ ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [x ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [ ] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin: 2.1.2
Device Tested On: Samsung S5
Simulator Tested On: 

### Expected Behavior
Fire ConnectivityChanged event
### Actual Behavior
No event is fired
### Steps to reproduce the Behavior

1) Disable wifi connection
2) Enable if not already enabled the data connection
3) enable wifi

For the first 2 points the 'ConnectivityChanged' event is being fired but not for the last point.
The issue was detected only on Android and not on IOS.

**Comment by jamesmontemagno** [comment]
This is as expected

Have you tried airplane mode. According to android it has not actually lost connectivity.

**Comment by rayhan990** [comment]
Hi James,

No, I only had my data activated and switching on/off the wifi connection.
It detects when the wifi is off but not when it connects back.

Is it an android issue? I can understand that the connection is not lost but
the type is changed.

**Comment by jamesmontemagno** [comment]
I mostly just listen to what Android tells me so perhaps to android it isn't a connection loss at all.
