### ISSUE TITLE
[Feature Request] Choose album in PickPhotoAsync()

### ISSUE THREAD

**Issue by VincentVanWijk** [jamesmontemagno/Xamarin.Plugins#250]
it would be very nice for me if i could choose an album to load pictures from in PickPhotoAsync() instead of always showing the entire gallery.

**Comment by VincentVanWijk** [comment]
is this even possible?

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/MediaPlugin#20
