### ISSUE TITLE
Error when installed on Xamarin.Droid

### ISSUE THREAD

**Issue by elyfran** [jamesmontemagno/Xamarin.Plugins#252]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [ ] Bug
- [ x] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ x] Geolocator
- [ ] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin: 4.0.0-beta1
Device Tested On: API 23
Simulator Tested On: API 23

### Expected Behavior
Capture the localization

### Actual Behavior
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: Error: Error executing task GenerateJavaStubs: Application cannot have both a type with an [Application] attribute and an [assembly:Application] attribute. (CaseServico.Droid)

### Steps to reproduce the Behavior
Only install plugin in Xamarin.Droid.

When I install the plugin in Xamarin.Droid is generating the following error:
how can I solve this?

**Comment by jamesmontemagno** [comment]
You will need to remove the [assembly:Application] attribute and use the one in MainApplication.cs
