### ISSUE TITLE
[Feature Request] Please add support for monitoring SignificantLocationChanges

### ISSUE THREAD

**Issue by David-Dartand** [jamesmontemagno/Xamarin.Plugins#254]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [ ] Bug
- [x] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [x] Geolocator
- [ ] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin:3.0.4
Device Tested On: iPhone 6s Plus
Simulator Tested On:

### Expected Behavior
Would like GeoLocator to support monitoring SignificantLocationChanges

### Actual Behavior
GeoLocator does not support SignificantLocationChanges

### Steps to reproduce the Behavior
Please add the ability to monitor SignificantLocationChanges in iOS.

**Comment by jamesmontemagno** [comment]
This is already in 4.0.0-beta1, please see other open issues
