### ISSUE TITLE
Connectivity - Would be nice to know which connection the device is actually using

### ISSUE THREAD

**Issue by wpeter-sfdc** [jamesmontemagno/Xamarin.Plugins#255]
This is a 
- [ ] Bug
- [x] Feature Request

Which plugin does this impact:
- [ ] Battery
- [x] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [ ] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin: 2.1.2
Device Tested On: Windows 10 desktop and mobile
Simulator Tested On:

### Feature Request
ConnectionTypes returns a list of active connections, but it would be nice to know which connection is being used for network calls... I'm not sure about other platforms, but for Windows you can get the connection that's being used by calling `NetworkInformation.GetInternetConnectionProfile();`

Can you either order the ConnectionTypes so that the first item is the connection being used or maybe add a new property... I guess this request could get tricky if Android and iOS don't support finding the connection being used.

**Comment by jamesmontemagno** [comment]
Copied to: https://github.com/jamesmontemagno/ConnectivityPlugin/issues/8
