### ISSUE TITLE
Connectivity - Provide a mapping between connection types and bandwidths

### ISSUE THREAD

**Issue by wpeter-sfdc** [jamesmontemagno/Xamarin.Plugins#256]
This is a 
- [ ] Bug
- [x] Feature Request

Which plugin does this impact:
- [ ] Battery
- [x] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [ ] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin: 2.1.2
Device Tested On: Windows 10 desktop and mobile
Simulator Tested On:

### Feature Request
There is a property for ConnectionTypes and a property for Bandwidths, but no mapping between the two... that feature would be nice so that if I need a user to send logs I can detect what connection type they were using and what the bandwidth of that connection was.  This request is related to #255

**Comment by jamesmontemagno** [comment]
Moved to: https://github.com/jamesmontemagno/ConnectivityPlugin/issues/7
