### ISSUE TITLE
Plans/ideas to make geolocator a sticky service on Android?

### ISSUE THREAD

**Issue by kgerken** [jamesmontemagno/Xamarin.Plugins#257]
This is a 
- [ ] Bug
- [x] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [x] Geolocator
- [ ] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

I was wondering if there were any plans to offer the possibility to make the geolocator a sticky service on Android (resulting e.g. in the service being restarted after a device reboot). If otherwise someone has an idea of how to achieve this behavior with the current plugin, I'd be happy to hear about it, too.

**Comment by jamesmontemagno** [comment]
I have thought about this, usually you want to customize and have control of how that works. I think an example is a way to do it to show everyone how to use it. However, the documentation on services is really good and has this exact example.

**Comment by kgerken** [comment]
Thanks, I'll look into that.
