### ISSUE TITLE
Xam.Media - very long time for photo to load (in portrait orientation only)

### ISSUE THREAD

**Issue by 100s** [jamesmontemagno/Xamarin.Plugins#258]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [x ] Bug
- [ ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [x ] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin: 2.4.0 - Beta3
Device Tested On: Samsung Galaxy S5, Samsung Galaxy Note 10
Simulator Tested On:

### Expected Behavior
Photo taken in portrait orientation should load almost immediately.
### Actual Behavior
Photo taken in portrait orientation loads about 5-15 seconds. For photo in panorama orientation it loads immediately. It works correctly in version 2.3.0.
### Steps to reproduce the Behavior
Take a photo in landscape mode
Wait for the result

**Comment by 100s** [comment]
This bug was introduced in 2.4.0 - Beta1

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/MediaPlugin#19
