### ISSUE TITLE
Unable to compile and launch ExternalMaps.sln in Xamarin.

### ISSUE THREAD

**Issue by mmehrle** [jamesmontemagno/Xamarin.Plugins#259]
I am unable to launch and compile the app in Xamarin. Getting the following error:

![2016-03-23_1915](https://cloud.githubusercontent.com/assets/8457499/13995944/d50a1fe8-f12b-11e5-8ba4-996441db8e3a.png)

I'm on the latest version of Xamarin running on OS X El Capitan.

**Comment by jamesmontemagno** [comment]
That is fine it is just a warning that UWP projects can't load. Alpha you can now load
