### ISSUE TITLE
Pick or take photo produces black/empty preview on iOS/Android

### ISSUE THREAD

**Issue by BakDavide** [jamesmontemagno/Xamarin.Plugins#260]
This is a 
- [x] Bug
- [ ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [x] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin: 2.3.0
Device Tested On: iPhone 6S, iPad 2, LG G3 (Android 6)
Simulator Tested On:iPhone 6

### Expected Behavior
After selecting an image from the gallery or take new from camera I view a preview of the selected image (using ImageSource.FromFile(mediaFile.Path))

### Actual Behavior
On iOS after selecting an image from the gallery displays a black preview of the selected image (using ImageSource.FromFile(mediaFile.Path)).
On Android after take picture from camera displays an empty preview of the image (using ImageSource.FromFile(mediaFile.Path)).

### Steps to reproduce the Behavior
With iOS select an image from gallery and use an ImageSource to show the selected image (black preview).
With Androd take a photo from camera and use an ImageSource to show the selected image (empty preview).
The gallery problem is reproduced only on iOS while the camera problem is reproduced only on Android 6 (with my LG G3 with Android 5 the problem does not occur).

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/MediaPlugin#18
