### ISSUE TITLE
GeoLocator StopListeningAsync doesn't stop

### ISSUE THREAD

**Issue by RanaInside** [jamesmontemagno/Xamarin.Plugins#261]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [ x] Bug
- [ ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ x] Geolocator
- [ ] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin:
Last Nuget Stable
Xam.Plugin.Geolocator.4.0.0-beta1

Device Tested On: iPhone 6, 6S (ios 8.2, ios9.x)
Simulator Tested On: iPhoneSimulator 8.2

### Expected Behavior
expecting success from method StopListeningAsync

### Actual Behavior
returns false and doesn't stop listening

### Steps to reproduce the Behavior
1. no location set in info.plist for UIBackgroundModes
2. StartListening on PageAppear method (returns true)
3. StopListening on PageDisappear method (returns false)

Note: I am calling it on Main thread as await; pretty sure I have tried on background thread as well.

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/GeolocatorPlugin#7
