### ISSUE TITLE
Media - Camera images taken in portrait behaving weird.

### ISSUE THREAD

**Issue by highplains** [jamesmontemagno/Xamarin.Plugins#263]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [X] Bug
- [ ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [X ] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin: 2.4.0-beta3
Device Tested On: iPhone 6s+
Simulator Tested On: iPhone 6s

### Expected Behavior
Take a photo in portrait, photo is saved/displays in correct dimensions.

### Actual Behavior
Photo looks like its been stretched into landscape

### Steps to reproduce the Behavior
Take a photo in portrait, same photo in landscape. Load in to a ImageView AspectFit

Stable Version.
![screen shot 2016-03-28 at 3 38 57 pm](https://cloud.githubusercontent.com/assets/1825076/14091379/2b9e11f0-f4fd-11e5-9d95-844ee1d8c13e.png)

Latest Beta
![screen shot 2016-03-28 at 3 39 06 pm](https://cloud.githubusercontent.com/assets/1825076/14091380/2f50cce8-f4fd-11e5-8eaa-7e24806a89d9.png)

**Comment by lima66** [comment]
I have the same problem the image are rotate of 90° with Iphone 6 os: 9.3 , Iphone 5 os: 9.2 and i have update the plugin to the beta 3

**Comment by highplains** [comment]
bump

**Comment by highplains** [comment]
Had to downgrade to last stable release to get this to work properly. But now the android rotation is messed up again.

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/MediaPlugin#17
