### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by svandelaarschot** [jamesmontemagno/Xamarin.Plugins#267]
got this weird exception 
code im using below:

            CrossConnectivity.Current.ConnectivityChanged += (sender, args) =>
            {
                try
                {
                    if (!args.IsConnected)
                    {
                        HasNetwork = false;
                    }
                    else
                    {
                        HasNetwork = true;
                    }
                }
                catch (Exception ex)
                {
                    Debug.WriteLine(ex.ToString());
                }
            };

'System.NotImplementedException' in Plugin.Connectivity.DLL
on every platforms

**Comment by svandelaarschot** [comment]
Fixed by using version 2.0.0

**Comment by imicer** [comment]
You need add Nuget packages to your Android or iOS project.
