### ISSUE TITLE
Connectivity sample crashes when in aeroplane mode

### ISSUE THREAD

**Issue by readiescards** [jamesmontemagno/Xamarin.Plugins#27]
James, some great plugins thanks.

I ran the Connectivity sample
from Xamarin.Plugins\Connectivity\Common\ConnectivityPlugin\samples
using Android 21 on my Nexus 5 (built in XS 5.7) and if I put my phone in aeroplane mode and then press the Test connectiion button the app disappears (crashes).

**Comment by jamesmontemagno** [comment]
Fixed, and pushed out a build: 1.0.1

Component has also been submitted.

Thanks!

**Comment by readiescards** [comment]
Wow that was quick!
thanks
Paul

On 12 February 2015 at 22:59, James Montemagno <notifications@github.com>
wrote:

> Closed #27 <https://github.com/jamesmontemagno/Xamarin.Plugins/issues/27>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jamesmontemagno/Xamarin.Plugins/issues/27#event-235055513>
> .
>



-- 
Lincolnshire Holiday Cottages <http://rigsbywoldholidaycottages.uk/>

**Comment by readiescards** [comment]
Unfortantely IsRemoteReachable no longer works.  (Again testing with the sample v1.0.0.3 finds my server while version 1.0.1 does not - and crashes my app though oddly not the sample)

**Comment by readiescards** [comment]
Ignore that Xamarin Android player got mixed up (I think) reboot my PC and all ok
