### ISSUE TITLE
Is it possible to use this plugin (Connectivity) to monitor the network change background? 

### ISSUE THREAD

**Issue by xinmeng1** [jamesmontemagno/Xamarin.Plugins#270]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [ ] Bug
- [x] Feature Request

Which plugin does this impact:
- [ ] Battery
- [x] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [ ] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin:
Device Tested On:
Simulator Tested On:

### Expected Behavior

Is it possible to use this plugin (Connectivity) to monitor the network change background? 
I had implement this function on Android with Broadcast Receiver, and I am worrying for the iOS.
According to some material, it said I can use the location to implement the long time running task background. So, is it possible to use this plugin to do this job?

### Steps to reproduce the Behavior

**Comment by jamesmontemagno** [comment]
On android it receives it automatically via the broadcast receiver and then any other network change on iOS it gets in the background too. If your app goes into the background and comes to the foreground simply check the isconnected again.

Else subscribe to events in the App Delegate.
