### ISSUE TITLE
Position.Timestamp wrong on iOS

### ISSUE THREAD

**Issue by DELUXEnized** [jamesmontemagno/Xamarin.Plugins#271]
This is a 
- [x] Bug

Which plugin does this impact:
- [x] Geolocator

Version Number of Plugin: 3.0.4
Device Tested On: iPhone 6 iOS 9.3
Simulator Tested On:

### Expected Behavior
Position.Timestamp should return correct UTC timestamp
### Actual Behavior
Position.Timestamp returns wrong UTC time
### Steps to reproduce the Behavior

[Bug Location in Code](https://github.com/jamesmontemagno/Xamarin.Plugins/blob/3fe065b06c39a53354fe4f99f9bda85765778f53/Geolocator/Geolocator/Geolocator.Plugin.iOS/GeolocatorImplementation.cs#L356)

The ToDateTime() extension method produces a DateTime with an Kind.Unspecified. Calling the ToUniversalTime() method will assume Kind Local and convert the timestamp to UTC. [MSDN Link](https://msdn.microsoft.com/en-us/library/system.datetime.touniversaltime(v=vs.110).aspx)

Use the static SpecifyKind method instead [MSDN Link](https://msdn.microsoft.com/en-us/library/system.datetime.specifykind(v=vs.110).aspx)

**Comment by kgerken** [comment]
@lothrop already created a pull request for this issue, see #266.

**Comment by DELUXEnized** [comment]
Did not see that... Thanks.
