### ISSUE TITLE
Xam.Geolocator does not work on iOS 9.3

### ISSUE THREAD

**Issue by jj09** [jamesmontemagno/Xamarin.Plugins#277]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [x] Bug
- [ ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [x] Geolocator
- [ ] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin: 4.0.0-beta2
Device Tested On: iPhone 5s (working with iOS 8.x, does not after update to 9.3.1), Apple Store (failed certification on iOS 9.3.1)
Simulator Tested On: iPhone 6S

### Expected Behavior
var position = await locator.GetPositionAsync (timeoutMilliseconds: 100000); returns location

### Actual Behavior
fails with System.NullReferenceException thrown inside plugin code

### Steps to reproduce the Behavior
try to get location with

var position = await locator.GetPositionAsync (timeoutMilliseconds: 100000);

on iOS 9.3.x with Xam.Geolocator v4.x

**Comment by jamesmontemagno** [comment]
I do not believe the beta2 of 4.0 is ready yet for production at all. it is still a WIP. Thanks for the feedback though and will take a look.

**Comment by MatthewGerber** [comment]
This works for me using beta4.

**Comment by jamesmontemagno** [comment]
@jj09 can you validate?

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/GeolocatorPlugin#6
