### ISSUE TITLE
Media Plugin 2.4.0-pre is not rotating or resizing images in android due to Out of Memory Exceptions

### ISSUE THREAD

**Issue by dhaligas** [jamesmontemagno/Xamarin.Plugins#279]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [x] Bug
- [ ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [x] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin: 2.4.0-pre3
Device Tested On: Samsung Galaxy S5
Simulator Tested On:

### Expected Behavior
I am taking a photo with the photo size of small and I expect the result to be rotated and resized.

### Actual Behavior
When debugging the MediaAndroidTest app I am getting Out of Memory exceptions when it tries to FixOrientationAync and ResizeImage

### Steps to reproduce the Behavior
Run MediaAndroidTest on Debug on Device
Take Photo

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/MediaPlugin#15
