### ISSUE TITLE
ExternalMaps/Android: double toString() and current culture setting

### ISSUE THREAD

**Issue by IlSocio** [jamesmontemagno/Xamarin.Plugins#28]
I just noticed an issue in the Android version... 
The latitude / longitude values are converted tostring using the current culture settings and in some country the decimal separator "." will be replaced with "," causing a wrong format in the intent string, so googlemaps will not find any results...

**Comment by IlSocio** [comment]
I suppose it can be fixed by just wrapping the string values inside the < and > signs...
geo:<lat>,<long>

**Comment by jamesmontemagno** [comment]
I will implement this with the <lat>, <long> and that should be the correct fix for sure.

**Comment by jamesmontemagno** [comment]
Fixed in latest version. Thanks.
