### ISSUE TITLE
IsRemoteReachable don't work on iOS

### ISSUE THREAD

**Issue by dcasbonne** [jamesmontemagno/Xamarin.Plugins#281]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [ x] Bug
- [ ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [x ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [ ] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin: 2.1.2
Device Tested On: iPad Air 2 on iOS 9.3.1
Simulator Tested On: iPhone 6s iOS 9.3

### Expected Behavior

Working method :)

### Actual Behavior

When trying to reach "google.ca" result is always false. In Android everything is OK.

### Steps to reproduce the Behavior

When using this code :
```
bool res = await CrossConnectivity.Current.IsRemoteReachable("google.ca");
```
res is always false. I tried with a high timeout, no changes.

Thanks!

**Comment by jamesmontemagno** [comment]
I have tested this out in 2.2.1 and working great.
