### ISSUE TITLE
ConnectionTypes doesn't contains all connections

### ISSUE THREAD

**Issue by dcasbonne** [jamesmontemagno/Xamarin.Plugins#282]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [ ] Bug
- [ x] Feature Request

Which plugin does this impact:
- [ ] Battery
- [x ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [ ] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin: 2.1.2
Device Tested On: Nexus 5 Android 6.0.1
Simulator Tested On:

### Expected Behavior

When cellular connection is active AND wifi connection too, ConnectionTypes should contains the 2 types.
By default Android use wifi connection if the 2 are active so I don't really know if it's possible for you to know that but if you could it would be great !

### Actual Behavior

Only Wifi is present in ConnectionTypes

### Steps to reproduce the Behavior

Activate cellular and wifi connection on a device.

Thanks !

**Comment by tomridl** [comment]
On IOS 9.3.2, when both Wifi and Cellular are enabled, the ConnectionType contains only the "Other" type, and doesn't contain either Wifi or Cellular. When in Flight mode, with Wifi on, the ConnectionType also only contains "Other" and doesn't contain "Wifi". If just a cellular connection is active, the ConnectionType correctly shows "Cellular". Tested on iPhone 5.

Example: Airplane mode on, Wifi On
![img_2499](https://cloud.githubusercontent.com/assets/2032782/16272066/a7e8257e-389c-11e6-8fd1-391a45bebbbf.jpg)

Example: Cellular and Wifi Connected
![img_2500](https://cloud.githubusercontent.com/assets/2032782/16272096/c50649f6-389c-11e6-9d99-f6bb849d31e0.jpg)

**Comment by jamespettigrew** [comment]
I'm having the same issue as @tomridl when using version 2.2.2, reverting to 2.1.2 resolves it.

**Comment by jamesmontemagno** [comment]
Moved to: https://github.com/jamesmontemagno/ConnectivityPlugin/issues/6
