### ISSUE TITLE
Android 6.0 only Media issue

### ISSUE THREAD

**Issue by michaeldimoudis** [jamesmontemagno/Xamarin.Plugins#283]
This is a 
- [x] Bug
- [ ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [x] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin: latest
Device Tested On: Android 6 devices
Simulator Tested On: Android 6

### Expected Behavior
When I click on a button to load a photo gallery, I get asked for permission, and the photo gallery should pop up.

### Actual Behavior
After you give permission for Android 6 to access the camera, the photo gallery doesn't pop up. Even after you press the button multiple times. If you navigate away from the page, and go back in to the page with the button to pop up the gallery, it then starts working as expected and pops up.

### Steps to reproduce the Behavior
See above.

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/MediaPlugin#14
