### ISSUE TITLE
Testing the ViewModels, how can I mock the SettingsRepository?

### ISSUE THREAD

**Issue by fcogutierrez** [jamesmontemagno/Xamarin.Plugins#289]
**Which plugin does this impact:**
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [ ] Media
- [ ] Permissions
- [x] Settings
- [ ] Text To Speech
- [ ] Vibrate

**Question:**

How can I mock my static **AppSettings** class in my Unit tests?

I am doing this:

    public static class AppSettings
    {
        private const string EmailKey = "email_key";

        public static string Email
        {
            get { return SettingsRepository.GetValueOrDefault<string>(EmailKey, string.Empty); }
            set { SettingsRepository.AddOrUpdateValue<string>(EmailKey, value); }
        }

        private static ISettings SettingsRepository
        {
            get { return CrossSettings.Current; }
        }
    }

Thanks a lot.

**Comment by jamesmontemagno** [comment]
You would just need to implement a different version of ISettings and then return it when you want to use that mock.

**Comment by fcogutierrez** [comment]
@jamesmontemagno, how can I set my **ISettings** implementation instead of using **CrossSettings.Current**?

        private static ISettings SettingsRepository
        {
            get { return CrossSettings.Current; }
        }

**Comment by jamesmontemagno** [comment]
Simply implement it in a new class and then return it?

**Comment by fcogutierrez** [comment]
Yes, but how can I replace the CrossSettings.Current by my implementation?

**Comment by jamesmontemagno** [comment]
```
private static ISettings SettingsRepository
    {
        get { return new YourImplementation(); }
    }
```

**Comment by fcogutierrez** [comment]
Ok James, so I have my **AppSettings** class and my **AppSettingsMock** class, but in my ViewModel (subject under test) I am doing:
 
            //some operations...
            Email = AppSettings.Email;
            Password = AppSettings.Password;
            //more operations...

**Comment by fcogutierrez** [comment]
Ok James, so I have my **AppSettings** class and my **AppSettingsMock** class:

- In the **AppSettings** I am using the CrossSettings.Current implementaiton.
- In the **AppSettingsMock** I am using a custom impolementation of **ISettings** (new MockSettingsRepository()).

However, in my ViewModel (subject under test) I am doing:
 
            //some operations...
            Email = AppSettings.Email;
            Password = AppSettings.Password;
            //more operations...

And my question is...how can I use my **AppSettingsMock** instead of the **AppSettings** class?

Thank you a lot for your help mr James :+1: :+1:

**Comment by yairsz** [comment]
@fcogutierrez I believe you need to setup a form of iOC. For example in MVVMCross you could do this:

    public static string Email
    {
        get { 
             var settingsSvc = Mvx.Resolve<ISettingsService>();
             return settingsSvc.GetValueOrDefault<string>(EmailKey, string.Empty); 
    }
        set { 
             var settingsSvc = Mvx.Resolve<ISettingsService>();
             settingsSvc .AddOrUpdateValue<string>(EmailKey, value); 
    }
    }
