### ISSUE TITLE
Please add support for iOS Unified API (Settings Plugin for Xamarin And Windows)

### ISSUE THREAD

**Issue by tblion** [jamesmontemagno/Xamarin.Plugins#29]
Hi,

Your plugin "Settings Plugin for Xamarin And Windows" is not compatible with Xamarin iOS Unified API.

Can you update your project ?

Thank you

**Comment by tblion** [comment]
My apologies, my nuget package was not updated... And Nugget don't show the update...

**Comment by jamesmontemagno** [comment]
I wish NuGet in VS would update to have this feature :( One day. We have that feature in XS which is very nice.
