### ISSUE TITLE
Thumbnails are not displayed when running on iPads (at iPhone resolution) 

### ISSUE THREAD

**Issue by dzolnjan** [jamesmontemagno/Xamarin.Plugins#290]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [x] Bug
- [ ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [x] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin:
Device Tested On: none
Simulator Tested On: iPad Air, iPad Retina, iPad Pro

### Expected Behavior
When running on iPad (at iPhone resolution) then photo picker is not displaying album and photo thumbnails (only placeholders)

This functionality is required for apps that are targeting only iPhones.

2.10 - iPhone Apps must also run on iPad without modification, at iPhone resolution, and at 2X iPhone 3GS resolution 

### Actual Behavior
Album and Photo thumbnails are displayed.

### Steps to reproduce the Behavior
Simply start debugging MediaTest.iOS project with any of iPads simulators listed above and tap on 'Pick P' option.

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/MediaPlugin#12
