### ISSUE TITLE
WinPhone project fails on physical device when updating Connectivity to 2.1.2.0

### ISSUE THREAD

**Issue by biste5** [jamesmontemagno/Xamarin.Plugins#291]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [X] Bug
- [ ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [X] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [ ] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin: 2.1.2.0
Device Tested On: Lumia 925 WinPhone 8.1 (Issue present)
Simulator Tested On: WinPhone 8.1 , WinMobile 10 (Issue NOT present)

### Expected Behavior
The App should start normally, Connectivity plugin should be initialized

### Actual Behavior
The App crashes on start (Connectivity is initialized in App class constructor)
Enabling 'break on every exception' via Exception Settings of the IDE, I can extract the real exception

> Exception thrown: 'System.IO.FileLoadException' in MyApp.Mobile.WinPhone.ni.EXE
> Additional information: Could not load file or assembly 'Plugin.Connectivity.Abstractions,
> Version=2.1.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. 
> The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

### Steps to reproduce the Behavior

- Install or update package in your solution to 2.1.2.0
- Deploy to a physical WinPhone 8.1 devce (on simulators issue doesn't occur)

**Comment by jamesmontemagno** [comment]
Moved to: https://github.com/jamesmontemagno/ConnectivityPlugin/issues/5
