### ISSUE TITLE
Geolocator Timestamp Issue

### ISSUE THREAD

**Issue by bikashghosh123** [jamesmontemagno/Xamarin.Plugins#294]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [x ] Bug
- [ ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [x ] Geolocator
- [ ] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin:
Device Tested On: iPhone 6s , Samsung Galaxy S6
Simulator Tested On:

### Expected Behavior
The UTC/Local timestamp that Geolocator plugin is returning should not be dependent on device time. It should return actual time. I saw that if I modify the device time UTC time also gets changed. It shouldn't be the case.
### Actual Behavior
GPS time should not be dependent on device time. It should return the actual time for a particular GPS location.
### Steps to reproduce the Behavior
1. Print UTC/Local timestamp from code.
2. Change the device time
3. Now check the UTC/local time

**Comment by jamesmontemagno** [comment]
This was fixed in alpha builds.
