### ISSUE TITLE
CiecleImage's opacity is not working on Android.

### ISSUE THREAD

**Issue by allbdeveloper** [jamesmontemagno/Xamarin.Plugins#295]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [x ] Bug
- [ ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [ ] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

CircleImage

Version Number of Plugin:
Device Tested On: 
Simulator Tested On: Android lollipop / iOS 8 or higher

### Actual Behavior
Setting CircleImage's opacity is not working. If I set it as under 1, it's not shown. 
(Only Android. and Xamarin's 'Image' is working fine.)

### Steps to reproduce the Behavior

**Comment by allbdeveloper** [comment]
Hi, 
Thanks for this wonderful plugin. 
Just wanna know if you saw this issue.

Thanks again.

**Comment by deduefren** [comment]
Hi, I'm having the same issue. 

I'm only being able to reproduce it on android with API level 21 or 22. On API 23 it work again.

Thanks

**Comment by jamesmontemagno** [comment]
Moved to: https://github.com/jamesmontemagno/ImageCirclePlugin/issues/2
