### ISSUE TITLE
Android NFC scanner

### ISSUE THREAD

**Issue by aphex3k** [jamesmontemagno/Xamarin.Plugins#298]
I know this is not a cross platform feature but it would be nice to request platform specific features as well. Right now this seems limited to the least common denominator.

This is a 
- [X] Feature Request

Which plugin does this impact:
- [x] Permissions

Version Number of Plugin:

Device Tested On:

Simulator Tested On:

### Expected Behavior
Can someone please add a permission for the Android NFC scanner?

### Steps to reproduce the Behavior

**Comment by jamesmontemagno** [comment]
I am not sure what you mean by this? Is this in the permissions plugin that you want to know if NFC is there? It doesn't require a runtime permission in android, just in the manifest.
