### ISSUE TITLE
Require Remote Connectivity

### ISSUE THREAD

**Issue by dansiegel** [jamesmontemagno/Xamarin.Plugins#299]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [X] Feature Request

Which plugin does this impact:
- [X] Connectivity

Version Number of Plugin: 2.1.2
Device Tested On:
Simulator Tested On:

### Expected Behavior
It would be nice to do more than manually check if a remote host is reachable. The plugin should have a mechanism to require a remote host is reachable and in the event that the host is not reachable a ConnectivityChanged event or possibly a new event should be triggered. This would be helpful particularly for Enterprise Applications which may require connectivity to a private Api and the device may experience loss of connectivity to that host while still being connected to the internet.

### Steps to reproduce the Behavior

**Comment by jamesmontemagno** [comment]
This is a pretty cool idea, however I am not sure if there are actual APIs to monitor this. You would have to try to leave a constant socket open to the end point and pass data back and forth. If you have any ideas let me know, but I don't think it is possible across all platforms.

**Comment by jamesmontemagno** [comment]
Moved to: https://github.com/jamesmontemagno/ConnectivityPlugin/issues/4
