### ISSUE TITLE
Unified iOS issues

### ISSUE THREAD

**Issue by jjbrunton** [jamesmontemagno/Xamarin.Plugins#30]
I am getting a on iOS Simulator (iPhone 6 8.0) but not on the iPhone 6 plus "System.IO.FileNotFoundException" - Could not load file or assembly 'monotouch, Version 0.0.0.0'...

Other simulators work or provide another error 'Parameter obj should not be null'.

**Comment by jamesmontemagno** [comment]
Hey there, which plugin are you using?

It looks like you have a non-unified NuGet installed. Be sure to uninstall all your NuGets, ensure you have the latest NuGet package manager installed, and re-install the NuGet.

**Comment by jjbrunton** [comment]
Apologies, I am using the Settings plugin. I have removed the NuGet packages from the iOS project and the core project and I am still experiencing these issues. Weirdly, it looks like it might only be on the simulators?

**Comment by jamesmontemagno** [comment]
Are you sure that all projects are correct referencing the Xamarin.iOS10 folder where the DLLs exist. I have tested this on all devices. From your exception it is saying "monotouch" which is saying one of your DLLS is not correct. Is it version 1.5.0?

**Comment by jjbrunton** [comment]
![screen shot 2015-02-20 at 09 38 20](https://cloud.githubusercontent.com/assets/8502823/6284067/5e2eb4ae-b8e4-11e4-8d6b-6668697e93e7.png)
![screen shot 2015-02-20 at 09 38 31](https://cloud.githubusercontent.com/assets/8502823/6284068/5e31ac0e-b8e4-11e4-9d31-8b73aba070bb.png)

Assembly version is 1.5.0.0

This crashes on "iPhone 5s iOS 8.0" simulator.
![screen shot 2015-02-20 at 09 40 39](https://cloud.githubusercontent.com/assets/8502823/6284087/90834b7c-b8e4-11e4-8185-7eb94e213aa2.png)

**Comment by jamesmontemagno** [comment]
What are you trying to save?

Have you tried this sample: https://github.com/jamesmontemagno/Xamarin.Plugins/tree/master/Settings/Component/SettingsPlugin/samples

I just tested it on iPhone 5s simulator and it is fine here.

**Comment by jjbrunton** [comment]
Appreciate the help James, annoyingly it turned out to be that the app needed to be uninstalled. I can only guess it was being deployed incrementally and was causing issues.

Removing the application from all simulators and redeploying solved the issue.
