### ISSUE TITLE
Issue adding ImageCircle with XF 2.2.0.31 for Android project

### ISSUE THREAD

**Issue by jovymathew** [jamesmontemagno/Xamarin.Plugins#302]
How do i fix the following error while adding the ImageCircle in the Android project after updating the Xamarin Forms 2.2.0.31

Adding Xam.Plugins.Forms.ImageCircle...
Attempting to resolve dependency 'Xamarin.Forms (≥ 2.0.1.6505)'.
Attempting to resolve dependency 'Xamarin.Android.Support.v4 (= 23.0.1.3)'.
Attempting to resolve dependency 'Xamarin.Android.Support.Design (= 23.0.1.3)'.
Attempting to resolve dependency 'Xamarin.Android.Support.v7.AppCompat (≥ 23.0.1.3)'.
Attempting to resolve dependency 'Xamarin.Android.Support.v4 (= 23.3.0)'.
Attempting to resolve dependency 'Xamarin.Android.Support.Design (= 23.3.0)'.
Updating 'Xamarin.Android.Support.v4 23.0.1.3' to 'Xamarin.Android.Support.v4 23.3.0' failed. Unable to find a version of 'Xamarin.Forms' that is compatible with 'Xamarin.Android.Support.v4 23.3.0'.

**Comment by jamesmontemagno** [comment]
Seems like you haven't updated all of the packages correctly, you should double check your packages. Maybe uninstall Forms and re-install the nuget?

**Comment by jamesmontemagno** [comment]
Can not reproduce at all here.
