### ISSUE TITLE
Xam.Plugin.Media taking photo not working on Xamarin.Forms(currently 2.2.0.31)

### ISSUE THREAD

**Issue by huby01** [jamesmontemagno/Xamarin.Plugins#303]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [x] Bug

Which plugin does this impact:
- [x] Media

Version Number of Plugin:2.3.0
Device Tested On:
Simulator Tested On:WP8.1

### Expected Behavior
Taking photo
### Actual Behavior
Taking photo task hangs with an endless "Resume..." message
### Steps to reproduce the Behavior

**Comment by danieledallavalle** [comment]
I have the same behavior on Android and same Foms version

**Comment by danieledallavalle** [comment]
Actually my issue seems more related to a strange behavior of ImageSource.FromStream not executing the delegate, the Media plugin is working correctly

**Comment by EduardoSerra** [comment]
Did you work around this issue? how?

**Comment by danieledallavalle** [comment]
Sorry for the late replay,

What I did was to use the path of the MediaFIle on the device to retrieve it, but you can also use the GetStream method of the MediaFile itself

**Comment by huby01** [comment]
I temporarily downgraded Xamarin.Forms to version 2.1.0.6529 and it works.
I also tried the current XF 2.3.*-pre2 and it is not working.

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/MediaPlugin#9
