### ISSUE TITLE
TakeVideoAsync is deleting other photos and videos on S7 running android 6.0.1

### ISSUE THREAD

**Issue by garybettman** [jamesmontemagno/Xamarin.Plugins#305]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [x] Bug
- [ ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [x] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin: 2.3.0
Device Tested On: S7 running android 6.0.1
Simulator Tested On:

### Expected Behavior

When using TakeVideoAsync it should be creating a new video file

### Actual Behavior

It is not creating a new file and is actually deleting existing images and videos inside my camera directory. It is not deleting images in folders such as downloads.  This is working fine on iOS and other android devices running older versions.  I don't know if it is the S7 or android 6.0.1

### Steps to reproduce the Behavior
Make sure you have multiple images and videos in the Camera's folder.  If there is just one it seems to work.
Create a new xamarin forms app.
Create a button that when clicked fires off TakeVideoAsync .
Take a video.
Click ok to accept video.
You will notice that an image or video has been removed from the Gallery.

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/MediaPlugin#8
