### ISSUE TITLE
[Media] iOS: Portrait photo appears as Landscape (stretched to fill landscape) when using PhotoSize.Small

### ISSUE THREAD

**Issue by CliffCawley** [jamesmontemagno/Xamarin.Plugins#306]
This is a 
- [x] Bug
- [ ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [x] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate

Version Number of Plugin: 2.4.0-beta2
Device Tested On: iPhone 6s
Simulator Tested On:

### Expected Behavior
Portrait photo to appear as portrait photo

### Actual Behavior
Portrait photo appears to be resized to be landscape (not rotated) so image is stretched horizontally

### Steps to reproduce the Behavior
Take a photo using PhotoSize.Small (Possibly others also don't work)
```
MediaFile file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions {
				Directory = "Media",
				Name = "MyFilename.jpg",
				PhotoSize = PhotoSize.Small
			});
			if (file != null)
			{
				// Load into an image control and you'll see the image is stretched horizontally.
			}
```

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/MediaPlugin#7
