### ISSUE TITLE
Heading value returns 0 in GeoLocator plugin

### ISSUE THREAD

**Issue by Nikygm** [jamesmontemagno/Xamarin.Plugins#307]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [x] Bug
- [ ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [x] Geolocator
- [ ] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin: 3.0.4
Device Tested On: Wiko kite (API 19)
Simulator Tested On:

### Expected Behavior

It is supposed to return the heading value where the device heads at compared to the north

### Actual Behavior

It returns 0

### Steps to reproduce the Behavior

I'm calling the method like so : 

var position = await CrossGeolocator.Current.GetPositionAsync(10000,null,true);
            Latitude = position.Latitude.ToString();
            Longitude = position.Longitude.ToString();
            Heading = position.Heading;

            System.Diagnostics.Debug.WriteLine("Position Status: " + position.Timestamp);
            System.Diagnostics.Debug.WriteLine("Position Latitude: " + position.Latitude);
            System.Diagnostics.Debug.WriteLine("Position Longitude: " + position.Longitude);
            System.Diagnostics.Debug.WriteLine("Position Heading: " + position.Heading);

**Comment by jamesmontemagno** [comment]
Please checkout: https://github.com/jamesmontemagno/Xamarin.Plugins/issues/140

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/GeolocatorPlugin#3
