### ISSUE TITLE
Integration with iOS settings bundles

### ISSUE THREAD

**Issue by Marakai** [jamesmontemagno/Xamarin.Plugins#311]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [X] Feature Request

Which plugin does this impact:
- [X] Settings

Version Number of Plugin: 2.5
Device Tested On: iPhone 6s
Simulator Tested On: iPhone Simulator

### Actual Behavior

Settings will  work perfectly when remaining with in-app preferences. However, they will not appear in the iOS Settings app. No integration with the iOS settings.bundle. Not sure this is even possible, but I thought I'd ask.
### Steps to reproduce the Behavior

**Comment by jamesmontemagno** [comment]
If you name them the same then it should work alright as I save them in NSUserDefaults

**Comment by Marakai** [comment]
That's an idea! I thought there'd be errors galore with naming overlap. Downside is you still have to create all the stuff in settings.bundle/en.proj/... manually, oh well.

**Comment by jamesmontemagno** [comment]
Yeah, i don't think you can do it pragmatically at all..

This would be good documentation to add in actually.

**Comment by jamesmontemagno** [comment]
Todo: add documentation
