### ISSUE TITLE
CrossDevice Feature Request -- Application package and version

### ISSUE THREAD

**Issue by zoanthal** [jamesmontemagno/Xamarin.Plugins#312]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [ ] Bug
- [ x] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ x] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [ ] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin:
Device Tested On:
Simulator Tested On:

### Steps to reproduce the Behavior

**Comment by jamesmontemagno** [comment]
Have you checked out: https://github.com/PluginsForXamarin/version-tracking

**Comment by zoanthal** [comment]
Thanks!


Vikas O'Reilly-Shah, MD, PhD
Assistant Professor of Anesthesiology
Chair, Data Governance Committee
Divisions of Surgical Specialties and of Pediatric Anesthesiology
Emory University School of Medicine and Children's Healthcare of Atlanta
Cell: +1-615-335-3808

On Wed, May 25, 2016 at 10:37 PM, James Montemagno <notifications@github.com
