### ISSUE TITLE
FillColor doesn't work in UWP

### ISSUE THREAD

**Issue by Matti-Koopa** [jamesmontemagno/Xamarin.Plugins#313]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [x] Bug
- [ ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [x] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin:
Device Tested On: Windows 10 Version 1511
Simulator Tested On: -

### Expected Behavior
Transparent part of PNG image fills with Color specified in "FillColor" attribute
### Actual Behavior
Transparent part of PNG stays transparent / filled with BackgroundCOlor of parent element
### Steps to reproduce the Behavior
Regular CircleImage control with FillColor specified

**Comment by jsenich** [comment]
I'm running into this as well with v1.4.1 of the ImageCircle plugin.

**Comment by jamesmontemagno** [comment]
Moved to: https://github.com/jamesmontemagno/ImageCirclePlugin/issues/1

I did not implement this so it is expected currently.
