### ISSUE TITLE
Default DesiredAccuracy

### ISSUE THREAD

**Issue by MihaMarkic** [jamesmontemagno/Xamarin.Plugins#32]
i don't think that DesiredAccuracy's defualt value 0 is a good choice. That way you won't ever get a position since retrieved accuracy is always greater than 0.
Perhaps a value of double.MaxValue is a better choice?

**Comment by jamesmontemagno** [comment]
I agree that it should be something that isn't 0 so it is faster. I think 50 is a good default as it is in meters. MaxValue would be a huge blanket.

**Comment by jamesmontemagno** [comment]
Closed via: https://twitter.com/MihaMarkic/status/568854690756214786
