### ISSUE TITLE
Settings and List of values

### ISSUE THREAD

**Issue by Goldstrike** [jamesmontemagno/Xamarin.Plugins#322]
Please take a moment to fill out the following (change to preview to check or place x in []) and remove all unused areas

This is a 
- [X] Feature Request

Which plugin does this impact:
- [X] Settings

Hello,

I would like to know if there is a way to use the Settings to store Data Types like List<KeyValuePair<string, string>>.

I know that this type is not in supported basically, but I'm looking for a way to store some cookies, that will be returned by a WebService, through the Settings. The number and the names of the cookies could change, so I wouldn't store them as individual values.

Is there a way to manage this?

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/SettingsPlugin#1
