### ISSUE TITLE
Settings Availability after app upgrade & uninstall/install

### ISSUE THREAD

**Issue by NovakSavicOPAL** [jamesmontemagno/Xamarin.Plugins#323]
Please take a moment to fill out the following (change to preview to check or place x in []) and remove all unused areas

This is a 
- [x] Feature Request

Which plugin does this impact:
- [x] Settings

## Feature Request:
This is basically question.
Are application settings available on all platforms if:
1. After application is upgraded to next version ?
2. Application is manually uninstalled and installed again?

Thanks!

**Comment by jamesmontemagno** [comment]
Settings are saved in NSUserDefaults, AppData, IsolatatedStoreage, and SharedPreferences. These are brought over with each upgrade of the app.

However on uninstall and re-install they will not be saved as the OS blows them away.
