### ISSUE TITLE
CrossGeolocator does not prompt for Location permission

### ISSUE THREAD

**Issue by pauldiston** [jamesmontemagno/Xamarin.Plugins#325]
Please take a moment to fill out the following (change to preview to check or place x in []) and remove all unused areas

This is a 
- [x] Bug

Which plugin does this impact:
- [x] Geolocator

## Bug

Version Number of Plugin: 3.0.4
Device Tested On: LG K8 (K350)
Simulator Tested On: N/A

### Expected Behavior
Location permission should be prompted for

### Actual Behavior
Location permission is not prompted for
### Steps to reproduce the Behavior
Create instance of GeoLocator and call StartListeningAsync

**Comment by jamesmontemagno** [comment]
I will add this in the future, checkout using the Permission Plugin until then.

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/GeolocatorPlugin#2
