### ISSUE TITLE
Application does not resume after calling CrossMedia.Current.TakePhotoAsync (Windows Phone)

### ISSUE THREAD

**Issue by pauldiston** [jamesmontemagno/Xamarin.Plugins#326]
Please take a moment to fill out the following (change to preview to check or place x in []) and remove all unused areas

This is a 
- [x] Bug

Which plugin does this impact:
- [x] Media

## Bug

Version Number of Plugin: 2.3.0
Device Tested On: Microsoft Lumia 640

### Expected Behavior
Application should resume after calling CrossMedia.Current.TakePhotoAsync

### Actual Behavior
After calling CrossMedia.Current.TakePhotoAsync, and accepting the taken image, the Resuming... message appears on the phone however the next line after calling TakePhotoAsync is never called. In release mode, the application will crash.
### Steps to reproduce the Behavior
1. Call CrossMedia.Current.TakePhotoAsync
2. Accept taken photo
3.Notice that the application doesn't resume

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/MediaPlugin#4
