### ISSUE TITLE
CrossDeviceInfo.Current.Version always get some weird numbers for UWP

### ISSUE THREAD

**Issue by huangjinshe** [jamesmontemagno/Xamarin.Plugins#328]
Please take a moment to fill out the following (change to preview to check or place x in []) and remove all unused areas

This is a 
- [x] Bug
- [] Feature Request

Which plugin does this impact:
- [] Battery
- [] Connectivity
- [] Contacts
- [x] DeviceInfo
- [] ExternalMaps
- [] Geolocator
- [] Media
- [] Permissions
- [] Settings
- [] Text To Speech
- [] Vibrate
- Other:

## Bug

Version Number of Plugin:2.0.2
Device Tested On:Windows 10 Visual Studio 2015
Simulator Tested On:Windows Phone 10 emulator by Visual studio 2015

### Expected Behavior
 return: 10.0.586
### Actual Behavior
return : 2814750460870974
### Steps to reproduce the Behavior
return CrossDeviceInfo.Current.Version

## Feature Request:
Please fill in what you would like

**Comment by jamesmontemagno** [comment]
Moved to: https://github.com/jamesmontemagno/DeviceInfoPlugin/issues/2
