### ISSUE TITLE
GeoLocator - Request - Get NMEA string and Number of Satellites

### ISSUE THREAD

**Issue by tlhintoq** [jamesmontemagno/Xamarin.Plugins#330]
This is a 
- [X] Feature Request

Which plugin does this impact:
- [x] Geolocator

## Feature Request:
It would be really great if the Number of Satellites and raw NMEA string could be accessible properties just like Latitude, Longitude etc.  I feel silly contemplating have to create my own dependency service for these when GeoLocator is (presumably) already grabbing this data. Not to mention worrying that two different services trying to grab the same data just smells like trouble.

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/GeolocatorPlugin#1
