### ISSUE TITLE
Connectivty fails on IPv6 networks

### ISSUE THREAD

**Issue by asj-it** [jamesmontemagno/Xamarin.Plugins#331]
Please take a moment to fill out the following (change to preview to check or place x in []) and remove all unused areas

This is a 
- [x] Bug
- [] Feature Request

Which plugin does this impact:
- [] Battery
- [x] Connectivity
- [] Contacts
- [] DeviceInfo
- [] ExternalMaps
- [] Geolocator
- [] Media
- [] Permissions
- [] Settings
- [] Text To Speech
- [] Vibrate
- Other:

## Bug

Version Number of Plugin:  2.1.2
Device Tested On: Iphone 6s IOS 9.3
Simulator Tested On: 

### Expected Behavior
When calling `Connectvity.Current.IsRemoteReachable` true should be returned for both IPv4 and IPv6 networks
### Actual Behavior
Works fine on Ipv4 network, but incorrectly returns `false`  for the IPv6 network

### Steps to reproduce the Behavior
Create Ipv6 network [(instructions)](https://derflounder.wordpress.com/2015/10/05/enabling-an-ipv6-only-network-using-internet-sharing-on-el-capitan/)  to create a IPv6 only network on OSX.  Connect to it from Iphone device and run code that calls IsRemoteReachable

**Comment by jamesmontemagno** [comment]
Working on this. You will see a 2.2.0-beta1 soon

**Comment by jamesmontemagno** [comment]
Can you please test the new beta1 of 2.2.0, now on NuGet

**Comment by asj-it** [comment]
Just tested this this morning and all seems to be working fine.  Thanks for the speedy update!

Ash :-)
