### ISSUE TITLE
iOS devices can't recognize if there are no camera permission 

### ISSUE THREAD

**Issue by Brosten** [jamesmontemagno/Xamarin.Plugins#332]
Please take a moment to fill out the following (change to preview to check or place x in []) and remove all unused areas

This is a 
- [] Bug
- [x] Feature Request

Which plugin does this impact:
- [] Battery
- [] Connectivity
- [] Contacts
- [] DeviceInfo
- [] ExternalMaps
- [] Geolocator
- [x] Media
- [] Permissions
- [] Settings
- [] Text To Speech
- [] Vibrate
- Other:

## Bug

Version Number of Plugin: 2.3
Device Tested On: ipad air 2
Simulator Tested On: 

## Feature Request:
There should be a property telling whatever the app has permission to use the camera or not. For the moment I have to implement this in my own iOS code. Should be nice if it were included in the CrossMedia

**Comment by jamesmontemagno** [comment]
Have you tried to use the Permissions plugin?

**Comment by Brosten** [comment]
Ahh, ok. No I havn’t.

I’ll have a look at it. Thank you.

 

And, by the way, thanks for the great Xamarin Evolve event!

 

// Andreas

 

Från: James Montemagno [mailto:notifications@github.com] 
Skickat: den 15 juni 2016 22:46
Till: jamesmontemagno/Xamarin.Plugins <Xamarin.Plugins@noreply.github.com>
Kopia: Brosten <andreas@brosten.com>; Author <author@noreply.github.com>
Ämne: Re: [jamesmontemagno/Xamarin.Plugins] iOS devices can't recognize if there are no camera permission (#332)

 

Have you tried to use the Permissions plugin?

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/MediaPlugin#3

**Comment by Brosten** [comment]
Hey! 
Isn't it the information you were looking for? Read about it here <http://mri.emsmeet.com/e4fc/5>


Be well, Andreas Brosten
