### ISSUE TITLE
Connectivity Plugin...Does this support IPV 6 network?

### ISSUE THREAD

**Issue by mofadevs** [jamesmontemagno/Xamarin.Plugins#333]
Please take a moment to fill out the following (change to preview to check or place x in []) and remove all unused areas

This is a 
- [] Bug
- [X] Feature Request

Which plugin does this impact:
- [] Battery
- [X] Connectivity
- [] Contacts
- [] DeviceInfo
- [] ExternalMaps
- [] Geolocator
- [] Media
- [] Permissions
- [] Settings
- [] Text To Speech
- [] Vibrate
- Other:

## Bug

Version Number of Plugin:
Device Tested On:
Simulator Tested On:

## Feature Request:
Just wanted to double check, if the Connectivity plugin supports IPV6 networks? If not please make it.

**Comment by jamesmontemagno** [comment]
Duplicate of #331

**Comment by jamesmontemagno** [comment]
https://www.nuget.org/packages/Xam.Plugin.Connectivity/2.2.0-beta1 is now available for testing
