### ISSUE TITLE
Empty file is created on canceling, while take photo with SaveToAlbum = true

### ISSUE THREAD

**Issue by CarMatt** [jamesmontemagno/Xamarin.Plugins#335]
This is a 
- [x] Bug

Which plugin does this impact:
- [x] Media

## Bug

Version Number of Plugin: 2.3.0
Device Tested On:
Samsung S4 Droid 5.0.1
Samsung S6 Droid 6.0.1
Simulator Tested On:
Visual Studio emulator Droid 5.1.1
### Expected Behavior
No file should be created when you canceling a photo
### Actual Behavior
When you take a photo and you choose to cancel, an empty file is created on disk
### Steps to reproduce the Behavior
Select cancel when to take a photo

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/MediaPlugin#2
