### ISSUE TITLE
Gelocator 3.0.4 System.NotImplementedException

### ISSUE THREAD

**Issue by brux88** [jamesmontemagno/Xamarin.Plugins#336]
Please take a moment to fill out the following (change to preview to check or place x in []) and remove all unused areas

This is a 
- [X] Bug
- [] Feature Request

Which plugin does this impact:
- [] Battery
- [] Connectivity
- [] Contacts
- [] DeviceInfo
- [] ExternalMaps
- [X] Geolocator
- [] Media
- [] Permissions
- [] Settings
- [] Text To Speech
- [] Vibrate
- Other:

## Bug

Version Number of Plugin:3.04
Device Tested On:andordi 6.0
Simulator Tested On:

### Expected Behavior
gestcurrentposition
### Actual Behavior
return thi error:
{System.NotImplementedException: This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.
  at Plugin.Geolocator.CrossGeolocator.get_Current () [0x0000d] in C:\projects\xamarin-plugins\Geolocator\Geolocator\Geolocator.Plugin\CrossGeolocator.cs:23 
  at WuThinkX.View.MapPage+<GetCurrentPosition>d__4.MoveNext () [0x00018] in C:\Progetti\WuThinkX\WuThinkX\WuThinkX\View\MapPage.xaml.cs:140 }

hello, I have followed the guide, I installed the plugin on all platforms but when run the code, from my plc project gives me this error, I also tried to download the example (Xamarin.Plugins/Geolocator/Common/GeolocatorPlugin/samples) works, but if I try to update the from 1.0.3 to last  version 3.0.4 gives me the same problem.

**Comment by jamesmontemagno** [comment]
Did you update ALL of the projects that have the nuget installed? You have to update your PCL and your Android/iOS/Windows Project.

**Comment by brux88** [comment]
yes all project have geolocator 3.0.4

**Comment by jamesmontemagno** [comment]
I have updated the sample and it is working perfect. I am unable to reproduce. Make sure you clean/rebuild and that all of your Projects that reference the Geolocator are on the same version.

**Comment by brux88** [comment]
hi, i have try, i have remove all reference (bin,obj) and rebuild and now work thanks

**Comment by waden34** [comment]
Another thing to try is deleting the project.lock.json file. 
I uninstalled, cleaned, rebuilt to no avail, but deleting that file finally got things working again.
I think I had an invalid reference in there due to moving projects around.
