### ISSUE TITLE
Version 2.2.0 on iOS : isRemoteReachable always returns false

### ISSUE THREAD

**Issue by mofadevs** [jamesmontemagno/Xamarin.Plugins#338]
Please take a moment to fill out the following (change to preview to check or place x in []) and remove all unused areas

This is a 
- [X] Bug
- [] Feature Request

Which plugin does this impact:
- [] Battery
- [X] Connectivity
- [] Contacts
- [] DeviceInfo
- [] ExternalMaps
- [] Geolocator
- [] Media
- [] Permissions
- [] Settings
- [] Text To Speech
- [] Vibrate
- Other:

## Bug

Version Number of Plugin:2.2.0
Device Tested On: iPhone 6s
Simulator Tested On: iPhone 6s iOS 9.2

### Expected Behavior
If remote host is reachable, should return true
### Actual Behavior
Always returns false, even if remote host is reachable. 
## Feature Request:
Please fill in what you would like

**Comment by jamesmontemagno** [comment]
Please try 2.2.1 as I added a bit more handling for v4 and v6 handling. I have tested against a bunch of different URLs and it is working great.

**Comment by mofadevs** [comment]
Hi, I have tried version 2.2.1 and 2.2.2 but in both cases, on iOS, isRemoteReachable always returns false. I have test the new version on iPhone 6s physical device and same version on the simulator as well. I have used google.com, apple.com and few other links but response is always false. I m using it like the following:
 _return CrossConnectivity.Current.IsConnected &&
                          await CrossConnectivity.Current.IsRemoteReachable("google.com");_
Please advise.

**Comment by jamesmontemagno** [comment]
Are you building it against xcode 7.3.1? I have tested it on iOS 9.3.X and working good here.

**Comment by mofadevs** [comment]
Hi James I mean using xamarin forms on Windows machine and using a mac
build host that has xcode 7.2.1. Should I upgrade xcode? Will it have any
affect on the current project since it is at the last stage and we don't
want any hiccups. Please advise?
