### ISSUE TITLE
Xam.Settings - not working in iOS unified environment

### ISSUE THREAD

**Issue by GuentherR** [jamesmontemagno/Xamarin.Plugins#34]
I converted an existing Xamarin forms with Settings plugin1.5 to unified iOS.
I got an error message that monotouch.dll is used by Settings ( which clashes with Xamarin.ios)

**Comment by jamesmontemagno** [comment]
Ensure that you uninstall and re-install all of your NuGets.

Additionally, if on simulator uninstall your app and re-install. 

See: https://github.com/jamesmontemagno/Xamarin.Plugins/issues/30#issuecomment-75313889
