### ISSUE TITLE
Version 2.2.1 and 2.2.2 on iOS : isRemoteReachable always returns false

### ISSUE THREAD

**Issue by mofadevs** [jamesmontemagno/Xamarin.Plugins#341]
Which Plugin does this impact: Xam.Plugins.Connectivity

Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 2.2.1 and 2.2.2
Device Tested On: iPhone 6s physical device ios9.2
Simulator Tested On: iPhone 6s ios9.2

### Expected Behavior
Should return true if the remote host is reachable
### Actual Behavior
Always returns false
### Steps to reproduce the Behavior
Running the following code always returns false:
return CrossConnectivity.Current.IsConnected &&
                          await CrossConnectivity.Current.IsRemoteReachable("google.com");
## Feature Request:
Please fill in what you would like

**Comment by jamesmontemagno** [comment]
This was tested and works perfect on 2.2.2 on device. Are you running the latest stable and xcode 7.3.1?

**Comment by mofadevs** [comment]
Hi James
I am using XCode 7.2.1 on my Mac Build Host. Is it necessary to upgrade it to 7.3.1? Coz we are at the final stage of the project and want to avoid any hiccups. Please advise.

**Comment by jamesmontemagno** [comment]
Should be the latest 7.3.x

**Comment by mofadevs** [comment]
Hi James,
Its been a while, but I thought I should give you my feedback. As you
suggested, I upgraded the XCode to latest version on my Mac build host and
the plugin works fine.
Actually we have successfully published our app to both Play Store and App
Store, completely rebuilt using Xamarin Forms from scratch. The app is
multilingual (English and Arabic) and has features like Map, Directions
Plotting, Live Data Sync, Embedding yahoo and google apis etc. We 've had
our challenges but were able to cop, using good community+Xamarin input.

James, I love Xamarin, and badly wants a Code Monkey+Xamarin University
Mug!! Can you help me with that???

Thanks
ADEEL (@_adeel_ehsan)

**Comment by wimdevriendt** [comment]
Hi Adeel, is it possible to share your project ? I am very curious about it and how you developped it
