### ISSUE TITLE
Huge delay or not opening camera Iphone SE

### ISSUE THREAD

**Issue by ppun51** [jamesmontemagno/Xamarin.Plugins#342]
Which Plugin does this impact: Xamarin Plug IN 2.30

Please fill out either the bug or feature request section and remove whatever section you are not using.
No Bug number for this issue

Version Number of Plugin:
Device Tested On: Iphone SE
Simulator Tested On: No

Some times opening camera with Huge delay or not opening camera.
When open camera,  all of buttons are freeze with black screen until I touch middle of screen.

Do you have anyone have this issue?
I am about to test it with Iphone 6S.

Is there any limit for this plug in to supports?

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/MediaPlugin#1
