### ISSUE TITLE
Add better null handling to contact loading.

### ISSUE THREAD

**Issue by josemh** [jamesmontemagno/Xamarin.Plugins#346]
Which Plugin does this impact: Contact - https://github.com/jamesmontemagno/Xamarin.Plugins/tree/master/Contacts

## Bug 

* Version Number of Plugin: 2.0.2-beta1 - Also happens if compiled from master
* Device Tested On: Galaxy S7 Edge
* Simulator Tested On: None

### Expected Behavior 
Calling CrossContacts.Current.Contacts.ToList() should return a list of all contacts.

### Actual Behavior
I get the following error: `Java.Lang.IllegalArgumentException: the bind value at index 255 is null`

It seems there is a contact on this particular phone with an null CONTACT_ID.  Perhaps this is due to data corruption.

### Steps to reproduce the Behavior
In the following method of the ContactsHelper class (line 63):
```C#
    internal static IEnumerable<Contact> GetContacts(ICursor cursor, bool rawContacts, ContentResolver content, Resources resources, int batchSize)
```

The id should be checked for null.  So line 88 should be change from:
```C#
    if (uniques.Contains(id))
```

To:
```C#
    if (uniques.Contains(id) || id == null)
```

## Feature Request:
Add better null handling to contact loading.

**Comment by jamesmontemagno** [comment]
will be in https://github.com/jamesmontemagno/ContactsPlugin Updated the code to reflect this.
