### ISSUE TITLE
Question - Media plugin

### ISSUE THREAD

**Issue by Pinox** [jamesmontemagno/Xamarin.Plugins#347]
Media Plugin , 

Is it possible to determine whether a picture was taken in Landscape or portrait mode. I  want todo something like this :
var image = ImageSource.FromStream(() => new MemoryStream(imageAsBytes));
if (image.Width > image.Height) {  "This is Landscape mode"   } 
Any pointers in the right directions would be appreciated.

**Comment by jamesmontemagno** [comment]
Not currently no, you would need to load up the images natively to see or load up exif data from each and calculate on there.
