### ISSUE TITLE
Permission Request Description required in iOS 10.

### ISSUE THREAD

**Issue by raedwa01** [jamesmontemagno/Xamarin.Plugins#348]
Which Plugin does this impact: _Contacts__ <- fill in here

## Bug 

In iOS 10, if you do not specify the Privacy description strings in the Info.plist, your app WILL crash with no logged reason.  Not a fault of the plug in, just a new requirement of iOS 10.

* Version Number of Plugin:
* Device Tested On:
* Simulator Tested On:

### Expected Behavior
Request would prompt for permission.

### Actual Behavior
App crashes

### Steps to reproduce the Behavior

Create a request for contacts.  Using iOS 10, do not put in a value for the Privacy - Contacts Usage Description in the Info.plist.  Run app and make request for contacts.  App will crash.  Add in required value to the Info.plist, recompile and run.  App will show value when requesting permission.  Need to document this in the readme.

**Comment by jamesmontemagno** [comment]
see updated readme
