### ISSUE TITLE
Licenses

### ISSUE THREAD

**Issue by Cheesebaron** [jamesmontemagno/Xamarin.Plugins#35]
Hey James,

I see some discrepancies with the license stated in some of my plugins and your statements in your derivative work. For the Connectivity and DeviceInfo plugin the Apache 2.0 license is used. You can see all the "Must" stuff you need to do in order to adhere to the license here: https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)

Basically you have removed the copyright and license statements in the top of the files you are deriving from. You also need to state that the files have been modified. You also need to have a NOTICE file with attribution notes.

I did give you permission to use my code, which the Apache 2.0 license already states that you can do :smile:. Although I am pretty certain that you can't sub-license Apache 2.0 licensed code with a less restrictive license like MIT. Although your own code can be licensed as MIT, you must retain Apache 2.0 on my code.

If you need help fixing these things, please do tell. It might be easier to change the two plugins in question to Apache 2.0.

Thanks,
Tomasz

**Comment by jamesmontemagno** [comment]
I can update this, sorry about that.

**Comment by jamesmontemagno** [comment]
Does the NOTICE file need to simply be in github or included in the nuget package?

**Comment by Cheesebaron** [comment]
The NOTICE is only for redistribution of the source code. Not for compiled code.

Apache 2.0 also requires then user of any Apache 2.0 licensed code to be attributed inside of the application. So it should mention the usage of any Apache 2.0 licensed plugin inside the app, by linking to this repository.

**Comment by jamesmontemagno** [comment]
Perfect, I will add a NOTICE file in there as well as others that are Apache 2.0 (the xamarin.mobile ones).

**Comment by Cheesebaron** [comment]
If it'd make it easier, I could look into relicensing using MIT or similar.
