### ISSUE TITLE
TapGestureRecognizer Command is not getting raised after imagecircle.IsEnabled changes

### ISSUE THREAD

**Issue by PantelisAr** [jamesmontemagno/Xamarin.Plugins#351]
I have the control's IsEnabled property bound to a ViewModel property which is false when the page loads and a RelayCommand bound to a TapGestureRecognizer added to the control's GestureRecognizers collection.

The Command doesn't seem to be able to execute when the ViewModel property bound to IsEnabled changes to true.

**Comment by jamesmontemagno** [comment]
Does this work with a normal Image?

**Comment by jamesmontemagno** [comment]
If so please open at: https://github.com/jamesmontemagno/ImageCirclePlugin

**Comment by PantelisAr** [comment]
James, didn't test it with a simple image yet, will do a bit later and report back. I've got another "disabled" looking image overlapping the one I mention and I'm toggling their visibility as a workaround, which I totally hate.
