### ISSUE TITLE
 GeoLocator, Battery and Contacts cannot be built for Release, Debug build has no issues

### ISSUE THREAD

**Issue by rarera** [jamesmontemagno/Xamarin.Plugins#352]
## Bug 

* Version Number of Plugin:
  <package id="Xam.Plugin.Battery" version="2.1.0" targetFramework="monoandroid60" />
  <package id="Xam.Plugin.Contacts" version="2.0.2-beta1" targetFramework="monoandroid60" />
  <package id="Xam.Plugin.Geolocator" version="4.0.0-beta4" targetFramework="monoandroid60" />
* Device Tested On: Lenovo X1 Carbon
* Simulator Tested On: Visual Studio 2015 Enterprise 

### Expected Behavior
Build succeeded
### Actual Behavior
CS0234 The type or Namespace Battery does not exist in the Namespace Plugin
CS0234 The type or Namespace Geolocator does not exist in the Namespace Plugin
CS0234 The type or Namespace Contacts does not exist in the Namespace Plugin

### Steps to reproduce the Behavior
Create Android project
Add the listed plugin nugets
Use the nugets in code
Build for debug -> success
Build for release -> fails

**Comment by jamesmontemagno** [comment]
Are you sure your nugets are installed in all projects? What are your linker settings set to?

I have never had any issue and released several apps to the store without any issues.

**Comment by rarera** [comment]
Hi James,


I have one Android project and several unrelated PCLs for some business logic.


I am using the plugins just in the Android project, which has all the nugets in the versions I listed.


If it is something about the linker. Which linker settings do you recommend? I have already tried several options without success.


Thanks,

Ramin


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
