### ISSUE TITLE
Camera app crashes when trying to playback video before saving in Android 7

### ISSUE THREAD

**Issue by JohnHasler** [jamesmontemagno/Xamarin.Plugins#355]
When taking a video using the TakeVideoAsync method we are getting an issue whereby on recording the video before confirming OK and saving the video we are unable to playback the video. When attempting to do this the device says that the camera has stopped.

This only occurs on devices using Android 7 (we have tested a few).

Please can you investigate this issue

**Comment by jamesmontemagno** [comment]
Please look at the individual repo to report an issue
