### ISSUE TITLE
Restarting the app while taking photo and after clicking OK

### ISSUE THREAD

**Issue by Packiaseelan** [jamesmontemagno/Xamarin.Plugins#357]
Hi james,

I am using  xam.plugin.media version 2.6.2
Not working in Some device. (MotoG 3rd Gen, MotoG 2rd Gen)
while taking photo after clicking "tick" or "OK". 
restarting the app. 

Please provide me a valid solution to me

**Comment by jamesmontemagno** [comment]
No issues are covered here, please go to the specific repo.
