### ISSUE TITLE
Minimum Android version compatibility for TextToSpeech

### ISSUE THREAD

**Issue by AbelCS** [jamesmontemagno/Xamarin.Plugins#36]
Hi, 

I'm trying your plugin and when I run the simple example:

```C#
CrossTextToSpeech.Current.Speak("Text to speak");
```

In some devices with Android version lower than 4.4 (KitKat) I get this error:

```
[] Missing method Android.Speech.Tts.TextToSpeech::get_DefaultLanguage() in assembly Mono.Android.dll, referenced in assembly /storage/sdcard0/Android/data/EverlapsMobile.Android/files/.__override__/Refractored.Xam.TTS.dll
```

**Comment by jamesmontemagno** [comment]
Ensure that you are compiling against API 21. That should fix it up. Additionally, ensure you have the latest nugets.
