### ISSUE TITLE
CrosscurrentActivity for iOs

### ISSUE THREAD

**Issue by CJACQUEL** [jamesmontemagno/Xamarin.Plugins#361]
Hello,

What is the equivalent of crosscurrent activity plugin on iOs ?

Thank you,
cjacquel

**Comment by CJACQUEL** [comment]
Hello James; 
Does Media.plugins needs Permission.Plugin on iOS ? 
ThxChristophe Jacquelin,

    Le jeudi 1 mars 2018 à 18:47:36 UTC+1, James Montemagno <notifications@github.com> a écrit :  
 
 
Closed #361.

**Comment by jamesmontemagno** [comment]
This is for library creators and doesn't' expose it cross-platform as iOS you can easily get to the app running window.
