### ISSUE TITLE
Image display rotated in web which is taken by IPhone

### ISSUE THREAD

**Issue by Arkinfosoft** [jamesmontemagno/Xamarin.Plugins#363]
- Media - http://github.com/jamesmontemagno/MediaPlugin
I used Media plugin to capture an image. An image captured by the iPhone is displayed rotated on the web but the same image in mobile show perfect. i used media plugin 4.0.1.5

**Comment by AmSmart** [comment]
I think it's better to open this PR on the original repo and this issue should probably be closed @jamesmontemagno
