### ISSUE TITLE
Vibrate plugin documentation issue

### ISSUE THREAD

**Issue by saramgsilva** [jamesmontemagno/Xamarin.Plugins#37]
In documentation you have

     In your iOS, Android, and Windows Phone projects please call:

    Xamarin.Forms.Init();//platform specific init
    Vibrate.Init();

but in Xamarin Android the Vibrate.Init(); not exists. I saw here
https://github.com/jamesmontemagno/Xamarin.Plugins/blob/master/Vibrate/Refractored.Xam.Vibrate.Android/Vibrate.cs

**Comment by jamesmontemagno** [comment]
You are looking in the wrong spot: https://github.com/jamesmontemagno/Xamarin.Plugins/blob/master/Vibrate/Refractored.Xam.Forms.Vibrate.Android/Vibrate.cs

**Comment by saramgsilva** [comment]
Humm.... why the nuget do not recognize this method?

-----Original Message-----

**Comment by saramgsilva** [comment]
you changed the API but did not changed the documentation for this reason it was not work... you could say that!

**Comment by saramgsilva** [comment]
And is **CrossVibrate.Current.Vibration** and it is not **CrossVibrate.Current.Vibrate**  :)

**Comment by jamesmontemagno** [comment]
I updated it. The API didn't change I just documented it incorrect, thanks for the change. You can always send a pull request for typos as well.

I have also obsoleted the forms version as there is no need for it since there is a general nuget available that I created.

**Comment by saramgsilva** [comment]
Sure, but I was using the nuget and read the code file on github and I did not have time to see more details.
