### ISSUE TITLE
Cancel

### ISSUE THREAD

**Issue by TimBarton** [jamesmontemagno/Xamarin.Plugins#38]
Is there a way to stop the Text To Speech after it has started?  Or have an event that launches when the speaking is done?

Thanks

**Comment by jamesmontemagno** [comment]
There is nothing in the implementation, but I could add it. Currently you could call Speak(string.Empty); to trick it I am pretty sure

**Comment by TimBarton** [comment]
Hi James,

I tried  Speak(string.Empty); and that sis not work.

Thanks,
Tim

**Comment by jamesmontemagno** [comment]
I will see if I can expose it in the API, but it is relatively easy if you
use the code for now instead of the plugin you can see where a lot of them
I have a Stop().... however some platforms might not have it. I will
research more.

On Thu, Mar 12, 2015 at 6:46 PM, TimBarton <notifications@github.com> wrote:

> Hi James,
>
> I tried Speak(string.Empty); and that sis not work.
>
> Thanks,
> Tim
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jamesmontemagno/Xamarin.Plugins/issues/38#issuecomment-78741124>
> .
>



-- 
James Montemagno
http://www.montemagno.com
@jamesmontemagno <http://www.twitter.com/jamesmontemagno>

**Comment by topsites** [comment]
Bump;
Speak(string.Empty)  would not work as the implementation skips if it's white or empty space. A Stop/Cancel is super simple implementation - but to do it on our end, we would need to recreate the whole project.

PS: Thanks james for the great work;

**Comment by jamesmontemagno** [comment]
You should be able to fork the project and send down a PR :)

**Comment by RanaInside** [comment]
Hi James, sorry about the late reply; there is a slight issue; on iOS device, current nuget package works, but not the source code. It took a bit of finding, but I finally nailed it down to the last commit:

https://github.com/jamesmontemagno/Xamarin.Plugins/commit/200ac0e7d64389b7b78bc8ee2b4ca6ab0ee25c22

and the method GetSpeechUtterance is the culprit. So I'm not sure how to proceed; fix that bug and add new method?

I don't have WinPhone 8, so from your project, I could only update droid and ios; without actual testing, the others look as if it should also work.

**Comment by jamesmontemagno** [comment]
Moved to: https://github.com/jamesmontemagno/TextToSpeechPlugin/issues/2
