### ISSUE TITLE
Xam.Settings: consider transparent json serialization

### ISSUE THREAD

**Issue by nirinchev** [jamesmontemagno/Xamarin.Plugins#40]
On iOS if I try to persist a non-value type, there's an exception thrown in the default case. Is there a reason we can't use Json.NET to serialize to/from string? I know it's kind of encouraging bad design, but still, would be useful in some cases.

**Comment by jamesmontemagno** [comment]
You are able to do this manually, however I do not support this in the current implementation and have no plans on it at this time.
