### ISSUE TITLE
Xam.Geolocator on iOS: GetPositionAsync never returns after a position error

### ISSUE THREAD

**Issue by vzsg** [jamesmontemagno/Xamarin.Plugins#41]
We've noticed that under specific circumstances, the Geolocator plugin can get stuck and never return or throw:

1) Given the geolocator instance is used concurrently by a watcher, i.e. `StartListening` was called;
2) positioning fails for whatever reason, the PositionError event is triggered;
3) and another client calls GetPositionAsync after that.

My guess is that while the last position is handled [here](https://github.com/jamesmontemagno/Xamarin.Plugins/blob/master/Geolocator/Geolocator/Geolocator.Plugin.iOS/GeolocatorImplementation.cs#L139), the error state is not saved, though CLLocationManager doesn't send the same notification again.

Temporarily, it seems that calling StopListening/StartListening in pair before GetPositionAsync works around this.

**Comment by jamesmontemagno** [comment]
is this still a valid issue? I know there have been a lot of changes to the code.

**Comment by vzsg** [comment]
I'll see if I can whip up a test project later next week (I don't have a Xamarin env installed anymore).

The line marker is obviously outdated in the original post. In the current version, it seems `StopListening()` is called in case of an error, so it _might_ have been already fixed.
