### ISSUE TITLE
[CircleImage] BackgroundColor issue

### ISSUE THREAD

**Issue by tkowalczyk** [jamesmontemagno/Xamarin.Plugins#42]
When I set a `BackgroundColor` property `CircleImage` is no longer circle on Android.
Sample code:

    `CircleImage startPomoButton = new CircleImage()
                {
                    BorderColor = Color.FromHex(StaticData.ViewStartButtoColor),
                    BackgroundColor = Color.FromHex(StaticData.ViewStartButtoColor),
                    BorderThickness = 5,
                    HeightRequest = 60,
                    WidthRequest = 60,
                    Source = StaticData.ViewStartButtoImage,
                    VerticalOptions = LayoutOptions.Start,
                    HorizontalOptions = LayoutOptions.End,
                };`

**Comment by jamesmontemagno** [comment]
BackgroundColor is not supported. You can use the BorderColor for this, but we cut the circle out of the image.
