### ISSUE TITLE
How to use CircleImage in XAML

### ISSUE THREAD

**Issue by JoshuaNovak919** [jamesmontemagno/Xamarin.Plugins#43]
I am trying to use CircleImage in Xaml, but it doesn't seem to want to work. Anyone know how to make it work?

I added this to my ContentPage tag:
`xmlns:ic="clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=MyApp"`

Xaml Code:
`<ic:CircleImage Source="misc/example_image.jpg" WidthRequest="50" HeightRequest="50" Aspect="AspectFill" HorizontalOptions="Center" />`

**Comment by jamesmontemagno** [comment]
Chance the xmlns to:
xmlns:ic="clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions"

**Comment by jamesmontemagno** [comment]
I added documentation for it.

**Comment by JoshuaNovak919** [comment]
Works great now. Thanks!
