### ISSUE TITLE
Plans for supporting .NET 4.5 application in Xam.Plugin.Connectivity?

### ISSUE THREAD

**Issue by SimonSimCity** [jamesmontemagno/Xamarin.Plugins#45]
Hi,

I am currently writing a C# connector for an API, that I want to share in a Xamarin and a pure .NET application.

We lately thought about implementing `Xam.Plugin.Connectivity` in there, but since it has no pure .NET support, we didn't quite know how to implement that.

Are there any plans on adding support for that?

**Comment by jamesmontemagno** [comment]
I currently do not plan on doing this as I don't focus on WPF, but anyone is free to contribute.

**Comment by SimonSimCity** [comment]
Thanks for the response.

I solved it by using a compiler condition:
```
#if (__MOBILE__ || WINDOWS_PHONE || SILVERLIGHT)
            var isConnected = CrossConnectivity.Current.IsConnected;
#else
            var isConnected = true;
#endif

See http://developer.xamarin.com/guides/cross-platform/application_fundamentals/building_cross_platform_applications/part_4_-_platform_divergence_abstraction_divergent_implementation/#Conditional_Compilation for further details.
