### ISSUE TITLE
Please add support for background mode.

### ISSUE THREAD

**Issue by jinlook** [jamesmontemagno/Xamarin.Plugins#49]
Just like this one.
https://github.com/katzer/cordova-plugin-background-mode

It is a cool plugin for cordova, I wish we could have the same one in xamarin plugins.
Also, the https://github.com/katzer have several other good plugins. 
Please make one or two happened in xamarin world~

**Comment by jamesmontemagno** [comment]
Can you please post this idea over at http://www.github.com/xamarin/plugins thanks!
