### ISSUE TITLE
Connectivity Plugin crashes a Foreground Service without activities in the background

### ISSUE THREAD

**Issue by ertay** [jamesmontemagno/Xamarin.Plugins#50]
Hey James,

You can find a demo solution here: http://1drv.ms/1xvg1lq

Steps to reproduce:
1. Launch app.
2. Open recent apps list
3. Swipe the app to left/right to kill the activity
4. Foreground Service should be running still (notification should still be visible in the notification center).
5. Now turn on or off  WiFi (it must connect to an access point)

At this point the service should crash without giving any errors. Debugger should also detach immediately without anything on the output window. 

Weird thing is, if the UI isn't killed (if you skip step 3 above) the service does not crash.

You will notice that no code is used in the solution from the Connectivity plugin. It only has to be installed in the project(s). Uninstalling the plugin from the projects fixes the issue.

Cheers,
Ertay

**Comment by jamesmontemagno** [comment]
Please check out package 1.0.2 now on GitHub.

I do believe that there are some potential crashers in your code when try to get the Activity from MVVMCross. Instead of using the .Activity simply use the ApplicationContext to create your intents. I would be concerned about MVVMCross having to be Init again in service as well so be aware of that too.

**Comment by ertay** [comment]
Hmmm, the steps I listed above don't say that you need to open the activity. (or maybe you were talking in general and not related to the Connectivity crash). But my app works fine once I removed the old connectivity plugin (will try 1.0.2 ).

**Comment by jamesmontemagno** [comment]
It was an issue with the broadcast receiver that I had implemented. I simply register and unregister in the implementation.
