### ISSUE TITLE
How To access to contacts images in Xamarin.Plugins.Contacts

### ISSUE THREAD

**Issue by gabrielacosta** [jamesmontemagno/Xamarin.Plugins#52]
Hi James,

I was working with Xamarin.Mobile and I know that there the object Contact has the property GetThumbnail() that returns the current bitmap of the contact photo.

I checked your implementation and that method does not exist. There is any way that I can access to the contact photos with your library or I can implemented if you give more details how to can be done.

Also, when I was trying to use the GetThumbnail() from Xamarin.Mobile, I found it complicated to use because it was better if you can have the URI where the image is stored that return the entire image.

Could you give your ideas, how to implemented this in a better way using your library. By the way, good job creating all this libraries.

Regards,

Gabriel

**Comment by jamesmontemagno** [comment]
This is not currently implemented. It is still in beta. I am not sure when I will get around to finishing this one, it is really tricky.

**Comment by gabrielacosta** [comment]
Hi James,

Thank you for your answer. If you tell how can I possible implemented, I could give a try. If I make it work, I will make a pull request with that implementation. 
But, I need your architectural advise of how do you think it can be done, and which parts of the library I have to modify.

Regards,

G

**Comment by gabrielacosta** [comment]
Hi James, 

I was looking another ways to solve the problem of manage contacts image crossplatform and I believe the best option is to add splat library to your project. https://github.com/paulcbetts/splat

Because, It will give the opportunity of have one generic class IBitmap and make the proper resolution using the ToNative implemented in splat library.

I checked the code for Contacts and it is a lot of work. I'm still thinking it is possible, if you pass me some document about  the architecture or where I can find it. I will try to make some progress.

Kind regards,

Juan
