### ISSUE TITLE
CrossConnectivity.Current.IsConnected returns false after device is put in flight mode

### ISSUE THREAD

**Issue by jorgenstorlie** [jamesmontemagno/Xamarin.Plugins#54]
I use this code:

bool result = CrossConnectivity.Current.IsConnected;

If I turn on flight mode it still returns true

If I try to access the internet in safari of Facebook before I do the check it returns false

**Comment by jamesmontemagno** [comment]
Which platform does this repo on?

**Comment by jorgenstorlie** [comment]
It is IOS

Den mandag 13. april 2015 skrev James Montemagno <notifications@github.com>
følgende:

**Comment by Brosten** [comment]
I have the same issue.
- If I start the app in flight mode, IsConnected still returns true.
- When I switch flightmode on/off the "CurrentConnectivityChanged event does not fire.

However, this is on the WinPhone 8.1 platform!

**Comment by poppywood** [comment]
I have the same issue in Xamarin Forms App, with both iOS and Android. I put the device into flight mode and IsConnected continues to return true.

**Comment by jamesmontemagno** [comment]
Tested against iPhone 5s and is working as implemented. It takes a few seconds for it to change and fully loose connectivity. The re-connect is faster.

**Comment by jorgenstorlie** [comment]
any reason it is not changed immediately?

**Comment by jamesmontemagno** [comment]
It is whenever iOS triggers the event so it is just as fast as iOS tells me.

**Comment by Brosten** [comment]
Hello friend, 

I've selected  a couple of great things for you, please take a look, you'll love them <http://discount.buffaloweddingpros.com/e4jox>

Yours sincerely, andreas

**Comment by Brosten** [comment]
Hi,
I've  picked a couple  of nice  things that might interest you, please  take a look <http://noemi.loonylounge.com/e4qjp/816>

My Best, andreas

**Comment by Brosten** [comment]
Hey, 

I've just seen something you'd never believe! Just take a look at this  cool  stuff <http://lucio.noisecircuit.net/e4fhr/33>

Looking forward, andreas

**Comment by Brosten** [comment]
Dear! 

Have  you ever seen that stuff? That's exetremely interesting, just take a  look here <http://giovnni.chrismartins.com/e4af/685>

All best, andreas
