### ISSUE TITLE
ImageCircle bug in Android

### ISSUE THREAD

**Issue by marcojak** [jamesmontemagno/Xamarin.Plugins#55]
Hi,

I'm using ImageCircle in a viewCell of a ListView.

as BindingContextChanged is use this method:

void ReadingCell_BindingContextChanged(object sender, EventArgs e)
        {
            var c = BindingContext as DbModel.Reading;
            _circleT.BorderColor = MyColor.GetTemperatureColour(c.temperature);
        }

I change the borderColor using a temperature.
On the visible cells, all work as expected, but if I scroll the ListView and then I return up to the previous cells, I see that the borderColor of the previous cells is now wrong (the color is the same of the ImageCircles on the screen before I scroll up).

On iOS all work perfect, i can scroll as much as i want and all the imagecircles still have the correct color.

**Comment by jamesmontemagno** [comment]
I should have a fix today. I wasn't checking for changes there to invalidate.

**Comment by jamesmontemagno** [comment]
1.0.11 is live
