### ISSUE TITLE
CrossConectivity return false in emulator

### ISSUE THREAD

**Issue by gabrielacosta** [jamesmontemagno/Xamarin.Plugins#56]
Hi James,

I was trying to use the Connectivity.Plugin.CrossConnectivity to checked the current connectivity of the device. However, the  method Current.IsConnected is always false even if  I have internet active in the emulator device. Can you give a hint of use it or let me know if required an specific permission besides 
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STAT" />

 public async Task isConnected(Activity activity) 
        {
            hasInternetActive = true;
            if (!Connectivity.Plugin.CrossConnectivity.Current.IsConnected)
            {
                bool accessedGoogle = await checkRemoteConnectivity();
                if (!accessedGoogle)
                {
                    hasInternetActive = false;
                }
            }            
        }

**Comment by jamesmontemagno** [comment]
for which platform is this happening on?

**Comment by gabrielacosta** [comment]
Sorry, James I just found the error was some misconfiguration in the emulator. Now, it is working fine. Thanks for your help.

**Comment by jamesmontemagno** [comment]
That is great to hear, can you share what you had to change incase anyone
else has the issue.

On Sun, May 10, 2015 at 6:46 PM, gabrielacosta <notifications@github.com>
wrote:

> Sorry, James I just found the error was some misconfiguration in the
> emulator. Now, it is working fine. Thanks for your help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jamesmontemagno/Xamarin.Plugins/issues/56#issuecomment-100736262>
> .
>



-- 
James Montemagno
http://www.montemagno.com
@jamesmontemagno <http://www.twitter.com/jamesmontemagno>
