### ISSUE TITLE
Settings Plugin for Xamarin doesnt save key value in the first run

### ISSUE THREAD

**Issue by sirfilipef** [jamesmontemagno/Xamarin.Plugins#58]
i developing a app that in the first run get a userid from the server. i want to store it locally, however i cant do it on android. i save the value and then try to get it and the value doesnt exists.
if i close the app and open it again the value is stored.
In IOS works fine. Any idea?

**Comment by jamesmontemagno** [comment]
Do you have the code snippet where you are saving it?

Your get/set?

**Comment by sirfilipef** [comment]
My Settings class:

private static readonly string SettingsDefault = string.Empty;
public static string GetSettings(string key)
 {
      return AppSettings.GetValueOrDefault(key, SettingsDefault);
 }
public static void SetSettings(string key, string value)
{
       AppSettings.AddOrUpdateValue(key, value);
}

My set:
Helpers.Settings.SetSettings("followerId", response["followerId"].Value<string>());
(i confirm that my response as the followerid value)

my get:
Helpers.Settings.GetSettings("followerId")

I try to define the key in the settings class and problem still happens.

Could this be a problem with the Android Context?

**Comment by sirfilipef** [comment]
When i do:

**Comment by sirfilipef** [comment]
When i do:

Helpers.Settings.GeneralSettings = "12343241234321";
string b = Helpers.Settings.GeneralSettings;

in the same page works fine. 

When i do the set in one page and the set in another, the string is empty

**Comment by jamesmontemagno** [comment]
You can try 1.5.1 which I just pushed. Are you able to do this:

string test = response["followerId"].Value();
Helpers.Settings.SetSettings("followerId", test);

**Comment by sirfilipef** [comment]
James, thanks for the quick response.

I think the issue is fixed.
I updated to 1.5.1 and tested the code snippet suggested, and works.
I'll do more tests to be sure. 

I tested with:
Nexus 5 - (android 5.1)
Galaxy Nexus - (android 4.0.3)
IPad (4th Gen) - (IOS 8.3)
IPhone 4 - (IOS 7.1.1)
Iphonw 6 - (Emulator - IOS 8.3)

**Comment by jamesmontemagno** [comment]
This is great to hear thanks!
