### ISSUE TITLE
[Settings] PutStringSet Missing

### ISSUE THREAD

**Issue by De4th69** [jamesmontemagno/Xamarin.Plugins#59]
Hi,
I wanted to add the functionality for `PutStringSet` to the Settings-Plugin. But it can't be resolved.
I've used it in another app before. 
I Decompiled `ISharedPreferenceEditor` and it is missing.
Did that got thrown out or what happened?
I mean you can look at it in the Android Dev Guide. http://developer.android.com/reference/android/content/SharedPreferences.Editor.html#putStringSet%28java.lang.String,%20java.util.Set%3Cjava.lang.String%3E%29

**Comment by jamesmontemagno** [comment]
Hey there, This is because I have it targeting API 2.3. PutStringSet was introduced in API 3.0 (11). You can change the target framework in the Android project property options.

**Comment by De4th69** [comment]
Ah ok. I was able to add the functionality :)
