### ISSUE TITLE
Geolocator fails on WinRT Phone 8.1

### ISSUE THREAD

**Issue by RandomEngy** [jamesmontemagno/Xamarin.Plugins#60]
I'm getting an exception thrown from CrossGeolocator.Current on a Windows Phone RT 8.1 app:

Operation aborted

You must set the MovementThreshold property or the ReportInterval property before adding event handlers.

This is with the Location capability for the app enabled.

**Comment by jamesmontemagno** [comment]
Fixed in 1.0.2

**Comment by RandomEngy** [comment]
Thanks!

**Comment by ZeAleks** [comment]
I'm getting the same exception here when my app is resuming and I try to start listening again.

'locator.DesiredAccuracy = 5' threw an exception of type 'System.Exception'
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2147467260
    HelpLink: null
    InnerException: null
    Message: "Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))"
    Source: "Windows"
    StackTrace: "   at Windows.Devices.Geolocation.Geolocator.put_DesiredAccuracy(PositionAccuracy value)\r\n   at Plugin.Geolocator.GeolocatorImplementation.set_DesiredAccuracy(Double value)"

Did I miss something ?

Thank you
Alek
