### ISSUE TITLE
Default value and nullables doesn't work very well

### ISSUE THREAD

**Issue by MihaMarkic** [jamesmontemagno/Xamarin.Plugins#61]
Hi,

Try this in Android
 ```c#
int? id = AppSettings.GetValueOrDefault<int?>("key", (int?)null);
 ```
it will return 0 when key doesn't exist.
i think ContainsKey method would come handy when you simply want to check for key presence anyway (it could be present with null value).
I can create a pull request if it makes sense.

**Comment by jamesmontemagno** [comment]
Nullables are not supported. I have listed all acceptable values. Unfortunately, the underlying frameworks do not allow nulls.
