### ISSUE TITLE
How to handle settings property changed

### ISSUE THREAD

**Issue by JoshuaNovak919** [jamesmontemagno/Xamarin.Plugins#62]
I have some settings bound to a view in my app, but when I update the settings the view does not update. Does anyone know how to properly handle this? I didn't find it in the docs or the forums, so I posted it here.

**Comment by jamesmontemagno** [comment]
You would have to trigger a property change somehow. Best maybe is to put some property getters/setting in your ViewModel that interact with the Settings...

**Comment by JoshuaNovak919** [comment]
@jamesmontemagno I figured that's what i'd probably have to do, I just wasn't sure if it was the correct way to handle it. Thanks for getting back to me!
