### ISSUE TITLE
Background color Android

### ISSUE THREAD

**Issue by marcojak** [jamesmontemagno/Xamarin.Plugins#63]
If i set a background color, inside a ImageCircle, under iOS is perfect but under Android the background color is a square and goes beyond the limits of the circle.

**Comment by jamesmontemagno** [comment]
It is not support on Android. We have to cut the circle out of the frame. I recommend using the border color for it. Sorry, android works the opposite. 

A feature I might try to add is "innerfillcolor", which you could probably add in the android renderer.
