### ISSUE TITLE
Geolocator fails with infinite timeout on WinRT Phone 8.1

### ISSUE THREAD

**Issue by RandomEngy** [jamesmontemagno/Xamarin.Plugins#64]
The Geolocator now works on Windows Phone when you supply a positive timeout. However if you leave that argument as default (-1), it will throw an ArgumentException.

A side note, the XML docs or argument name should probably mention what the units are for the timeout. Presumably milliseconds?

**Comment by jamesmontemagno** [comment]
Intriguing... It is milliseconds. I will update docs. I think someone made a change to the timeout. Let me investigate.

**Comment by jamesmontemagno** [comment]
Should be fixed in 1.0.3-alpha2
