### ISSUE TITLE
Add support in Media Plugin to also show video inside an app from a file or web stream.

### ISSUE THREAD

**Issue by iitr-ankur** [jamesmontemagno/Xamarin.Plugins#65]

**Comment by jamesmontemagno** [comment]
Do you mean you want to display a video in the app?

You should be able to use the native controls on each. Can you add more context to this request.

**Comment by iitr-ankur** [comment]
Yes, I want to display video inside an app. There is no cross-platform Video View and that is what I need. It would be nice if there is such an option. Currently I am using VideoView & MediaController in Android.

**Comment by jamesmontemagno** [comment]
This is the correct way to do it. You would only need a cross platform VideoView for Xamarin.Forms else they should be implemented like you are natively. I do not have any current plans to implement this, but thank you for your feedback.
