### ISSUE TITLE
NavigateTo() fails on some Android devices

### ISSUE THREAD

**Issue by IlSocio** [jamesmontemagno/Xamarin.Plugins#66]
Hi James,
the NavigateTo() is broken on some devices (eg. Samsung Galaxy S4 Android 4.2.2) 
it is caused by the "(name)" which doesn't seems to be parsed properly by Maps.
After deleting the "(name)" the navigation starts correctly.

https://github.com/jamesmontemagno/Xamarin.Plugins/blob/master/ExternalMaps/ExternalMaps/ExternalMaps.Plugin.Android/ExternalMapsImplementation.cs

I would suggest to change the format string in something like this:
`
var uri = String.Format("http://maps.google.com/maps?&daddr={0},{1}", latitude.ToString(CultureInfo.InvariantCulture), longitude.ToString(CultureInfo.InvariantCulture));
if (!string.IsNullOrEmpty(name))
{
   uri += " ("+name+")";
}
`

Marco.

**Comment by jamesmontemagno** [comment]
Wouldn't this still have an issue if you are still putting in the name? It seems like we would need to remove it completely? Yes?

Is Google Maps fully up to date?

**Comment by IlSocio** [comment]
Completely removing the name, will fix the issue for sure.
I suggested to keep it optional just to maintain the compatibility with existing code and it seems be working fine in almost all the cases.
Like you, I suppose it's more related to Google Maps application which is not updated to the latest version, so it doesn't parse properly the "(name)" parameter.
Unfortunately, it's hard for me to collect further details, because the issue has been reported during a beta-testing stage performed by a 3rd party.
