### ISSUE TITLE
Hardcoded circle image inset for Android

### ISSUE THREAD

**Issue by rudyryk** [jamesmontemagno/Xamarin.Plugins#68]
There's a strange inset on Android for circle image. As I understand it is hardcoded here:
https://github.com/jamesmontemagno/Xamarin.Plugins/blob/master/ImageCircle/ImageCircle.Forms.Plugin.Android/ImageCircleRenderer.cs#L69

```csharp
var radius = Math.Min(Width, Height) / 2;
var strokeWidth = 10;
radius -= strokeWidth / 2;
```

What is the point? Should we use `BorderThickness` there? Like that:

```csharp
var radius = Math.Min(Width, Height) / 2;
var strokeWidth = ((ImageCircle.Forms.Plugin.Abstractions.CircleImage)Element).BorderThickness;
radius -= strokeWidth / 2;
```

**Comment by jamesmontemagno** [comment]
Hmmmm yes, most likely. I will adjust this and publish new package.

**Comment by rudyryk** [comment]
Thank you! Looking forward for an update :)
