### ISSUE TITLE
[Feature Request] TakeVideoAsync & TakePictureAsync saves file within App folder. No option to provide absolute path and save in external storage.

### ISSUE THREAD

**Issue by iitr-ankur** [jamesmontemagno/Xamarin.Plugins#69]
I would like to save file here:

var _dir = new Java.IO.File(Android.OS.Environment.GetExternalStoragePublicDirectory(Android.OS.Environment.DirectoryMovies), "MyAppName");

Also, these files are not visible in the gallery apps. Would prefer if there is an optional bool parameter to do so. Currently, I use following code to achieve this:

Intent mediaScanIntent = new Intent (Intent.ActionMediaScannerScanFile);
Android.Net.Uri contentUri = Android.Net.Uri.FromFile (_file);
mediaScanIntent.SetData (contentUri);
SendBroadcast (mediaScanIntent);

**Comment by jamesmontemagno** [comment]
You can now save external with the "SaveToAlbum" in 2.1.0-beta1
