### ISSUE TITLE
[Feature Request] Add support for Audio in Media Plugin.

### ISSUE THREAD

**Issue by iitr-ankur** [jamesmontemagno/Xamarin.Plugins#73]
Would love to have a cross platform plugin for audio which can:
a) Record audio. (see http://developer.xamarin.com/guides/android/application_fundamentals/working_with_audio/ for android)
b) Play audio. (or open other apps to play. )

**Comment by deckertron9000** [comment]
I'm going to fork and take a crack at at this. I'll start with recording and choosing pre-existing audio files to match the current photo and video support. @jamesmontemagno if you have any design preferences let me know, otherwise I'll just stick to matching the existing architecture.

**Comment by jamesmontemagno** [comment]
A new suggestion should be posted on http://github.com/xamarin/plugins

These fall out of scope of the media plugin and an Audio plugin could be created.
