### ISSUE TITLE
[Feature Request] Media - overlay

### ISSUE THREAD

**Issue by LostBalloon1** [jamesmontemagno/Xamarin.Plugins#77]
Hi,

I'm not too sure how it is on android, but for iOS, the native media picker supports the possibility of adding an overlay.

The use I would have for an overlay is, similar to how the Nexus 5 default camera does when recording videos, the possibility to add a clear indicator telling the users to capture in landscape as the content created in my case targets widescreens.

There are a few ways I see as possibilities:
1- nullable svg property (probably not the best and most intuitive)
2- svg property & possibility to show/hide (this would be more than enough to satisfy my requirements)
3- custom view & possibility to show/hide (probably ideal since more flexible)

As stated in my other issue, I would not mind adding it to the implementation myself if need be (and if you have any design preferences, I'm all ears)

**Comment by LostBalloon1** [comment]
I have an implementation of this (iOS only) that responds to my apps needs, I have the changes in my fork https://github.com/LostBalloon1/Xamarin.Plugins/ 

I did not issue a pull request as I've only implemented for iOS.

**Comment by jamesmontemagno** [comment]
Scope is too large for plugin.

**Comment by LostBalloon1** [comment]
I understand your concern, but since your plugin basically hides the native implementations of the pickers, it is impossible for us to even add one unless we modify your sources.

All that is really needed is having the possibility to provide the overlay's UI to the picker. In my own implementation (which I've done for iOS) it was only a [very] few lines of code.

I see that it isn't impossible on Android, I can't tell how complicated it is, but again, it doesn't need to be something crazy, just an entry point.

I would really rather not have to maintain a fork indefinitely for one feature.

**Comment by jamesmontemagno** [comment]
These could be extensions into the core PCLs there isn't going to be an easy way of doing a cross platform API on that, however it could be an extension on iOS or Android. If you have the implementation you can do a pull request. I personally have no plans to add it in right now, but open to pull requests.

**Comment by LostBalloon1** [comment]
Sounds good, I'll need to synchronize myself to your new version and retest. I'll submit a pull request as soon as I get the chance to work on this.
