### ISSUE TITLE
Support for Thumbnails in Contacts plugin

### ISSUE THREAD

**Issue by ttoconnell** [jamesmontemagno/Xamarin.Plugins#78]
It looks like Thumbnail feature for a Contact was almost implemented, but it was commented out in this file: 
https://github.com/jamesmontemagno/Xamarin.Plugins/blob/master/Contacts/Contacts.Plugin.Shared/Contact.cs

It is very important to have this feature. Is this something that will be added soon?

Thanks in advance,
Tom

**Comment by iducool** [comment]
:+1: 
Thanks for great work. Thumbnail feature is very important for everyone.

**Comment by rlingineni** [comment]
Is this supported? I would love to have thumbnail support.

**Comment by jamesmontemagno** [comment]
It is not currently support, which is why the issue is still open.

**Comment by rlingineni** [comment]
Right. I just wanted to bump the request :+1:

**Comment by bbougot** [comment]
Indeed, really need this!

**Comment by jamesmontemagno** [comment]
Moved to: https://github.com/jamesmontemagno/ContactsPlugin/issues/1
