### ISSUE TITLE
ImageCircle doesn't work in iOS Release Build with 'Link SDK Assemblies Only' set.

### ISSUE THREAD

**Issue by renzska** [jamesmontemagno/Xamarin.Plugins#79]
When building in Release mode for iOS Xamarin.Forms, the ImageCircle does not work when the Linker Options are set to "Link SDK Assemblies Only". It just displays the regular image. If I change it to "Don't Link" it works and shows the ImageCircle.

I have gotten it to work with the "Link SDK Assemblies Only" option set by either of the two options:

1. Changing the Init method declaration to:
 - public async static void Init(){} //added async, but don't actually call it with await
2. Adding some arbitrary call inside of the init like:
 - var temp = DateTime.Now;

I'd like to continue to reference the nuget package to make sure I get the latest fixes. 
This is using Xamarin Studio v5.9.3 build 1. Latest stable release for all components as of today. Running Build Release on an iPhone 6 Plus.

Thanks,

John Rennemeyer

**Comment by jamesmontemagno** [comment]
I have gotten it to work just fine with these settings in My Shoppe.

However I will make both of these adjustments just incase.

**Comment by jamesmontemagno** [comment]
See 1.0.14 now with both of these changes.
