### ISSUE TITLE
iOS Status Bar Tint Reverts to Black after selecting photo

### ISSUE THREAD

**Issue by highplains** [jamesmontemagno/Xamarin.Plugins#80]
Media / Camera Plugin
Xamarin Forms 1.4.2.6359
iOS 8.3
Occurs in both Simulator and on Device

After selecting a photo from the iOS library the status bar seems to revert to black. Please see attached images for before and after.

Issue does not appear to exist when using the camera and taking a new picture.

![img_1805](https://cloud.githubusercontent.com/assets/1825076/8337238/2af9a7a8-1a67-11e5-867f-b4ceff6a6af5.PNG)
![img_1806](https://cloud.githubusercontent.com/assets/1825076/8337240/31b6ed12-1a67-11e5-9fa9-3dc7d32b7c87.PNG)

**Comment by jamesmontemagno** [comment]
On your View Did Appear can you set:
NavigationController.NavigationBar.BarStyle = UIBarStyle.Black; 

See:
http://motzcod.es/post/110755300272/ios-tip-change-status-bar-icon-text-colors

**Comment by highplains** [comment]
I'm actually doing this in a Xamarin.Forms app in the PCL.

**Comment by jamesmontemagno** [comment]
Fixed in Alpha8, it was really tricky actually as this is a big bug in iOS in general. What I am doing is saving out your status bar style and then setting it back on dismiss.

**Comment by highplains** [comment]
lol i was just about to submit a pull for you on this one. I was playing with it as well and came to your same conclusion, and fix. Tested Alpha8 and it works, thanks!

**Comment by jamesmontemagno** [comment]
Yeah, it was actually really tricky as there was no great solutions out there and I didn't want you as a developer to have to add an additional field at all.
