### ISSUE TITLE
iOS project looking for GeolocatorReadme.txt

### ISSUE THREAD

**Issue by fgiacomelli** [jamesmontemagno/Xamarin.Plugins#83]
Hello,
I've this problem, I've a project in Xamarin Forms, when I build the project for iOS it tell me that the file GeolocatorReadme.txt under PluginsHelp folder is missing.
Simply create a blank file solve the problem

**Comment by jamesmontemagno** [comment]
This should get installed with the nuget.

What IDE are you using?

**Comment by fgiacomelli** [comment]
Visual studio 2013.
I've another problem that seems to be much more serious: I can't obtain GPS coordinates from ios, while with the same code (using the getpositionasync) under Android it works well.
Can you help me? Do have I to do something different for ios platform?
Thank you 

----- Messaggio originale -----
Da: "James Montemagno" <notifications@github.com>
Inviato: ‎16/‎07/‎2015 21:44
A: "jamesmontemagno/Xamarin.Plugins" <Xamarin.Plugins@noreply.github.com>
Cc: "fgiacomelli" <fgiacomelli@gmail.com>
Oggetto: Re: [Xamarin.Plugins] iOS project looking for GeolocatorReadme.txt(#83)

This should get installed with the nuget.
What IDE are you using?

**Comment by jamesmontemagno** [comment]
It is the same code, just ensure you install the NuGet in all of them. I have examples in the sample project and also: https://github.com/jamesmontemagno/coffee-filter
