### ISSUE TITLE
Current	System.IO.FileNotFoundExceptio

### ISSUE THREAD

**Issue by NimaGhaedsharafi** [jamesmontemagno/Xamarin.Plugins#85]
CrossGeolocator.Current	System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b0…

**Comment by jamesmontemagno** [comment]
Is this in release mode? Did you set all linking perhaps? Seems odd.... Need more context. Did you install the NuGets into ALL projects?

**Comment by NimaGhaedsharafi** [comment]
Hi, sry for late, 

Yes i just have a shared project and a droid project. I added the Nuget package to the droid.

**Comment by NimaGhaedsharafi** [comment]
I figured it out whats the problem but too wired to me!!
setting default shared preferences  to (this) make the null pointer exception problems!!
i had a static class like this to set and get the context statically. 
```
using System;
using Android.App;
using Android.Content;

namespace Nabsh.Droid
{
	public class MyApp: Application
	{
		private static Context context;

		public MyApp(Context c)
		{
			MyApp.context = c;
		}

		public static Context getAppContext() {
			return MyApp.context;
		}
	}
}
```
and i get the context form this class and set it as default 
```PreferenceManager.GetDefaultSharedPreferences (Nabsh.Droid.MyApp.getAppContext()); ```

now I changed my code to this, 
```PreferenceManager.GetDefaultSharedPreferences (Android.App.Application.Context); ```
and now it's works well!

thanks :)

**Comment by NimaGhaedsharafi** [comment]
I share my problem's solution and hope it will saves people some time.

**Comment by jamesmontemagno** [comment]
This is what I am doing: https://github.com/jamesmontemagno/Xamarin.Plugins/blob/master/Settings/Refractored.Xam.Settings.Android/Settings.cs#L30

**Comment by NimaGhaedsharafi** [comment]
I will check again GeoLocator and will comment the results

**Comment by jamesmontemagno** [comment]
Closing again as there seems to be no issue by anyone else using this plugin.
