### ISSUE TITLE
Error when installing from Nuget VS2015

### ISSUE THREAD

**Issue by khoacoi** [jamesmontemagno/Xamarin.Plugins#86]
Hi,
I'm facing with this error when installing from Nuget in VS2015:

Install-Package : Could not find a part of the path 'C:\Users\username\.nuget\packages\Xam.Plugins.Settings\1.5.1\content\portable-net45%2Bwp8%2Bwpa81%2Bwin8%2BMonoAndroid10%2BM
onoTouch10\Helpers\Settings.cs.pp'.
At line:1 char:16
+ Install-Package <<<<  Xam.Plugins.Settings
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Could you please help?

Thanks,

**Comment by jamesmontemagno** [comment]
Fixed in 1.5.2, just published.

**Comment by jamesmontemagno** [comment]
This actually seems to be an issue with VS 2015 NuGet Package manager that it can't find the cs.pp
Work around is to create a folder called Helpers and create a Settings.cs in there. :(

**Comment by khoacoi** [comment]
The issue is because of the folder url :portable-net45+wp8+wpa81+win8+MonoAndroid10+M
onoTouch10 has been encoded and changed toportable-net45%2Bwp8%2Bwpa81%2Bwin8%2BMonoAndroid10%2BM
onoTouch10.  It cannot add reference to project sucessfull

**Comment by rmdaustin** [comment]
I'm seeing a similar issue with Xam.Plugin.Connectivity.  Installs into the platform projects okay, but in the Xamarin.Forms PCL project I get this error:

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\rmdne\.nuget\packages\Xam.Plugin.Connectivity\1.0.2\content\portable-net45%2Bwp8%2Bwpa81%2Bwin8%2BMonoAndroid10%2BMonoTouch10%2BXamarin.iOS10\PluginsHelp\ConnectivityReadme.txt.pp'.

If you url decode that path, the file DOES exist.  So it seems to be an erroneous URL encoding taking place.  But I'm wondering why it happens specifically for Xamarin.Plugins packages.  Other packages install fine into the same PCL (for example, I just installed AutoMapper--but that seems to use dynamic targeting).

**Comment by jamesmontemagno** [comment]
I have created an new issue: https://github.com/NuGet/Home/issues/1087

**Comment by jamesmontemagno** [comment]
Going to close as there is a work around and now fixed in the NuGet library and is out of my control
