### ISSUE TITLE
Plugin TTS doesn't work on iOS 8.x

### ISSUE THREAD

**Issue by guyprovost** [jamesmontemagno/Xamarin.Plugins#88]
AVSpeechSynthesizer is known to have a bug under iOS 8.x when using something other than default voice/non high quality voice.

Workaround here : http://stackoverflow.com/questions/24197952/avspeechsynthesizer-with-ios8

Guy

**Comment by jamesmontemagno** [comment]
Seems like this only effect 8.0.2? I have seen it work alright in my simulators.

**Comment by guyprovost** [comment]
Tested on iOS 8.4, real device + simulators... Does not work! Did you tried with a language other than the default English US ?

**Comment by jamesmontemagno** [comment]
@guyprovost I am pushing out a 1.0.2, could you give it a spin?

I also adjusted the default speak back to be .125 on iOS 8 as they doubled the speed for some reason.

Best,
James
