### ISSUE TITLE
iOS Geolocation Position Timestamp Daylight Savings Time ignored

### ISSUE THREAD

**Issue by mhirons** [jamesmontemagno/Xamarin.Plugins#89]
In my PositionChanged event handler, I am getting unexpected results on iOS for the Position TimeStamp.

I am in the Eastern timezone and we are currently observing DST.  If I get an event at 2PM, Android returns the following:
Timestamp() = 6PM, which is the correct UTC time.
Timestamp().ToLocalTime() = 2PM, which is my correct local time.

In iOS, I get the following:
Timestamp() = 1PM, which is my local time WITHOUT DST.
Timestamp().ToLocalTime() = 1PM, the same thing.

The device is showing the correct time and timezone.

Shouldn't iOS Timestamp() be the UTC time?
Shouldn't iOS Timestamp().ToLocalTime() take into account DST?

**Comment by jamesmontemagno** [comment]
Should be fixed in 1.0.3-alpha3
