### ISSUE TITLE
[Feature Request] Deleting photos taken using TakePhotoAsync

### ISSUE THREAD

**Issue by chance-kirsch** [jamesmontemagno/Xamarin.Plugins#90]
Thanks for your plugin, it work great, but I'm having an issue where it's saving the photos somewhere on my app's local storage. I call the dispose method like I'm supposed to, but right now, my app increase in data size with every picture I take. Is there a good way to fix this?

**Comment by Xmarker25** [comment]
Was there any solution to this? Is it possible to specify a location other than the app's local storage?

**Comment by jamesmontemagno** [comment]
Currently the photos are stored in your private folder, you can now as of 2.1.0 store to the gallery, which will not increase your app size. You could easily delete and clean photos with PCL Storage: https://github.com/dsplaisted/PCLStorage

The only thing I could think to add is a way of adding a "delete" flag to the media options, which would delete on dispose.
