### ISSUE TITLE
GetPositionAsync Async Really ?

### ISSUE THREAD

**Issue by guyprovost** [jamesmontemagno/Xamarin.Plugins#91]
Testing the geolocator plugin, using the sample code you provide, compiler says that cannot use await on a method that doesn't marked with the async modifier ???

var position = await locator.GetPositionAsync(timeout: 10000);

**Comment by jamesmontemagno** [comment]
@guyprovost you need to mark your method with async.

Such as:
public async Task MyAwesomeMethod()
{
  var position = await locator.GetPositionAsync();
}
