### ISSUE TITLE
TakePhotoAsync issue

### ISSUE THREAD

**Issue by FranciscoNieves** [jamesmontemagno/Xamarin.Plugins#94]
Hi, thanks for your package it's been so helpful to me.

Right now I'm facing a issue that I don't know how to resolve.

Sometimes, when trying to take a photo, if I change the device orientation, after taking the photo it seems like the page is reloaded, the photo taken is never shown on the image control, and after 3 attempts on take a photo, the app crashes.

Do you have any idea of what could be causing this issue?

Any suggestion will be helpful.

Thanks.

Note:

I'm currently using this Xamarin configuration:

Xamarin Studio 5.9.5

Xamarin.Forms 1.4.4.6392

**Comment by jamesmontemagno** [comment]
Haven't been able to reproduce.
