### ISSUE TITLE
iOS ImageCircle - Some images not appearing at all

### ISSUE THREAD

**Issue by redwards1966** [jamesmontemagno/Xamarin.Plugins#95]
I have ImageCircle in a custom ViewCell in a ListView in Xamarin Forms. In Android it renders all of the images fine but in iOS there is only a single image rendered. The rest are blank. I've checked the images urls and they seem fine and they are all jpg. Is there any issues with the image type in iOS?

**Comment by jamesmontemagno** [comment]
The first thing here is to try to not use ImageCircle and just use a normal Image from Xamarin.Forms. I don't do anything special to the image. Xamarin.Forms does all the downloading, caching, and rendering... I just make a circle :)

I would check the application output to see what is going on.
