### ISSUE TITLE
Media Component issue in xamarin.forms for android lollypop 5.1.1

### ISSUE THREAD

**Issue by DnyaneshwarWadghanePM** [jamesmontemagno/Xamarin.Plugins#97]
I am using Media.Plugin for xamarin.forms app. While getting picture from gallery specially on android 5.1.1, It does not showing. It's working on android kitkat properly . Is there any work around for this issue?

**Comment by jamesmontemagno** [comment]
Was able to verify locally, will test.

**Comment by jamesmontemagno** [comment]
Fixed this in latest 1.0.1-alpha1 for testing.
