### ISSUE TITLE
Media Plugin - PickPhotoAsync() - Android 5 Device - Hangs

### ISSUE THREAD

**Issue by hvaughan3** [jamesmontemagno/Xamarin.Plugins#99]
Everything works great with the Media plugin on the simulators. It also works great on an iOS device. When running on an actual Android device, I run the `PickPhotoAsync()` and the photo picker shows, I choose a photo, and am returned back to the original screen but then it just sits there loading for ever and an image never makes it into the `/tmp/` directory.

If, however, I do the following, everything works great:

`file = await CrossMedia.Current.PickPhotoAsync();`
`await Task.Delay(300);`

Not sure if it is because I am calling the async method, with the code above in it, from an event that I also marked as async or what. Hope this helps someone else!

**Comment by jamesmontemagno** [comment]
Not sure why you are using a Task.Delay in there.... Do you have more specifics on the version number of Android and Device? Are you trying the latest alpha?

**Comment by jamesmontemagno** [comment]
Please try official 1.0.1 package, just pushed.

**Comment by hvaughan3** [comment]
Was finally able to test it out and it works great. Thank you for the quick fix!
